// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2 (64-bit)
// Version: 2020.2
// Copyright (C) Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module example_proc_1 (
        ap_start,
        start_full_n,
        start_out,
        start_write,
        A_V_dout,
        A_V_empty_n,
        A_V_read,
        B_din,
        B_full_n,
        B_write,
        C_din,
        C_full_n,
        C_write,
        ap_clk,
        ap_rst,
        ap_done,
        ap_ready,
        ap_idle,
        ap_continue
);


input   ap_start;
input   start_full_n;
output   start_out;
output   start_write;
input  [31:0] A_V_dout;
input   A_V_empty_n;
output   A_V_read;
output  [31:0] B_din;
input   B_full_n;
output   B_write;
output  [31:0] C_din;
input   C_full_n;
output   C_write;
input   ap_clk;
input   ap_rst;
output   ap_done;
output   ap_ready;
output   ap_idle;
input   ap_continue;

reg start_write;

reg    real_start;
reg    start_once_reg;
wire    internal_ap_ready;
wire    proc_1_1_U0_ap_start;
wire    proc_1_1_U0_ap_done;
wire    proc_1_1_U0_ap_continue;
wire    proc_1_1_U0_ap_idle;
wire    proc_1_1_U0_ap_ready;
wire    proc_1_1_U0_start_out;
wire    proc_1_1_U0_start_write;
wire    proc_1_1_U0_A_V_read;
wire   [31:0] proc_1_1_U0_data_channel1_din;
wire    proc_1_1_U0_data_channel1_write;
wire   [31:0] proc_1_1_U0_data_channel2_din;
wire    proc_1_1_U0_data_channel2_write;
wire    proc_1_2_U0_ap_start;
wire    proc_1_2_U0_ap_done;
wire    proc_1_2_U0_ap_continue;
wire    proc_1_2_U0_ap_idle;
wire    proc_1_2_U0_ap_ready;
wire   [31:0] proc_1_2_U0_B_din;
wire    proc_1_2_U0_B_write;
wire   [31:0] proc_1_2_U0_C_din;
wire    proc_1_2_U0_C_write;
wire    proc_1_2_U0_data_channel1_read;
wire    proc_1_2_U0_data_channel2_read;
wire    ap_sync_continue;
wire    data_channel1_full_n;
wire   [31:0] data_channel1_dout;
wire    data_channel1_empty_n;
wire    data_channel2_full_n;
wire   [31:0] data_channel2_dout;
wire    data_channel2_empty_n;
wire    ap_sync_done;
wire    ap_sync_ready;
wire   [0:0] start_for_proc_1_2_U0_din;
wire    start_for_proc_1_2_U0_full_n;
wire   [0:0] start_for_proc_1_2_U0_dout;
wire    start_for_proc_1_2_U0_empty_n;
wire    proc_1_2_U0_start_full_n;
wire    proc_1_2_U0_start_write;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
end

example_proc_1_1 proc_1_1_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(proc_1_1_U0_ap_start),
    .start_full_n(start_for_proc_1_2_U0_full_n),
    .ap_done(proc_1_1_U0_ap_done),
    .ap_continue(proc_1_1_U0_ap_continue),
    .ap_idle(proc_1_1_U0_ap_idle),
    .ap_ready(proc_1_1_U0_ap_ready),
    .start_out(proc_1_1_U0_start_out),
    .start_write(proc_1_1_U0_start_write),
    .A_V_dout(A_V_dout),
    .A_V_empty_n(A_V_empty_n),
    .A_V_read(proc_1_1_U0_A_V_read),
    .data_channel1_din(proc_1_1_U0_data_channel1_din),
    .data_channel1_full_n(data_channel1_full_n),
    .data_channel1_write(proc_1_1_U0_data_channel1_write),
    .data_channel2_din(proc_1_1_U0_data_channel2_din),
    .data_channel2_full_n(data_channel2_full_n),
    .data_channel2_write(proc_1_1_U0_data_channel2_write)
);

example_proc_1_2 proc_1_2_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(proc_1_2_U0_ap_start),
    .ap_done(proc_1_2_U0_ap_done),
    .ap_continue(proc_1_2_U0_ap_continue),
    .ap_idle(proc_1_2_U0_ap_idle),
    .ap_ready(proc_1_2_U0_ap_ready),
    .B_din(proc_1_2_U0_B_din),
    .B_full_n(B_full_n),
    .B_write(proc_1_2_U0_B_write),
    .C_din(proc_1_2_U0_C_din),
    .C_full_n(C_full_n),
    .C_write(proc_1_2_U0_C_write),
    .data_channel1_dout(data_channel1_dout),
    .data_channel1_empty_n(data_channel1_empty_n),
    .data_channel1_read(proc_1_2_U0_data_channel1_read),
    .data_channel2_dout(data_channel2_dout),
    .data_channel2_empty_n(data_channel2_empty_n),
    .data_channel2_read(proc_1_2_U0_data_channel2_read)
);

example_fifo_w32_d10_S data_channel1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(proc_1_1_U0_data_channel1_din),
    .if_full_n(data_channel1_full_n),
    .if_write(proc_1_1_U0_data_channel1_write),
    .if_dout(data_channel1_dout),
    .if_empty_n(data_channel1_empty_n),
    .if_read(proc_1_2_U0_data_channel1_read)
);

example_fifo_w32_d1_S data_channel2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(proc_1_1_U0_data_channel2_din),
    .if_full_n(data_channel2_full_n),
    .if_write(proc_1_1_U0_data_channel2_write),
    .if_dout(data_channel2_dout),
    .if_empty_n(data_channel2_empty_n),
    .if_read(proc_1_2_U0_data_channel2_read)
);

example_start_for_proc_1_2_U0 start_for_proc_1_2_U0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_proc_1_2_U0_din),
    .if_full_n(start_for_proc_1_2_U0_full_n),
    .if_write(proc_1_1_U0_start_write),
    .if_dout(start_for_proc_1_2_U0_dout),
    .if_empty_n(start_for_proc_1_2_U0_empty_n),
    .if_read(proc_1_2_U0_ap_ready)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((real_start == 1'b1) & (internal_ap_ready == 1'b0))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (start_full_n == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (real_start == 1'b1))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

assign A_V_read = proc_1_1_U0_A_V_read;

assign B_din = proc_1_2_U0_B_din;

assign B_write = proc_1_2_U0_B_write;

assign C_din = proc_1_2_U0_C_din;

assign C_write = proc_1_2_U0_C_write;

assign ap_done = proc_1_2_U0_ap_done;

assign ap_idle = (proc_1_2_U0_ap_idle & proc_1_1_U0_ap_idle);

assign ap_ready = internal_ap_ready;

assign ap_sync_continue = ap_continue;

assign ap_sync_done = proc_1_2_U0_ap_done;

assign ap_sync_ready = proc_1_1_U0_ap_ready;

assign internal_ap_ready = ap_sync_ready;

assign proc_1_1_U0_ap_continue = 1'b1;

assign proc_1_1_U0_ap_start = real_start;

assign proc_1_2_U0_ap_continue = ap_continue;

assign proc_1_2_U0_ap_start = start_for_proc_1_2_U0_empty_n;

assign proc_1_2_U0_start_full_n = 1'b1;

assign proc_1_2_U0_start_write = 1'b0;

assign start_for_proc_1_2_U0_din = 1'b1;

assign start_out = real_start;

endmodule //example_proc_1
