// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2020.1
// Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module Loop_realfft_be_stre (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        real_spectrum_lo_V_M_real_V_dout,
        real_spectrum_lo_V_M_real_V_empty_n,
        real_spectrum_lo_V_M_real_V_read,
        real_spectrum_lo_V_M_imag_V_dout,
        real_spectrum_lo_V_M_imag_V_empty_n,
        real_spectrum_lo_V_M_imag_V_read,
        real_spectrum_hi_V_M_real_V_dout,
        real_spectrum_hi_V_M_real_V_empty_n,
        real_spectrum_hi_V_M_real_V_read,
        real_spectrum_hi_V_M_imag_V_dout,
        real_spectrum_hi_V_M_imag_V_empty_n,
        real_spectrum_hi_V_M_imag_V_read,
        dout_TREADY,
        dout_TDATA,
        dout_TVALID,
        dout_TLAST
);

parameter    ap_ST_fsm_state1 = 2'd1;
parameter    ap_ST_fsm_pp0_stage0 = 2'd2;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [15:0] real_spectrum_lo_V_M_real_V_dout;
input   real_spectrum_lo_V_M_real_V_empty_n;
output   real_spectrum_lo_V_M_real_V_read;
input  [15:0] real_spectrum_lo_V_M_imag_V_dout;
input   real_spectrum_lo_V_M_imag_V_empty_n;
output   real_spectrum_lo_V_M_imag_V_read;
input  [15:0] real_spectrum_hi_V_M_real_V_dout;
input   real_spectrum_hi_V_M_real_V_empty_n;
output   real_spectrum_hi_V_M_real_V_read;
input  [15:0] real_spectrum_hi_V_M_imag_V_dout;
input   real_spectrum_hi_V_M_imag_V_empty_n;
output   real_spectrum_hi_V_M_imag_V_read;
input   dout_TREADY;
output  [31:0] dout_TDATA;
output   dout_TVALID;
output  [0:0] dout_TLAST;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg real_spectrum_lo_V_M_real_V_read;
reg real_spectrum_lo_V_M_imag_V_read;
reg real_spectrum_hi_V_M_real_V_read;
reg real_spectrum_hi_V_M_imag_V_read;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [0:0] dout_val_last_V_fu_202_p2;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
wire    ap_block_state2_pp0_stage0_iter0;
wire    io_acc_block_signal_op28;
reg   [0:0] tmp_reg_239;
wire    io_acc_block_signal_op32;
reg    ap_block_state4_pp0_stage0_iter1;
reg    ap_enable_reg_pp0_iter1;
wire    regslice_both_dout_V_data_U_apdone_blk;
reg    ap_block_state3_pp0_stage0_iter2;
reg    ap_enable_reg_pp0_iter2;
reg    ap_block_pp0_stage0_11001;
reg    dout_TDATA_blk_n;
wire    ap_block_pp0_stage0;
reg    real_spectrum_lo_V_M_real_V_blk_n;
reg    real_spectrum_lo_V_M_imag_V_blk_n;
reg    real_spectrum_hi_V_M_real_V_blk_n;
reg    real_spectrum_hi_V_M_imag_V_blk_n;
reg   [8:0] i4_0_i1_reg_156;
wire   [8:0] i_fu_196_p2;
reg   [8:0] i_reg_243;
reg   [0:0] dout_val_last_V_reg_248;
reg   [0:0] dout_val_last_V_reg_248_pp0_iter1_reg;
reg    ap_block_state1;
reg    ap_block_pp0_stage0_subdone;
reg   [8:0] ap_phi_mux_i4_0_i1_phi_fu_160_p6;
reg   [15:0] ap_phi_mux_tmp_data_M_imag_V_phi_fu_173_p4;
wire   [15:0] ap_phi_reg_pp0_iter1_tmp_data_M_imag_V_reg_170;
reg   [15:0] ap_phi_mux_tmp_data_M_real_V_phi_fu_182_p4;
wire   [15:0] ap_phi_reg_pp0_iter1_tmp_data_M_real_V_reg_179;
reg    ap_block_pp0_stage0_01001;
reg   [1:0] ap_NS_fsm;
reg    ap_idle_pp0_0to1;
reg    ap_reset_idle_pp0;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
wire   [31:0] dout_TDATA_int;
reg    dout_TVALID_int;
wire    dout_TREADY_int;
wire    regslice_both_dout_V_data_U_vld_out;
wire    regslice_both_dout_V_last_V_U_apdone_blk;
wire    regslice_both_dout_V_last_V_U_ack_in_dummy;
wire    regslice_both_dout_V_last_V_U_vld_out;
reg    ap_condition_97;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 2'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
end

regslice_both #(
    .DataWidth( 32 ))
regslice_both_dout_V_data_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(dout_TDATA_int),
    .vld_in(dout_TVALID_int),
    .ack_in(dout_TREADY_int),
    .data_out(dout_TDATA),
    .vld_out(regslice_both_dout_V_data_U_vld_out),
    .ack_out(dout_TREADY),
    .apdone_blk(regslice_both_dout_V_data_U_apdone_blk)
);

regslice_both #(
    .DataWidth( 1 ))
regslice_both_dout_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(dout_val_last_V_reg_248),
    .vld_in(dout_TVALID_int),
    .ack_in(regslice_both_dout_V_last_V_U_ack_in_dummy),
    .data_out(dout_TLAST),
    .vld_out(regslice_both_dout_V_last_V_U_vld_out),
    .ack_out(dout_TREADY),
    .apdone_blk(regslice_both_dout_V_last_V_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_11001) & (dout_val_last_V_reg_248_pp0_iter1_reg == 1'd1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_enable_reg_pp0_iter1 <= ap_start;
        end else if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end else if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (dout_val_last_V_reg_248 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        i4_0_i1_reg_156 <= i_reg_243;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (dout_val_last_V_reg_248 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | (~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1)))) begin
        i4_0_i1_reg_156 <= 9'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        dout_val_last_V_reg_248 <= dout_val_last_V_fu_202_p2;
        dout_val_last_V_reg_248_pp0_iter1_reg <= dout_val_last_V_reg_248;
        tmp_reg_239 <= ap_phi_mux_i4_0_i1_phi_fu_160_p6[32'd8];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        i_reg_243 <= i_fu_196_p2;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (dout_val_last_V_reg_248_pp0_iter1_reg == 1'd1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0_0to1 = 1'b1;
    end else begin
        ap_idle_pp0_0to1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_97)) begin
        if ((dout_val_last_V_reg_248 == 1'd1)) begin
            ap_phi_mux_i4_0_i1_phi_fu_160_p6 = 9'd0;
        end else if ((dout_val_last_V_reg_248 == 1'd0)) begin
            ap_phi_mux_i4_0_i1_phi_fu_160_p6 = i_reg_243;
        end else begin
            ap_phi_mux_i4_0_i1_phi_fu_160_p6 = i4_0_i1_reg_156;
        end
    end else begin
        ap_phi_mux_i4_0_i1_phi_fu_160_p6 = i4_0_i1_reg_156;
    end
end

always @ (*) begin
    if ((tmp_reg_239 == 1'd1)) begin
        ap_phi_mux_tmp_data_M_imag_V_phi_fu_173_p4 = real_spectrum_hi_V_M_imag_V_dout;
    end else if ((tmp_reg_239 == 1'd0)) begin
        ap_phi_mux_tmp_data_M_imag_V_phi_fu_173_p4 = real_spectrum_lo_V_M_imag_V_dout;
    end else begin
        ap_phi_mux_tmp_data_M_imag_V_phi_fu_173_p4 = ap_phi_reg_pp0_iter1_tmp_data_M_imag_V_reg_170;
    end
end

always @ (*) begin
    if ((tmp_reg_239 == 1'd1)) begin
        ap_phi_mux_tmp_data_M_real_V_phi_fu_182_p4 = real_spectrum_hi_V_M_real_V_dout;
    end else if ((tmp_reg_239 == 1'd0)) begin
        ap_phi_mux_tmp_data_M_real_V_phi_fu_182_p4 = real_spectrum_lo_V_M_real_V_dout;
    end else begin
        ap_phi_mux_tmp_data_M_real_V_phi_fu_182_p4 = ap_phi_reg_pp0_iter1_tmp_data_M_real_V_reg_179;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (dout_val_last_V_fu_202_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0_0to1 == 1'b1))) begin
        ap_reset_idle_pp0 = 1'b1;
    end else begin
        ap_reset_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        dout_TDATA_blk_n = dout_TREADY_int;
    end else begin
        dout_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        dout_TVALID_int = 1'b1;
    end else begin
        dout_TVALID_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (tmp_reg_239 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        real_spectrum_hi_V_M_imag_V_blk_n = real_spectrum_hi_V_M_imag_V_empty_n;
    end else begin
        real_spectrum_hi_V_M_imag_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (tmp_reg_239 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        real_spectrum_hi_V_M_imag_V_read = 1'b1;
    end else begin
        real_spectrum_hi_V_M_imag_V_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (tmp_reg_239 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        real_spectrum_hi_V_M_real_V_blk_n = real_spectrum_hi_V_M_real_V_empty_n;
    end else begin
        real_spectrum_hi_V_M_real_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (tmp_reg_239 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        real_spectrum_hi_V_M_real_V_read = 1'b1;
    end else begin
        real_spectrum_hi_V_M_real_V_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (tmp_reg_239 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        real_spectrum_lo_V_M_imag_V_blk_n = real_spectrum_lo_V_M_imag_V_empty_n;
    end else begin
        real_spectrum_lo_V_M_imag_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (tmp_reg_239 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        real_spectrum_lo_V_M_imag_V_read = 1'b1;
    end else begin
        real_spectrum_lo_V_M_imag_V_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (tmp_reg_239 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        real_spectrum_lo_V_M_real_V_blk_n = real_spectrum_lo_V_M_real_V_empty_n;
    end else begin
        real_spectrum_lo_V_M_real_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (tmp_reg_239 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        real_spectrum_lo_V_M_real_V_read = 1'b1;
    end else begin
        real_spectrum_lo_V_M_real_V_read = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if ((ap_reset_idle_pp0 == 1'b0)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if (((ap_reset_idle_pp0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = ((ap_done_reg == 1'b1) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (regslice_both_dout_V_data_U_apdone_blk == 1'b1)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (((io_acc_block_signal_op32 == 1'b0) & (tmp_reg_239 == 1'd1)) | ((tmp_reg_239 == 1'd0) & (io_acc_block_signal_op28 == 1'b0)))));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_done_reg == 1'b1) | ((ap_enable_reg_pp0_iter2 == 1'b1) & ((dout_TREADY_int == 1'b0) | (regslice_both_dout_V_data_U_apdone_blk == 1'b1))) | ((ap_enable_reg_pp0_iter1 == 1'b1) & ((dout_TREADY_int == 1'b0) | ((io_acc_block_signal_op32 == 1'b0) & (tmp_reg_239 == 1'd1)) | ((tmp_reg_239 == 1'd0) & (io_acc_block_signal_op28 == 1'b0)))));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_done_reg == 1'b1) | ((ap_enable_reg_pp0_iter2 == 1'b1) & ((dout_TREADY_int == 1'b0) | (regslice_both_dout_V_data_U_apdone_blk == 1'b1))) | ((ap_enable_reg_pp0_iter1 == 1'b1) & ((dout_TREADY_int == 1'b0) | ((io_acc_block_signal_op32 == 1'b0) & (tmp_reg_239 == 1'd1)) | ((tmp_reg_239 == 1'd0) & (io_acc_block_signal_op28 == 1'b0)))));
end

always @ (*) begin
    ap_block_state1 = ((ap_start == 1'b0) | (ap_done_reg == 1'b1));
end

assign ap_block_state2_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state3_pp0_stage0_iter2 = (regslice_both_dout_V_data_U_apdone_blk == 1'b1);
end

always @ (*) begin
    ap_block_state4_pp0_stage0_iter1 = (((io_acc_block_signal_op32 == 1'b0) & (tmp_reg_239 == 1'd1)) | ((tmp_reg_239 == 1'd0) & (io_acc_block_signal_op28 == 1'b0)));
end

always @ (*) begin
    ap_condition_97 = ((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start;

assign ap_phi_reg_pp0_iter1_tmp_data_M_imag_V_reg_170 = 'bx;

assign ap_phi_reg_pp0_iter1_tmp_data_M_real_V_reg_179 = 'bx;

assign dout_TDATA_int = {{ap_phi_mux_tmp_data_M_imag_V_phi_fu_173_p4}, {ap_phi_mux_tmp_data_M_real_V_phi_fu_182_p4}};

assign dout_TVALID = regslice_both_dout_V_data_U_vld_out;

assign dout_val_last_V_fu_202_p2 = ((ap_phi_mux_i4_0_i1_phi_fu_160_p6 == 9'd511) ? 1'b1 : 1'b0);

assign i_fu_196_p2 = (ap_phi_mux_i4_0_i1_phi_fu_160_p6 + 9'd1);

assign io_acc_block_signal_op28 = (real_spectrum_lo_V_M_real_V_empty_n & real_spectrum_lo_V_M_imag_V_empty_n);

assign io_acc_block_signal_op32 = (real_spectrum_hi_V_M_real_V_empty_n & real_spectrum_hi_V_M_imag_V_empty_n);

endmodule //Loop_realfft_be_stre
