// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2020.1
// Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="hls_real2xfft,hls_ip_2020_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=1,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=4.000000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=3.890000,HLS_SYN_LAT=1032,HLS_SYN_TPT=1024,HLS_SYN_MEM=6,HLS_SYN_DSP=2,HLS_SYN_FF=648,HLS_SYN_LUT=1165,HLS_VERSION=2020_1}" *)

module hls_real2xfft (
        din_V_V_TDATA,
        dout_TDATA,
        dout_TLAST,
        ap_clk,
        ap_rst_n,
        din_V_V_TVALID,
        din_V_V_TREADY,
        ap_start,
        dout_TVALID,
        dout_TREADY,
        ap_done,
        ap_ready,
        ap_idle
);


input  [15:0] din_V_V_TDATA;
output  [31:0] dout_TDATA;
output  [0:0] dout_TLAST;
input   ap_clk;
input   ap_rst_n;
input   din_V_V_TVALID;
output   din_V_V_TREADY;
input   ap_start;
output   dout_TVALID;
input   dout_TREADY;
output   ap_done;
output   ap_ready;
output   ap_idle;

 reg    ap_rst_n_inv;
wire    Loop_sliding_win_del_U0_ap_start;
wire    Loop_sliding_win_del_U0_ap_done;
wire    Loop_sliding_win_del_U0_ap_continue;
wire    Loop_sliding_win_del_U0_ap_idle;
wire    Loop_sliding_win_del_U0_ap_ready;
wire   [15:0] Loop_sliding_win_del_U0_nodelay_i_0_din;
wire    Loop_sliding_win_del_U0_nodelay_i_0_write;
wire   [15:0] Loop_sliding_win_del_U0_nodelay_i_1_din;
wire    Loop_sliding_win_del_U0_nodelay_i_1_write;
wire   [15:0] Loop_sliding_win_del_U0_delayed_i_0_din;
wire    Loop_sliding_win_del_U0_delayed_i_0_write;
wire   [15:0] Loop_sliding_win_del_U0_delayed_i_1_din;
wire    Loop_sliding_win_del_U0_delayed_i_1_write;
wire    Loop_sliding_win_del_U0_start_out;
wire    Loop_sliding_win_del_U0_start_write;
wire    Loop_sliding_win_del_U0_din_V_V_TREADY;
wire    Loop_sliding_win_out_U0_ap_start;
wire    Loop_sliding_win_out_U0_ap_done;
wire    Loop_sliding_win_out_U0_ap_continue;
wire    Loop_sliding_win_out_U0_ap_idle;
wire    Loop_sliding_win_out_U0_ap_ready;
wire    Loop_sliding_win_out_U0_delayed_i_0_read;
wire    Loop_sliding_win_out_U0_nodelay_i_0_read;
wire    Loop_sliding_win_out_U0_delayed_i_1_read;
wire    Loop_sliding_win_out_U0_nodelay_i_1_read;
wire    Loop_sliding_win_out_U0_start_out;
wire    Loop_sliding_win_out_U0_start_write;
wire   [15:0] Loop_sliding_win_out_U0_data2window_1_din;
wire    Loop_sliding_win_out_U0_data2window_1_write;
wire   [15:0] Loop_sliding_win_out_U0_data2window_0_din;
wire    Loop_sliding_win_out_U0_data2window_0_write;
wire    window_fn_U0_ap_start;
wire    window_fn_U0_ap_done;
wire    window_fn_U0_ap_continue;
wire    window_fn_U0_ap_idle;
wire    window_fn_U0_ap_ready;
wire    window_fn_U0_indata_0_V_read;
wire    window_fn_U0_indata_1_V_read;
wire    window_fn_U0_start_out;
wire    window_fn_U0_start_write;
wire   [15:0] window_fn_U0_outdata_0_V_din;
wire    window_fn_U0_outdata_0_V_write;
wire   [15:0] window_fn_U0_outdata_1_V_din;
wire    window_fn_U0_outdata_1_V_write;
wire    Loop_real2xfft_outpu_U0_ap_start;
wire    Loop_real2xfft_outpu_U0_ap_done;
wire    Loop_real2xfft_outpu_U0_ap_continue;
wire    Loop_real2xfft_outpu_U0_ap_idle;
wire    Loop_real2xfft_outpu_U0_ap_ready;
wire    Loop_real2xfft_outpu_U0_windowed_0_read;
wire    Loop_real2xfft_outpu_U0_windowed_1_read;
wire   [31:0] Loop_real2xfft_outpu_U0_dout_TDATA;
wire    Loop_real2xfft_outpu_U0_dout_TVALID;
wire   [0:0] Loop_real2xfft_outpu_U0_dout_TLAST;
wire    ap_sync_continue;
wire    delayed_i_0_channel_full_n;
wire   [15:0] delayed_i_0_channel_dout;
wire    delayed_i_0_channel_empty_n;
wire    delayed_i_1_channel_full_n;
wire   [15:0] delayed_i_1_channel_dout;
wire    delayed_i_1_channel_empty_n;
wire    nodelay_i_0_channel_full_n;
wire   [15:0] nodelay_i_0_channel_dout;
wire    nodelay_i_0_channel_empty_n;
wire    nodelay_i_1_channel_full_n;
wire   [15:0] nodelay_i_1_channel_dout;
wire    nodelay_i_1_channel_empty_n;
wire    data2window_1_channe_full_n;
wire   [15:0] data2window_1_channe_dout;
wire    data2window_1_channe_empty_n;
wire    data2window_0_channe_full_n;
wire   [15:0] data2window_0_channe_dout;
wire    data2window_0_channe_empty_n;
wire    windowed_0_channel_full_n;
wire   [15:0] windowed_0_channel_dout;
wire    windowed_0_channel_empty_n;
wire    windowed_1_channel_full_n;
wire   [15:0] windowed_1_channel_dout;
wire    windowed_1_channel_empty_n;
wire    ap_sync_done;
wire    ap_sync_ready;
wire   [0:0] start_for_Loop_sliding_win_out_U0_din;
wire    start_for_Loop_sliding_win_out_U0_full_n;
wire   [0:0] start_for_Loop_sliding_win_out_U0_dout;
wire    start_for_Loop_sliding_win_out_U0_empty_n;
wire   [0:0] start_for_window_fn_U0_din;
wire    start_for_window_fn_U0_full_n;
wire   [0:0] start_for_window_fn_U0_dout;
wire    start_for_window_fn_U0_empty_n;
wire   [0:0] start_for_Loop_real2xfft_outpu_U0_din;
wire    start_for_Loop_real2xfft_outpu_U0_full_n;
wire   [0:0] start_for_Loop_real2xfft_outpu_U0_dout;
wire    start_for_Loop_real2xfft_outpu_U0_empty_n;
wire    Loop_real2xfft_outpu_U0_start_full_n;
wire    Loop_real2xfft_outpu_U0_start_write;

Loop_sliding_win_del Loop_sliding_win_del_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(Loop_sliding_win_del_U0_ap_start),
    .start_full_n(start_for_Loop_sliding_win_out_U0_full_n),
    .ap_done(Loop_sliding_win_del_U0_ap_done),
    .ap_continue(Loop_sliding_win_del_U0_ap_continue),
    .ap_idle(Loop_sliding_win_del_U0_ap_idle),
    .ap_ready(Loop_sliding_win_del_U0_ap_ready),
    .din_V_V_TVALID(din_V_V_TVALID),
    .nodelay_i_0_din(Loop_sliding_win_del_U0_nodelay_i_0_din),
    .nodelay_i_0_full_n(nodelay_i_0_channel_full_n),
    .nodelay_i_0_write(Loop_sliding_win_del_U0_nodelay_i_0_write),
    .nodelay_i_1_din(Loop_sliding_win_del_U0_nodelay_i_1_din),
    .nodelay_i_1_full_n(nodelay_i_1_channel_full_n),
    .nodelay_i_1_write(Loop_sliding_win_del_U0_nodelay_i_1_write),
    .delayed_i_0_din(Loop_sliding_win_del_U0_delayed_i_0_din),
    .delayed_i_0_full_n(delayed_i_0_channel_full_n),
    .delayed_i_0_write(Loop_sliding_win_del_U0_delayed_i_0_write),
    .delayed_i_1_din(Loop_sliding_win_del_U0_delayed_i_1_din),
    .delayed_i_1_full_n(delayed_i_1_channel_full_n),
    .delayed_i_1_write(Loop_sliding_win_del_U0_delayed_i_1_write),
    .start_out(Loop_sliding_win_del_U0_start_out),
    .start_write(Loop_sliding_win_del_U0_start_write),
    .din_V_V_TDATA(din_V_V_TDATA),
    .din_V_V_TREADY(Loop_sliding_win_del_U0_din_V_V_TREADY)
);

Loop_sliding_win_out Loop_sliding_win_out_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(Loop_sliding_win_out_U0_ap_start),
    .start_full_n(start_for_window_fn_U0_full_n),
    .ap_done(Loop_sliding_win_out_U0_ap_done),
    .ap_continue(Loop_sliding_win_out_U0_ap_continue),
    .ap_idle(Loop_sliding_win_out_U0_ap_idle),
    .ap_ready(Loop_sliding_win_out_U0_ap_ready),
    .delayed_i_0_dout(delayed_i_0_channel_dout),
    .delayed_i_0_empty_n(delayed_i_0_channel_empty_n),
    .delayed_i_0_read(Loop_sliding_win_out_U0_delayed_i_0_read),
    .nodelay_i_0_dout(nodelay_i_0_channel_dout),
    .nodelay_i_0_empty_n(nodelay_i_0_channel_empty_n),
    .nodelay_i_0_read(Loop_sliding_win_out_U0_nodelay_i_0_read),
    .delayed_i_1_dout(delayed_i_1_channel_dout),
    .delayed_i_1_empty_n(delayed_i_1_channel_empty_n),
    .delayed_i_1_read(Loop_sliding_win_out_U0_delayed_i_1_read),
    .nodelay_i_1_dout(nodelay_i_1_channel_dout),
    .nodelay_i_1_empty_n(nodelay_i_1_channel_empty_n),
    .nodelay_i_1_read(Loop_sliding_win_out_U0_nodelay_i_1_read),
    .start_out(Loop_sliding_win_out_U0_start_out),
    .start_write(Loop_sliding_win_out_U0_start_write),
    .data2window_1_din(Loop_sliding_win_out_U0_data2window_1_din),
    .data2window_1_full_n(data2window_1_channe_full_n),
    .data2window_1_write(Loop_sliding_win_out_U0_data2window_1_write),
    .data2window_0_din(Loop_sliding_win_out_U0_data2window_0_din),
    .data2window_0_full_n(data2window_0_channe_full_n),
    .data2window_0_write(Loop_sliding_win_out_U0_data2window_0_write)
);

window_fn window_fn_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(window_fn_U0_ap_start),
    .start_full_n(start_for_Loop_real2xfft_outpu_U0_full_n),
    .ap_done(window_fn_U0_ap_done),
    .ap_continue(window_fn_U0_ap_continue),
    .ap_idle(window_fn_U0_ap_idle),
    .ap_ready(window_fn_U0_ap_ready),
    .indata_0_V_dout(data2window_0_channe_dout),
    .indata_0_V_empty_n(data2window_0_channe_empty_n),
    .indata_0_V_read(window_fn_U0_indata_0_V_read),
    .indata_1_V_dout(data2window_1_channe_dout),
    .indata_1_V_empty_n(data2window_1_channe_empty_n),
    .indata_1_V_read(window_fn_U0_indata_1_V_read),
    .start_out(window_fn_U0_start_out),
    .start_write(window_fn_U0_start_write),
    .outdata_0_V_din(window_fn_U0_outdata_0_V_din),
    .outdata_0_V_full_n(windowed_0_channel_full_n),
    .outdata_0_V_write(window_fn_U0_outdata_0_V_write),
    .outdata_1_V_din(window_fn_U0_outdata_1_V_din),
    .outdata_1_V_full_n(windowed_1_channel_full_n),
    .outdata_1_V_write(window_fn_U0_outdata_1_V_write)
);

Loop_real2xfft_outpu Loop_real2xfft_outpu_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(Loop_real2xfft_outpu_U0_ap_start),
    .ap_done(Loop_real2xfft_outpu_U0_ap_done),
    .ap_continue(Loop_real2xfft_outpu_U0_ap_continue),
    .ap_idle(Loop_real2xfft_outpu_U0_ap_idle),
    .ap_ready(Loop_real2xfft_outpu_U0_ap_ready),
    .windowed_0_dout(windowed_0_channel_dout),
    .windowed_0_empty_n(windowed_0_channel_empty_n),
    .windowed_0_read(Loop_real2xfft_outpu_U0_windowed_0_read),
    .windowed_1_dout(windowed_1_channel_dout),
    .windowed_1_empty_n(windowed_1_channel_empty_n),
    .windowed_1_read(Loop_real2xfft_outpu_U0_windowed_1_read),
    .dout_TREADY(dout_TREADY),
    .dout_TDATA(Loop_real2xfft_outpu_U0_dout_TDATA),
    .dout_TVALID(Loop_real2xfft_outpu_U0_dout_TVALID),
    .dout_TLAST(Loop_real2xfft_outpu_U0_dout_TLAST)
);

fifo_w16_d256_A delayed_i_0_channel_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Loop_sliding_win_del_U0_delayed_i_0_din),
    .if_full_n(delayed_i_0_channel_full_n),
    .if_write(Loop_sliding_win_del_U0_delayed_i_0_write),
    .if_dout(delayed_i_0_channel_dout),
    .if_empty_n(delayed_i_0_channel_empty_n),
    .if_read(Loop_sliding_win_out_U0_delayed_i_0_read)
);

fifo_w16_d256_A delayed_i_1_channel_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Loop_sliding_win_del_U0_delayed_i_1_din),
    .if_full_n(delayed_i_1_channel_full_n),
    .if_write(Loop_sliding_win_del_U0_delayed_i_1_write),
    .if_dout(delayed_i_1_channel_dout),
    .if_empty_n(delayed_i_1_channel_empty_n),
    .if_read(Loop_sliding_win_out_U0_delayed_i_1_read)
);

fifo_w16_d512_A nodelay_i_0_channel_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Loop_sliding_win_del_U0_nodelay_i_0_din),
    .if_full_n(nodelay_i_0_channel_full_n),
    .if_write(Loop_sliding_win_del_U0_nodelay_i_0_write),
    .if_dout(nodelay_i_0_channel_dout),
    .if_empty_n(nodelay_i_0_channel_empty_n),
    .if_read(Loop_sliding_win_out_U0_nodelay_i_0_read)
);

fifo_w16_d512_A nodelay_i_1_channel_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Loop_sliding_win_del_U0_nodelay_i_1_din),
    .if_full_n(nodelay_i_1_channel_full_n),
    .if_write(Loop_sliding_win_del_U0_nodelay_i_1_write),
    .if_dout(nodelay_i_1_channel_dout),
    .if_empty_n(nodelay_i_1_channel_empty_n),
    .if_read(Loop_sliding_win_out_U0_nodelay_i_1_read)
);

fifo_w16_d2_A data2window_1_channe_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Loop_sliding_win_out_U0_data2window_1_din),
    .if_full_n(data2window_1_channe_full_n),
    .if_write(Loop_sliding_win_out_U0_data2window_1_write),
    .if_dout(data2window_1_channe_dout),
    .if_empty_n(data2window_1_channe_empty_n),
    .if_read(window_fn_U0_indata_1_V_read)
);

fifo_w16_d2_A data2window_0_channe_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Loop_sliding_win_out_U0_data2window_0_din),
    .if_full_n(data2window_0_channe_full_n),
    .if_write(Loop_sliding_win_out_U0_data2window_0_write),
    .if_dout(data2window_0_channe_dout),
    .if_empty_n(data2window_0_channe_empty_n),
    .if_read(window_fn_U0_indata_0_V_read)
);

fifo_w16_d2_A windowed_0_channel_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(window_fn_U0_outdata_0_V_din),
    .if_full_n(windowed_0_channel_full_n),
    .if_write(window_fn_U0_outdata_0_V_write),
    .if_dout(windowed_0_channel_dout),
    .if_empty_n(windowed_0_channel_empty_n),
    .if_read(Loop_real2xfft_outpu_U0_windowed_0_read)
);

fifo_w16_d2_A windowed_1_channel_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(window_fn_U0_outdata_1_V_din),
    .if_full_n(windowed_1_channel_full_n),
    .if_write(window_fn_U0_outdata_1_V_write),
    .if_dout(windowed_1_channel_dout),
    .if_empty_n(windowed_1_channel_empty_n),
    .if_read(Loop_real2xfft_outpu_U0_windowed_1_read)
);

start_for_Loop_slfYi start_for_Loop_slfYi_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_Loop_sliding_win_out_U0_din),
    .if_full_n(start_for_Loop_sliding_win_out_U0_full_n),
    .if_write(Loop_sliding_win_del_U0_start_write),
    .if_dout(start_for_Loop_sliding_win_out_U0_dout),
    .if_empty_n(start_for_Loop_sliding_win_out_U0_empty_n),
    .if_read(Loop_sliding_win_out_U0_ap_ready)
);

start_for_window_g8j start_for_window_g8j_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_window_fn_U0_din),
    .if_full_n(start_for_window_fn_U0_full_n),
    .if_write(Loop_sliding_win_out_U0_start_write),
    .if_dout(start_for_window_fn_U0_dout),
    .if_empty_n(start_for_window_fn_U0_empty_n),
    .if_read(window_fn_U0_ap_ready)
);

start_for_Loop_rehbi start_for_Loop_rehbi_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_Loop_real2xfft_outpu_U0_din),
    .if_full_n(start_for_Loop_real2xfft_outpu_U0_full_n),
    .if_write(window_fn_U0_start_write),
    .if_dout(start_for_Loop_real2xfft_outpu_U0_dout),
    .if_empty_n(start_for_Loop_real2xfft_outpu_U0_empty_n),
    .if_read(Loop_real2xfft_outpu_U0_ap_ready)
);

assign Loop_real2xfft_outpu_U0_ap_continue = 1'b1;

assign Loop_real2xfft_outpu_U0_ap_start = start_for_Loop_real2xfft_outpu_U0_empty_n;

assign Loop_real2xfft_outpu_U0_start_full_n = 1'b1;

assign Loop_real2xfft_outpu_U0_start_write = 1'b0;

assign Loop_sliding_win_del_U0_ap_continue = 1'b1;

assign Loop_sliding_win_del_U0_ap_start = ap_start;

assign Loop_sliding_win_out_U0_ap_continue = 1'b1;

assign Loop_sliding_win_out_U0_ap_start = start_for_Loop_sliding_win_out_U0_empty_n;

assign ap_done = Loop_real2xfft_outpu_U0_ap_done;

assign ap_idle = (window_fn_U0_ap_idle & Loop_sliding_win_out_U0_ap_idle & Loop_sliding_win_del_U0_ap_idle & Loop_real2xfft_outpu_U0_ap_idle);

assign ap_ready = Loop_sliding_win_del_U0_ap_ready;

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign ap_sync_continue = 1'b1;

assign ap_sync_done = Loop_real2xfft_outpu_U0_ap_done;

assign ap_sync_ready = Loop_sliding_win_del_U0_ap_ready;

assign din_V_V_TREADY = Loop_sliding_win_del_U0_din_V_V_TREADY;

assign dout_TDATA = Loop_real2xfft_outpu_U0_dout_TDATA;

assign dout_TLAST = Loop_real2xfft_outpu_U0_dout_TLAST;

assign dout_TVALID = Loop_real2xfft_outpu_U0_dout_TVALID;

assign start_for_Loop_real2xfft_outpu_U0_din = 1'b1;

assign start_for_Loop_sliding_win_out_U0_din = 1'b1;

assign start_for_window_fn_U0_din = 1'b1;

assign window_fn_U0_ap_continue = 1'b1;

assign window_fn_U0_ap_start = start_for_window_fn_U0_empty_n;

endmodule //hls_real2xfft
