#!/bin/bash
# software emulation
make all TARGET=sw_emu DEVICE=xilinx_u50_gen3x16_xdma_201920_3 HOST_ARCH=x86
mkdir -p build_dir.sw_emu.xilinx_u50_gen3x16_xdma_201920_3
g++ -o build_dir.sw_emu.xilinx_u50_gen3x16_xdma_201920_3/host.exe /mnt/HLSNAS/richard/blas/L2/src/sw/main.cpp /mnt/HLSNAS/richard/blas/L2/src/sw/xcl2/xcl2.cpp -I/mnt/HLSNAS/richard/blas/L1/include/hw/xf_blas/helpers/utils -I/mnt/HLSNAS/richard/blas/L2/include/ -I/mnt/HLSNAS/richard/blas/L2/include/sw -I/mnt/HLSNAS/richard/blas/L2/include/sw/xcl2 -I/mnt/HLSNAS/richard/blas/L1/include/hw -D SW_EMU_TEST -I/opt/xilinx/xrt/include -I/opt/Xilinx/Vivado/2020.2/include -std=c++11 -O3 -Wall -Wno-unknown-pragmas -Wno-unused-label -fmessage-length=0 -O3 -I/mnt/HLSNAS/richard/blas/L2/tests/gemm_1CU/src/  -D TEST_MEMCPY=0 -D BLAS_instructionSizeBytes=64 -D BLAS_dataType=float  -D BLAS_dataEqIntType=float -D BLAS_ddrWidth=16  -D BLAS_argInstrWidth=1 -D BLAS_numInstr=64 -D BLAS_argPipeline=2 -D BLAS_runTransp=0 -D BLAS_runGemv=0 -D BLAS_runGemm=1 -D BLAS_runFcn=0 -D BLAS_numKernels=1 -D BLAS_CACHE=0 -D BLAS_XVEC=0 -D BLAS_gemmMBlocks=4 -D BLAS_gemmKBlocks=4  -D BLAS_gemmNBlocks=4  -D BLAS_XdataType=float  -D BLAS_XddrWidth=16  -D AP_INT_MAX_W=1026 -L/opt/xilinx/xrt/lib -lOpenCL -lpthread -lrt -Wno-unused-label -Wno-narrowing -DVERBOSE -L/opt/Xilinx/Vivado/2020.2/lnx64/tools/fpo_v7_0 -Wl,--as-needed -lgmp -lmpfr -lIp_floating_point_v7_0_bitacc_cmodel
echo "Compiling Kernel: blasKernel"
mkdir -p _x_temp.sw_emu.xilinx_u50_gen3x16_xdma_201920_3
v++ -c --hls.clock 300000000:blasKernel -t sw_emu --platform /opt/xilinx/platforms/xilinx_u50_gen3x16_xdma_201920_3/xilinx_u50_gen3x16_xdma_201920_3.xpfm --save-temps --optimize 2 --hls.jobs 8 --config /mnt/HLSNAS/richard/blas/L2/tests/gemm_1CU/conn_u50.cfg -I/mnt/HLSNAS/richard/blas/L1/include/hw -I/mnt/HLSNAS/richard/blas/L1/include/hw -I/mnt/HLSNAS/richard/blas/L1/include/hw/xf_blas -I/mnt/HLSNAS/richard/blas/L1/include/hw/xf_blas/gemm -I/mnt/HLSNAS/richard/blas/L1/include/hw/xf_blas/helpers/utils -I/mnt/HLSNAS/richard/blas/L2/include -I/mnt/HLSNAS/richard/blas/L2/include/hw/xf_blas -D TEST_MEMCPY=0 -D BLAS_instructionSizeBytes=64 -D BLAS_dataType=float  -D BLAS_dataEqIntType=float -D BLAS_ddrWidth=16  -D BLAS_argInstrWidth=1 -D BLAS_numInstr=64 -D BLAS_argPipeline=2 -D BLAS_runTransp=0 -D BLAS_runGemv=0 -D BLAS_runGemm=1 -D BLAS_runFcn=0 -D BLAS_numKernels=1 -D BLAS_CACHE=0 -D BLAS_XVEC=0 -D BLAS_gemmMBlocks=4 -D BLAS_gemmKBlocks=4  -D BLAS_gemmNBlocks=4  -D BLAS_XdataType=float  -D BLAS_XddrWidth=16  -D AP_INT_MAX_W=1026 -k blasKernel -I'/mnt/HLSNAS/richard/blas/L2/src/hw' --temp_dir _x_temp.sw_emu.xilinx_u50_gen3x16_xdma_201920_3 --report_dir /mnt/HLSNAS/richard/blas/L2/tests/gemm_1CU/reports/_x.sw_emu.xilinx_u50_gen3x16_xdma_201920_3 -o'_x_temp.sw_emu.xilinx_u50_gen3x16_xdma_201920_3/blasKernel.xo' '/mnt/HLSNAS/richard/blas/L2/src/hw/kernel.cpp'
mkdir -p build_dir.sw_emu.xilinx_u50_gen3x16_xdma_201920_3
v++ -l -t sw_emu --platform /opt/xilinx/platforms/xilinx_u50_gen3x16_xdma_201920_3/xilinx_u50_gen3x16_xdma_201920_3.xpfm --save-temps --optimize 2 --hls.jobs 8 --config /mnt/HLSNAS/richard/blas/L2/tests/gemm_1CU/conn_u50.cfg -I/mnt/HLSNAS/richard/blas/L1/include/hw -I/mnt/HLSNAS/richard/blas/L1/include/hw -I/mnt/HLSNAS/richard/blas/L1/include/hw/xf_blas -I/mnt/HLSNAS/richard/blas/L1/include/hw/xf_blas/gemm -I/mnt/HLSNAS/richard/blas/L1/include/hw/xf_blas/helpers/utils -I/mnt/HLSNAS/richard/blas/L2/include -I/mnt/HLSNAS/richard/blas/L2/include/hw/xf_blas -D TEST_MEMCPY=0 -D BLAS_instructionSizeBytes=64 -D BLAS_dataType=float  -D BLAS_dataEqIntType=float -D BLAS_ddrWidth=16  -D BLAS_argInstrWidth=1 -D BLAS_numInstr=64 -D BLAS_argPipeline=2 -D BLAS_runTransp=0 -D BLAS_runGemv=0 -D BLAS_runGemm=1 -D BLAS_runFcn=0 -D BLAS_numKernels=1 -D BLAS_CACHE=0 -D BLAS_XVEC=0 -D BLAS_gemmMBlocks=4 -D BLAS_gemmKBlocks=4  -D BLAS_gemmNBlocks=4  -D BLAS_XdataType=float  -D BLAS_XddrWidth=16  -D AP_INT_MAX_W=1026 --temp_dir build_dir.sw_emu.xilinx_u50_gen3x16_xdma_201920_3 --report_dir /mnt/HLSNAS/richard/blas/L2/tests/gemm_1CU/reports/_build.sw_emu.xilinx_u50_gen3x16_xdma_201920_3/blas --vivado.synth.jobs 8 --vivado.impl.jobs 8 --kernel_frequency 300 --config opts.cfg -o 'build_dir.sw_emu.xilinx_u50_gen3x16_xdma_201920_3/blas.xclbin' _x_temp.sw_emu.xilinx_u50_gen3x16_xdma_201920_3/blasKernel.xo
emconfigutil --platform /opt/xilinx/platforms/xilinx_u50_gen3x16_xdma_201920_3/xilinx_u50_gen3x16_xdma_201920_3.xpfm --od build_dir.sw_emu.xilinx_u50_gen3x16_xdma_201920_3
XCL_EMULATION_MODE=sw_emu make data_gen TARGET=sw_emu DEVICE=xilinx_u50_gen3x16_xdma_201920_3 HOST_ARCH=x86
cp -rf build_dir.sw_emu.xilinx_u50_gen3x16_xdma_201920_3/emconfig.json .
XCL_EMULATION_MODE=sw_emu build_dir.sw_emu.xilinx_u50_gen3x16_xdma_201920_3/host.exe build_dir.sw_emu.xilinx_u50_gen3x16_xdma_201920_3/blas.xclbin build_dir.sw_emu.xilinx_u50_gen3x16_xdma_201920_3/data
make check TARGET=sw_emu DEVICE=xilinx_u50_gen3x16_xdma_201920_3 HOST_ARCH=x86

# hardware emulation
make all TARGET=hw_emu DEVICE=xilinx_u50_gen3x16_xdma_201920_3 HOST_ARCH=x86
mkdir -p build_dir.hw_emu.xilinx_u50_gen3x16_xdma_201920_3
g++ -o build_dir.hw_emu.xilinx_u50_gen3x16_xdma_201920_3/host.exe /mnt/HLSNAS/richard/blas/L2/src/sw/main.cpp /mnt/HLSNAS/richard/blas/L2/src/sw/xcl2/xcl2.cpp -I/mnt/HLSNAS/richard/blas/L1/include/hw/xf_blas/helpers/utils -I/mnt/HLSNAS/richard/blas/L2/include/ -I/mnt/HLSNAS/richard/blas/L2/include/sw -I/mnt/HLSNAS/richard/blas/L2/include/sw/xcl2 -I/mnt/HLSNAS/richard/blas/L1/include/hw -D HW_EMU_TEST -I/opt/xilinx/xrt/include -I/opt/Xilinx/Vivado/2020.2/include -std=c++11 -O3 -Wall -Wno-unknown-pragmas -Wno-unused-label -fmessage-length=0 -O3 -I/mnt/HLSNAS/richard/blas/L2/tests/gemm_1CU/src/  -D TEST_MEMCPY=0 -D BLAS_instructionSizeBytes=64 -D BLAS_dataType=float  -D BLAS_dataEqIntType=float -D BLAS_ddrWidth=16  -D BLAS_argInstrWidth=1 -D BLAS_numInstr=64 -D BLAS_argPipeline=2 -D BLAS_runTransp=0 -D BLAS_runGemv=0 -D BLAS_runGemm=1 -D BLAS_runFcn=0 -D BLAS_numKernels=1 -D BLAS_CACHE=0 -D BLAS_XVEC=0 -D BLAS_gemmMBlocks=4 -D BLAS_gemmKBlocks=4  -D BLAS_gemmNBlocks=4  -D BLAS_XdataType=float  -D BLAS_XddrWidth=16  -D AP_INT_MAX_W=1026 -L/opt/xilinx/xrt/lib -lOpenCL -lpthread -lrt -Wno-unused-label -Wno-narrowing -DVERBOSE -L/opt/Xilinx/Vivado/2020.2/lnx64/tools/fpo_v7_0 -Wl,--as-needed -lgmp -lmpfr -lIp_floating_point_v7_0_bitacc_cmodel
echo "Compiling Kernel: blasKernel"
mkdir -p _x_temp.hw_emu.xilinx_u50_gen3x16_xdma_201920_3
v++ -c --hls.clock 300000000:blasKernel -t hw_emu --platform /opt/xilinx/platforms/xilinx_u50_gen3x16_xdma_201920_3/xilinx_u50_gen3x16_xdma_201920_3.xpfm --save-temps --optimize 2 --hls.jobs 8 --config /mnt/HLSNAS/richard/blas/L2/tests/gemm_1CU/conn_u50.cfg -I/mnt/HLSNAS/richard/blas/L1/include/hw -I/mnt/HLSNAS/richard/blas/L1/include/hw -I/mnt/HLSNAS/richard/blas/L1/include/hw/xf_blas -I/mnt/HLSNAS/richard/blas/L1/include/hw/xf_blas/gemm -I/mnt/HLSNAS/richard/blas/L1/include/hw/xf_blas/helpers/utils -I/mnt/HLSNAS/richard/blas/L2/include -I/mnt/HLSNAS/richard/blas/L2/include/hw/xf_blas -D TEST_MEMCPY=0 -D BLAS_instructionSizeBytes=64 -D BLAS_dataType=float  -D BLAS_dataEqIntType=float -D BLAS_ddrWidth=16  -D BLAS_argInstrWidth=1 -D BLAS_numInstr=64 -D BLAS_argPipeline=2 -D BLAS_runTransp=0 -D BLAS_runGemv=0 -D BLAS_runGemm=1 -D BLAS_runFcn=0 -D BLAS_numKernels=1 -D BLAS_CACHE=0 -D BLAS_XVEC=0 -D BLAS_gemmMBlocks=4 -D BLAS_gemmKBlocks=4  -D BLAS_gemmNBlocks=4  -D BLAS_XdataType=float  -D BLAS_XddrWidth=16  -D AP_INT_MAX_W=1026 -k blasKernel -I'/mnt/HLSNAS/richard/blas/L2/src/hw' --temp_dir _x_temp.hw_emu.xilinx_u50_gen3x16_xdma_201920_3 --report_dir /mnt/HLSNAS/richard/blas/L2/tests/gemm_1CU/reports/_x.hw_emu.xilinx_u50_gen3x16_xdma_201920_3 -o'_x_temp.hw_emu.xilinx_u50_gen3x16_xdma_201920_3/blasKernel.xo' '/mnt/HLSNAS/richard/blas/L2/src/hw/kernel.cpp'
mkdir -p build_dir.hw_emu.xilinx_u50_gen3x16_xdma_201920_3
v++ -l -t hw_emu --platform /opt/xilinx/platforms/xilinx_u50_gen3x16_xdma_201920_3/xilinx_u50_gen3x16_xdma_201920_3.xpfm --save-temps --optimize 2 --hls.jobs 8 --config /mnt/HLSNAS/richard/blas/L2/tests/gemm_1CU/conn_u50.cfg -I/mnt/HLSNAS/richard/blas/L1/include/hw -I/mnt/HLSNAS/richard/blas/L1/include/hw -I/mnt/HLSNAS/richard/blas/L1/include/hw/xf_blas -I/mnt/HLSNAS/richard/blas/L1/include/hw/xf_blas/gemm -I/mnt/HLSNAS/richard/blas/L1/include/hw/xf_blas/helpers/utils -I/mnt/HLSNAS/richard/blas/L2/include -I/mnt/HLSNAS/richard/blas/L2/include/hw/xf_blas -D TEST_MEMCPY=0 -D BLAS_instructionSizeBytes=64 -D BLAS_dataType=float  -D BLAS_dataEqIntType=float -D BLAS_ddrWidth=16  -D BLAS_argInstrWidth=1 -D BLAS_numInstr=64 -D BLAS_argPipeline=2 -D BLAS_runTransp=0 -D BLAS_runGemv=0 -D BLAS_runGemm=1 -D BLAS_runFcn=0 -D BLAS_numKernels=1 -D BLAS_CACHE=0 -D BLAS_XVEC=0 -D BLAS_gemmMBlocks=4 -D BLAS_gemmKBlocks=4  -D BLAS_gemmNBlocks=4  -D BLAS_XdataType=float  -D BLAS_XddrWidth=16  -D AP_INT_MAX_W=1026 --temp_dir build_dir.hw_emu.xilinx_u50_gen3x16_xdma_201920_3 --report_dir /mnt/HLSNAS/richard/blas/L2/tests/gemm_1CU/reports/_build.hw_emu.xilinx_u50_gen3x16_xdma_201920_3/blas --vivado.synth.jobs 8 --vivado.impl.jobs 8 --kernel_frequency 300 --config opts.cfg -o 'build_dir.hw_emu.xilinx_u50_gen3x16_xdma_201920_3/blas.xclbin' _x_temp.hw_emu.xilinx_u50_gen3x16_xdma_201920_3/blasKernel.xo
emconfigutil --platform /opt/xilinx/platforms/xilinx_u50_gen3x16_xdma_201920_3/xilinx_u50_gen3x16_xdma_201920_3.xpfm --od build_dir.hw_emu.xilinx_u50_gen3x16_xdma_201920_3
XCL_EMULATION_MODE=hw_emu make data_gen TARGET=hw_emu DEVICE=xilinx_u50_gen3x16_xdma_201920_3 HOST_ARCH=x86
cp -rf build_dir.hw_emu.xilinx_u50_gen3x16_xdma_201920_3/emconfig.json .
XCL_EMULATION_MODE=hw_emu build_dir.hw_emu.xilinx_u50_gen3x16_xdma_201920_3/host.exe build_dir.hw_emu.xilinx_u50_gen3x16_xdma_201920_3/blas.xclbin build_dir.hw_emu.xilinx_u50_gen3x16_xdma_201920_3/data
make check TARGET=hw_emu DEVICE=xilinx_u50_gen3x16_xdma_201920_3 HOST_ARCH=x86

# hardware
make all TARGET=hw DEVICE=xilinx_u50_gen3x16_xdma_201920_3 HOST_ARCH=x86
echo "Compiling Kernel: blasKernel"
mkdir -p _x_temp.hw.xilinx_u50_gen3x16_xdma_201920_3
v++ -c --hls.clock 300000000:blasKernel -t hw --platform /opt/xilinx/platforms/xilinx_u50_gen3x16_xdma_201920_3/xilinx_u50_gen3x16_xdma_201920_3.xpfm --save-temps --optimize 2 --hls.jobs 8 --config /mnt/HLSNAS/richard/blas/L2/tests/gemm_1CU/conn_u50.cfg -I/mnt/HLSNAS/richard/blas/L1/include/hw -I/mnt/HLSNAS/richard/blas/L1/include/hw -I/mnt/HLSNAS/richard/blas/L1/include/hw/xf_blas -I/mnt/HLSNAS/richard/blas/L1/include/hw/xf_blas/gemm -I/mnt/HLSNAS/richard/blas/L1/include/hw/xf_blas/helpers/utils -I/mnt/HLSNAS/richard/blas/L2/include -I/mnt/HLSNAS/richard/blas/L2/include/hw/xf_blas -D TEST_MEMCPY=0 -D BLAS_instructionSizeBytes=64 -D BLAS_dataType=float  -D BLAS_dataEqIntType=float -D BLAS_ddrWidth=16  -D BLAS_argInstrWidth=1 -D BLAS_numInstr=64 -D BLAS_argPipeline=2 -D BLAS_runTransp=0 -D BLAS_runGemv=0 -D BLAS_runGemm=1 -D BLAS_runFcn=0 -D BLAS_numKernels=1 -D BLAS_CACHE=0 -D BLAS_XVEC=0 -D BLAS_gemmMBlocks=4 -D BLAS_gemmKBlocks=4  -D BLAS_gemmNBlocks=4  -D BLAS_XdataType=float  -D BLAS_XddrWidth=16  -D AP_INT_MAX_W=1026 -k blasKernel -I'/mnt/HLSNAS/richard/blas/L2/src/hw' --temp_dir _x_temp.hw.xilinx_u50_gen3x16_xdma_201920_3 --report_dir /mnt/HLSNAS/richard/blas/L2/tests/gemm_1CU/reports/_x.hw.xilinx_u50_gen3x16_xdma_201920_3 -o'_x_temp.hw.xilinx_u50_gen3x16_xdma_201920_3/blasKernel.xo' '/mnt/HLSNAS/richard/blas/L2/src/hw/kernel.cpp'
mkdir -p build_dir.hw.xilinx_u50_gen3x16_xdma_201920_3
v++ -l -t hw --platform /opt/xilinx/platforms/xilinx_u50_gen3x16_xdma_201920_3/xilinx_u50_gen3x16_xdma_201920_3.xpfm --save-temps --optimize 2 --hls.jobs 8 --config /mnt/HLSNAS/richard/blas/L2/tests/gemm_1CU/conn_u50.cfg -I/mnt/HLSNAS/richard/blas/L1/include/hw -I/mnt/HLSNAS/richard/blas/L1/include/hw -I/mnt/HLSNAS/richard/blas/L1/include/hw/xf_blas -I/mnt/HLSNAS/richard/blas/L1/include/hw/xf_blas/gemm -I/mnt/HLSNAS/richard/blas/L1/include/hw/xf_blas/helpers/utils -I/mnt/HLSNAS/richard/blas/L2/include -I/mnt/HLSNAS/richard/blas/L2/include/hw/xf_blas -D TEST_MEMCPY=0 -D BLAS_instructionSizeBytes=64 -D BLAS_dataType=float  -D BLAS_dataEqIntType=float -D BLAS_ddrWidth=16  -D BLAS_argInstrWidth=1 -D BLAS_numInstr=64 -D BLAS_argPipeline=2 -D BLAS_runTransp=0 -D BLAS_runGemv=0 -D BLAS_runGemm=1 -D BLAS_runFcn=0 -D BLAS_numKernels=1 -D BLAS_CACHE=0 -D BLAS_XVEC=0 -D BLAS_gemmMBlocks=4 -D BLAS_gemmKBlocks=4  -D BLAS_gemmNBlocks=4  -D BLAS_XdataType=float  -D BLAS_XddrWidth=16  -D AP_INT_MAX_W=1026 --temp_dir build_dir.hw.xilinx_u50_gen3x16_xdma_201920_3 --report_dir /mnt/HLSNAS/richard/blas/L2/tests/gemm_1CU/reports/_build.hw.xilinx_u50_gen3x16_xdma_201920_3/blas --vivado.synth.jobs 8 --vivado.impl.jobs 8 --kernel_frequency 300 --config opts.cfg -o 'build_dir.hw.xilinx_u50_gen3x16_xdma_201920_3/blas.xclbin' _x_temp.hw.xilinx_u50_gen3x16_xdma_201920_3/blasKernel.xo
emconfigutil --platform /opt/xilinx/platforms/xilinx_u50_gen3x16_xdma_201920_3/xilinx_u50_gen3x16_xdma_201920_3.xpfm --od build_dir.hw.xilinx_u50_gen3x16_xdma_201920_3
XCL_EMULATION_MODE=hw make data_gen TARGET=hw DEVICE=xilinx_u50_gen3x16_xdma_201920_3 HOST_ARCH=x86
build_dir.hw.xilinx_u50_gen3x16_xdma_201920_3/host.exe build_dir.hw.xilinx_u50_gen3x16_xdma_201920_3/blas.xclbin build_dir.hw.xilinx_u50_gen3x16_xdma_201920_3/data
