# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/Zynq_RealFFT/Zynq_RealFFT.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Zynq_RealFFT || ORIG_REF_NAME==Zynq_RealFFT} -quiet] -quiet

# IP: bd/Zynq_RealFFT/ip/Zynq_RealFFT_xfft_0_0/Zynq_RealFFT_xfft_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Zynq_RealFFT_xfft_0_0 || ORIG_REF_NAME==Zynq_RealFFT_xfft_0_0} -quiet] -quiet

# IP: bd/Zynq_RealFFT/ip/Zynq_RealFFT_xlconstant_0_0/Zynq_RealFFT_xlconstant_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Zynq_RealFFT_xlconstant_0_0 || ORIG_REF_NAME==Zynq_RealFFT_xlconstant_0_0} -quiet] -quiet

# IP: bd/Zynq_RealFFT/ip/Zynq_RealFFT_xlconstant_1_0/Zynq_RealFFT_xlconstant_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Zynq_RealFFT_xlconstant_1_0 || ORIG_REF_NAME==Zynq_RealFFT_xlconstant_1_0} -quiet] -quiet

# IP: bd/Zynq_RealFFT/ip/Zynq_RealFFT_processing_system7_0_0/Zynq_RealFFT_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Zynq_RealFFT_processing_system7_0_0 || ORIG_REF_NAME==Zynq_RealFFT_processing_system7_0_0} -quiet] -quiet

# IP: bd/Zynq_RealFFT/ip/Zynq_RealFFT_hls_real2xfft_0_0/Zynq_RealFFT_hls_real2xfft_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Zynq_RealFFT_hls_real2xfft_0_0 || ORIG_REF_NAME==Zynq_RealFFT_hls_real2xfft_0_0} -quiet] -quiet

# IP: bd/Zynq_RealFFT/ip/Zynq_RealFFT_hls_xfft2real_0_0/Zynq_RealFFT_hls_xfft2real_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Zynq_RealFFT_hls_xfft2real_0_0 || ORIG_REF_NAME==Zynq_RealFFT_hls_xfft2real_0_0} -quiet] -quiet

# IP: bd/Zynq_RealFFT/ip/Zynq_RealFFT_axi_dma_0/Zynq_RealFFT_axi_dma_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Zynq_RealFFT_axi_dma_0 || ORIG_REF_NAME==Zynq_RealFFT_axi_dma_0} -quiet] -quiet

# IP: bd/Zynq_RealFFT/ip/Zynq_RealFFT_xbar_0/Zynq_RealFFT_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Zynq_RealFFT_xbar_0 || ORIG_REF_NAME==Zynq_RealFFT_xbar_0} -quiet] -quiet

# IP: bd/Zynq_RealFFT/ip/Zynq_RealFFT_auto_us_0/Zynq_RealFFT_auto_us_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Zynq_RealFFT_auto_us_0 || ORIG_REF_NAME==Zynq_RealFFT_auto_us_0} -quiet] -quiet

# IP: bd/Zynq_RealFFT/ip/Zynq_RealFFT_auto_pc_0/Zynq_RealFFT_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Zynq_RealFFT_auto_pc_0 || ORIG_REF_NAME==Zynq_RealFFT_auto_pc_0} -quiet] -quiet

# IP: bd/Zynq_RealFFT/ip/Zynq_RealFFT_axi_mem_intercon_0/Zynq_RealFFT_axi_mem_intercon_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Zynq_RealFFT_axi_mem_intercon_0 || ORIG_REF_NAME==Zynq_RealFFT_axi_mem_intercon_0} -quiet] -quiet

# IP: bd/Zynq_RealFFT/ip/Zynq_RealFFT_rst_ps7_0_100M_0/Zynq_RealFFT_rst_ps7_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Zynq_RealFFT_rst_ps7_0_100M_0 || ORIG_REF_NAME==Zynq_RealFFT_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/Zynq_RealFFT/ip/Zynq_RealFFT_auto_pc_1/Zynq_RealFFT_auto_pc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Zynq_RealFFT_auto_pc_1 || ORIG_REF_NAME==Zynq_RealFFT_auto_pc_1} -quiet] -quiet

# IP: bd/Zynq_RealFFT/ip/Zynq_RealFFT_ps7_0_axi_periph_0/Zynq_RealFFT_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Zynq_RealFFT_ps7_0_axi_periph_0 || ORIG_REF_NAME==Zynq_RealFFT_ps7_0_axi_periph_0} -quiet] -quiet

# XDC: e:/Courses/EEE5060/LabA/Using_IP_with_Zynq/lab2/project_1/project_1.gen/sources_1/bd/Zynq_RealFFT/Zynq_RealFFT_ooc.xdc
