// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2020.1
// Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _hls_xfft2real_HH_
#define _hls_xfft2real_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "Loop_realfft_be_buff.h"
#include "Loop_realfft_be_desc.h"
#include "Loop_realfft_be_rev_s.h"
#include "Loop_realfft_be_stre.h"
#include "hls_xfft2real_deshbi.h"
#include "hls_xfft2real_desibs.h"
#include "fifo_w16_d8_A.h"
#include "start_for_Loop_rencg.h"

namespace ap_rtl {

struct hls_xfft2real : public sc_module {
    // Port declarations 14
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst_n;
    sc_in< sc_lv<32> > din_TDATA;
    sc_in< sc_lv<1> > din_TLAST;
    sc_out< sc_lv<32> > dout_TDATA;
    sc_out< sc_lv<1> > dout_TLAST;
    sc_in< sc_logic > din_TVALID;
    sc_out< sc_logic > din_TREADY;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > dout_TVALID;
    sc_in< sc_logic > dout_TREADY;
    sc_out< sc_logic > ap_done;
    sc_out< sc_logic > ap_ready;
    sc_out< sc_logic > ap_idle;
    sc_signal< sc_logic > ap_var_for_const2;
    sc_signal< sc_logic > ap_var_for_const0;
    sc_signal< sc_lv<16> > ap_var_for_const1;
    sc_signal< sc_lv<8> > ap_var_for_const3;


    // Module declarations
    hls_xfft2real(sc_module_name name);
    SC_HAS_PROCESS(hls_xfft2real);

    ~hls_xfft2real();

    sc_trace_file* mVcdFile;

    ofstream mHdltvinHandle;
    ofstream mHdltvoutHandle;
    hls_xfft2real_deshbi* descramble_buf_0_M_U;
    hls_xfft2real_desibs* descramble_buf_1_M_U;
    hls_xfft2real_deshbi* descramble_buf_0_M_1_U;
    hls_xfft2real_desibs* descramble_buf_1_M_1_U;
    hls_xfft2real_deshbi* real_spectrum_hi_buf_U;
    hls_xfft2real_deshbi* real_spectrum_hi_buf_1_U;
    Loop_realfft_be_buff* Loop_realfft_be_buff_U0;
    Loop_realfft_be_desc* Loop_realfft_be_desc_U0;
    Loop_realfft_be_rev_s* Loop_realfft_be_rev_U0;
    Loop_realfft_be_stre* Loop_realfft_be_stre_U0;
    fifo_w16_d8_A* real_spectrum_lo_V_s_U;
    fifo_w16_d8_A* real_spectrum_lo_V_1_U;
    fifo_w16_d8_A* real_spectrum_hi_V_s_U;
    fifo_w16_d8_A* real_spectrum_hi_V_1_U;
    start_for_Loop_rencg* start_for_Loop_rencg_U;
    sc_signal< sc_logic > ap_rst_n_inv;
    sc_signal< sc_lv<16> > descramble_buf_0_M_i_q0;
    sc_signal< sc_lv<16> > descramble_buf_0_M_t_q0;
    sc_signal< sc_lv<16> > descramble_buf_1_M_i_q0;
    sc_signal< sc_lv<16> > descramble_buf_1_M_i_q1;
    sc_signal< sc_lv<16> > descramble_buf_1_M_t_q0;
    sc_signal< sc_lv<16> > descramble_buf_1_M_t_q1;
    sc_signal< sc_lv<16> > descramble_buf_0_M_1_i_q0;
    sc_signal< sc_lv<16> > descramble_buf_0_M_1_t_q0;
    sc_signal< sc_lv<16> > descramble_buf_1_M_1_i_q0;
    sc_signal< sc_lv<16> > descramble_buf_1_M_1_i_q1;
    sc_signal< sc_lv<16> > descramble_buf_1_M_1_t_q0;
    sc_signal< sc_lv<16> > descramble_buf_1_M_1_t_q1;
    sc_signal< sc_lv<16> > real_spectrum_hi_buf_i_q0;
    sc_signal< sc_lv<16> > real_spectrum_hi_buf_t_q0;
    sc_signal< sc_lv<16> > real_spectrum_hi_buf_1_i_q0;
    sc_signal< sc_lv<16> > real_spectrum_hi_buf_1_t_q0;
    sc_signal< sc_logic > Loop_realfft_be_buff_U0_ap_start;
    sc_signal< sc_logic > Loop_realfft_be_buff_U0_ap_done;
    sc_signal< sc_logic > Loop_realfft_be_buff_U0_ap_continue;
    sc_signal< sc_logic > Loop_realfft_be_buff_U0_ap_idle;
    sc_signal< sc_logic > Loop_realfft_be_buff_U0_ap_ready;
    sc_signal< sc_lv<8> > Loop_realfft_be_buff_U0_descramble_buf_0_M_imag_V_address0;
    sc_signal< sc_logic > Loop_realfft_be_buff_U0_descramble_buf_0_M_imag_V_ce0;
    sc_signal< sc_logic > Loop_realfft_be_buff_U0_descramble_buf_0_M_imag_V_we0;
    sc_signal< sc_lv<16> > Loop_realfft_be_buff_U0_descramble_buf_0_M_imag_V_d0;
    sc_signal< sc_lv<8> > Loop_realfft_be_buff_U0_descramble_buf_1_M_imag_V_address0;
    sc_signal< sc_logic > Loop_realfft_be_buff_U0_descramble_buf_1_M_imag_V_ce0;
    sc_signal< sc_logic > Loop_realfft_be_buff_U0_descramble_buf_1_M_imag_V_we0;
    sc_signal< sc_lv<16> > Loop_realfft_be_buff_U0_descramble_buf_1_M_imag_V_d0;
    sc_signal< sc_logic > Loop_realfft_be_buff_U0_din_TREADY;
    sc_signal< sc_lv<8> > Loop_realfft_be_buff_U0_descramble_buf_0_M_real_V_address0;
    sc_signal< sc_logic > Loop_realfft_be_buff_U0_descramble_buf_0_M_real_V_ce0;
    sc_signal< sc_logic > Loop_realfft_be_buff_U0_descramble_buf_0_M_real_V_we0;
    sc_signal< sc_lv<16> > Loop_realfft_be_buff_U0_descramble_buf_0_M_real_V_d0;
    sc_signal< sc_lv<8> > Loop_realfft_be_buff_U0_descramble_buf_1_M_real_V_address0;
    sc_signal< sc_logic > Loop_realfft_be_buff_U0_descramble_buf_1_M_real_V_ce0;
    sc_signal< sc_logic > Loop_realfft_be_buff_U0_descramble_buf_1_M_real_V_we0;
    sc_signal< sc_lv<16> > Loop_realfft_be_buff_U0_descramble_buf_1_M_real_V_d0;
    sc_signal< sc_logic > ap_channel_done_descramble_buf_1_M;
    sc_signal< sc_logic > Loop_realfft_be_buff_U0_descramble_buf_1_M_real_V_full_n;
    sc_signal< sc_logic > ap_sync_reg_channel_write_descramble_buf_1_M;
    sc_signal< sc_logic > ap_sync_channel_write_descramble_buf_1_M;
    sc_signal< sc_logic > ap_channel_done_descramble_buf_0_M;
    sc_signal< sc_logic > Loop_realfft_be_buff_U0_descramble_buf_0_M_real_V_full_n;
    sc_signal< sc_logic > ap_sync_reg_channel_write_descramble_buf_0_M;
    sc_signal< sc_logic > ap_sync_channel_write_descramble_buf_0_M;
    sc_signal< sc_logic > ap_channel_done_descramble_buf_1_M_1;
    sc_signal< sc_logic > Loop_realfft_be_buff_U0_descramble_buf_1_M_imag_V_full_n;
    sc_signal< sc_logic > ap_sync_reg_channel_write_descramble_buf_1_M_1;
    sc_signal< sc_logic > ap_sync_channel_write_descramble_buf_1_M_1;
    sc_signal< sc_logic > ap_channel_done_descramble_buf_0_M_1;
    sc_signal< sc_logic > Loop_realfft_be_buff_U0_descramble_buf_0_M_imag_V_full_n;
    sc_signal< sc_logic > ap_sync_reg_channel_write_descramble_buf_0_M_1;
    sc_signal< sc_logic > ap_sync_channel_write_descramble_buf_0_M_1;
    sc_signal< sc_logic > Loop_realfft_be_desc_U0_ap_start;
    sc_signal< sc_logic > Loop_realfft_be_desc_U0_ap_done;
    sc_signal< sc_logic > Loop_realfft_be_desc_U0_ap_continue;
    sc_signal< sc_logic > Loop_realfft_be_desc_U0_ap_idle;
    sc_signal< sc_logic > Loop_realfft_be_desc_U0_ap_ready;
    sc_signal< sc_logic > Loop_realfft_be_desc_U0_start_out;
    sc_signal< sc_logic > Loop_realfft_be_desc_U0_start_write;
    sc_signal< sc_lv<16> > Loop_realfft_be_desc_U0_real_spectrum_lo_V_M_real_V_din;
    sc_signal< sc_logic > Loop_realfft_be_desc_U0_real_spectrum_lo_V_M_real_V_write;
    sc_signal< sc_lv<16> > Loop_realfft_be_desc_U0_real_spectrum_lo_V_M_imag_V_din;
    sc_signal< sc_logic > Loop_realfft_be_desc_U0_real_spectrum_lo_V_M_imag_V_write;
    sc_signal< sc_lv<8> > Loop_realfft_be_desc_U0_real_spectrum_hi_buf_i_0_address0;
    sc_signal< sc_logic > Loop_realfft_be_desc_U0_real_spectrum_hi_buf_i_0_ce0;
    sc_signal< sc_logic > Loop_realfft_be_desc_U0_real_spectrum_hi_buf_i_0_we0;
    sc_signal< sc_lv<16> > Loop_realfft_be_desc_U0_real_spectrum_hi_buf_i_0_d0;
    sc_signal< sc_lv<8> > Loop_realfft_be_desc_U0_real_spectrum_hi_buf_i_1_address0;
    sc_signal< sc_logic > Loop_realfft_be_desc_U0_real_spectrum_hi_buf_i_1_ce0;
    sc_signal< sc_logic > Loop_realfft_be_desc_U0_real_spectrum_hi_buf_i_1_we0;
    sc_signal< sc_lv<16> > Loop_realfft_be_desc_U0_real_spectrum_hi_buf_i_1_d0;
    sc_signal< sc_lv<8> > Loop_realfft_be_desc_U0_descramble_buf_1_M_real_V_address0;
    sc_signal< sc_logic > Loop_realfft_be_desc_U0_descramble_buf_1_M_real_V_ce0;
    sc_signal< sc_lv<8> > Loop_realfft_be_desc_U0_descramble_buf_1_M_real_V_address1;
    sc_signal< sc_logic > Loop_realfft_be_desc_U0_descramble_buf_1_M_real_V_ce1;
    sc_signal< sc_lv<8> > Loop_realfft_be_desc_U0_descramble_buf_1_M_imag_V_address0;
    sc_signal< sc_logic > Loop_realfft_be_desc_U0_descramble_buf_1_M_imag_V_ce0;
    sc_signal< sc_lv<8> > Loop_realfft_be_desc_U0_descramble_buf_1_M_imag_V_address1;
    sc_signal< sc_logic > Loop_realfft_be_desc_U0_descramble_buf_1_M_imag_V_ce1;
    sc_signal< sc_lv<8> > Loop_realfft_be_desc_U0_descramble_buf_0_M_real_V_address0;
    sc_signal< sc_logic > Loop_realfft_be_desc_U0_descramble_buf_0_M_real_V_ce0;
    sc_signal< sc_lv<8> > Loop_realfft_be_desc_U0_descramble_buf_0_M_imag_V_address0;
    sc_signal< sc_logic > Loop_realfft_be_desc_U0_descramble_buf_0_M_imag_V_ce0;
    sc_signal< sc_logic > ap_channel_done_real_spectrum_hi_buf_1;
    sc_signal< sc_logic > Loop_realfft_be_desc_U0_real_spectrum_hi_buf_i_1_full_n;
    sc_signal< sc_logic > ap_sync_reg_channel_write_real_spectrum_hi_buf_1;
    sc_signal< sc_logic > ap_sync_channel_write_real_spectrum_hi_buf_1;
    sc_signal< sc_logic > ap_channel_done_real_spectrum_hi_buf;
    sc_signal< sc_logic > Loop_realfft_be_desc_U0_real_spectrum_hi_buf_i_0_full_n;
    sc_signal< sc_logic > ap_sync_reg_channel_write_real_spectrum_hi_buf;
    sc_signal< sc_logic > ap_sync_channel_write_real_spectrum_hi_buf;
    sc_signal< sc_logic > Loop_realfft_be_rev_U0_ap_start;
    sc_signal< sc_logic > Loop_realfft_be_rev_U0_ap_done;
    sc_signal< sc_logic > Loop_realfft_be_rev_U0_ap_continue;
    sc_signal< sc_logic > Loop_realfft_be_rev_U0_ap_idle;
    sc_signal< sc_logic > Loop_realfft_be_rev_U0_ap_ready;
    sc_signal< sc_lv<8> > Loop_realfft_be_rev_U0_real_spectrum_hi_buf_i_0_address0;
    sc_signal< sc_logic > Loop_realfft_be_rev_U0_real_spectrum_hi_buf_i_0_ce0;
    sc_signal< sc_lv<8> > Loop_realfft_be_rev_U0_real_spectrum_hi_buf_i_1_address0;
    sc_signal< sc_logic > Loop_realfft_be_rev_U0_real_spectrum_hi_buf_i_1_ce0;
    sc_signal< sc_lv<16> > Loop_realfft_be_rev_U0_real_spectrum_hi_V_M_real_V_din;
    sc_signal< sc_logic > Loop_realfft_be_rev_U0_real_spectrum_hi_V_M_real_V_write;
    sc_signal< sc_lv<16> > Loop_realfft_be_rev_U0_real_spectrum_hi_V_M_imag_V_din;
    sc_signal< sc_logic > Loop_realfft_be_rev_U0_real_spectrum_hi_V_M_imag_V_write;
    sc_signal< sc_logic > Loop_realfft_be_stre_U0_ap_start;
    sc_signal< sc_logic > Loop_realfft_be_stre_U0_ap_done;
    sc_signal< sc_logic > Loop_realfft_be_stre_U0_ap_continue;
    sc_signal< sc_logic > Loop_realfft_be_stre_U0_ap_idle;
    sc_signal< sc_logic > Loop_realfft_be_stre_U0_ap_ready;
    sc_signal< sc_logic > Loop_realfft_be_stre_U0_real_spectrum_lo_V_M_real_V_read;
    sc_signal< sc_logic > Loop_realfft_be_stre_U0_real_spectrum_lo_V_M_imag_V_read;
    sc_signal< sc_logic > Loop_realfft_be_stre_U0_real_spectrum_hi_V_M_real_V_read;
    sc_signal< sc_logic > Loop_realfft_be_stre_U0_real_spectrum_hi_V_M_imag_V_read;
    sc_signal< sc_lv<32> > Loop_realfft_be_stre_U0_dout_TDATA;
    sc_signal< sc_logic > Loop_realfft_be_stre_U0_dout_TVALID;
    sc_signal< sc_lv<1> > Loop_realfft_be_stre_U0_dout_TLAST;
    sc_signal< sc_logic > ap_sync_continue;
    sc_signal< sc_logic > descramble_buf_0_M_1_i_full_n;
    sc_signal< sc_logic > descramble_buf_0_M_1_t_empty_n;
    sc_signal< sc_logic > descramble_buf_1_M_1_i_full_n;
    sc_signal< sc_logic > descramble_buf_1_M_1_t_empty_n;
    sc_signal< sc_lv<16> > descramble_buf_1_M_1_t_d1;
    sc_signal< sc_logic > descramble_buf_1_M_1_t_we1;
    sc_signal< sc_logic > descramble_buf_0_M_i_full_n;
    sc_signal< sc_logic > descramble_buf_0_M_t_empty_n;
    sc_signal< sc_logic > descramble_buf_1_M_i_full_n;
    sc_signal< sc_logic > descramble_buf_1_M_t_empty_n;
    sc_signal< sc_lv<16> > descramble_buf_1_M_t_d1;
    sc_signal< sc_logic > descramble_buf_1_M_t_we1;
    sc_signal< sc_logic > real_spectrum_hi_buf_i_full_n;
    sc_signal< sc_logic > real_spectrum_hi_buf_t_empty_n;
    sc_signal< sc_logic > real_spectrum_hi_buf_1_i_full_n;
    sc_signal< sc_logic > real_spectrum_hi_buf_1_t_empty_n;
    sc_signal< sc_logic > real_spectrum_lo_V_s_full_n;
    sc_signal< sc_lv<16> > real_spectrum_lo_V_s_dout;
    sc_signal< sc_logic > real_spectrum_lo_V_s_empty_n;
    sc_signal< sc_logic > real_spectrum_lo_V_1_full_n;
    sc_signal< sc_lv<16> > real_spectrum_lo_V_1_dout;
    sc_signal< sc_logic > real_spectrum_lo_V_1_empty_n;
    sc_signal< sc_logic > real_spectrum_hi_V_s_full_n;
    sc_signal< sc_lv<16> > real_spectrum_hi_V_s_dout;
    sc_signal< sc_logic > real_spectrum_hi_V_s_empty_n;
    sc_signal< sc_logic > real_spectrum_hi_V_1_full_n;
    sc_signal< sc_lv<16> > real_spectrum_hi_V_1_dout;
    sc_signal< sc_logic > real_spectrum_hi_V_1_empty_n;
    sc_signal< sc_logic > ap_sync_done;
    sc_signal< sc_logic > ap_sync_ready;
    sc_signal< sc_logic > Loop_realfft_be_buff_U0_start_full_n;
    sc_signal< sc_logic > Loop_realfft_be_buff_U0_start_write;
    sc_signal< sc_lv<1> > start_for_Loop_realfft_be_stre_U0_din;
    sc_signal< sc_logic > start_for_Loop_realfft_be_stre_U0_full_n;
    sc_signal< sc_lv<1> > start_for_Loop_realfft_be_stre_U0_dout;
    sc_signal< sc_logic > start_for_Loop_realfft_be_stre_U0_empty_n;
    sc_signal< sc_logic > Loop_realfft_be_rev_U0_start_full_n;
    sc_signal< sc_logic > Loop_realfft_be_rev_U0_start_write;
    sc_signal< sc_logic > Loop_realfft_be_stre_U0_start_full_n;
    sc_signal< sc_logic > Loop_realfft_be_stre_U0_start_write;
    static const sc_logic ap_const_logic_1;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<16> ap_const_lv16_0;
    static const sc_lv<8> ap_const_lv8_0;
    static const sc_lv<8> ap_const_lv8_1;
    static const bool ap_const_boolean_1;
    // Thread declarations
    void thread_ap_var_for_const2();
    void thread_ap_var_for_const0();
    void thread_ap_var_for_const1();
    void thread_ap_var_for_const3();
    void thread_ap_clk_no_reset_();
    void thread_Loop_realfft_be_buff_U0_ap_continue();
    void thread_Loop_realfft_be_buff_U0_ap_start();
    void thread_Loop_realfft_be_buff_U0_descramble_buf_0_M_imag_V_full_n();
    void thread_Loop_realfft_be_buff_U0_descramble_buf_0_M_real_V_full_n();
    void thread_Loop_realfft_be_buff_U0_descramble_buf_1_M_imag_V_full_n();
    void thread_Loop_realfft_be_buff_U0_descramble_buf_1_M_real_V_full_n();
    void thread_Loop_realfft_be_buff_U0_start_full_n();
    void thread_Loop_realfft_be_buff_U0_start_write();
    void thread_Loop_realfft_be_desc_U0_ap_continue();
    void thread_Loop_realfft_be_desc_U0_ap_start();
    void thread_Loop_realfft_be_desc_U0_real_spectrum_hi_buf_i_0_full_n();
    void thread_Loop_realfft_be_desc_U0_real_spectrum_hi_buf_i_1_full_n();
    void thread_Loop_realfft_be_rev_U0_ap_continue();
    void thread_Loop_realfft_be_rev_U0_ap_start();
    void thread_Loop_realfft_be_rev_U0_start_full_n();
    void thread_Loop_realfft_be_rev_U0_start_write();
    void thread_Loop_realfft_be_stre_U0_ap_continue();
    void thread_Loop_realfft_be_stre_U0_ap_start();
    void thread_Loop_realfft_be_stre_U0_start_full_n();
    void thread_Loop_realfft_be_stre_U0_start_write();
    void thread_ap_channel_done_descramble_buf_0_M();
    void thread_ap_channel_done_descramble_buf_0_M_1();
    void thread_ap_channel_done_descramble_buf_1_M();
    void thread_ap_channel_done_descramble_buf_1_M_1();
    void thread_ap_channel_done_real_spectrum_hi_buf();
    void thread_ap_channel_done_real_spectrum_hi_buf_1();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_ap_rst_n_inv();
    void thread_ap_sync_channel_write_descramble_buf_0_M();
    void thread_ap_sync_channel_write_descramble_buf_0_M_1();
    void thread_ap_sync_channel_write_descramble_buf_1_M();
    void thread_ap_sync_channel_write_descramble_buf_1_M_1();
    void thread_ap_sync_channel_write_real_spectrum_hi_buf();
    void thread_ap_sync_channel_write_real_spectrum_hi_buf_1();
    void thread_ap_sync_continue();
    void thread_ap_sync_done();
    void thread_ap_sync_ready();
    void thread_descramble_buf_1_M_1_t_d1();
    void thread_descramble_buf_1_M_1_t_we1();
    void thread_descramble_buf_1_M_t_d1();
    void thread_descramble_buf_1_M_t_we1();
    void thread_din_TREADY();
    void thread_dout_TDATA();
    void thread_dout_TLAST();
    void thread_dout_TVALID();
    void thread_start_for_Loop_realfft_be_stre_U0_din();
    void thread_hdltv_gen();
};

}

using namespace ap_rtl;

#endif
