// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2020.1
// Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "hls_xfft2real.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic hls_xfft2real::ap_const_logic_1 = sc_dt::Log_1;
const sc_lv<32> hls_xfft2real::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<1> hls_xfft2real::ap_const_lv1_0 = "0";
const sc_logic hls_xfft2real::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<16> hls_xfft2real::ap_const_lv16_0 = "0000000000000000";
const sc_lv<8> hls_xfft2real::ap_const_lv8_0 = "00000000";
const sc_lv<8> hls_xfft2real::ap_const_lv8_1 = "1";
const bool hls_xfft2real::ap_const_boolean_1 = true;

hls_xfft2real::hls_xfft2real(sc_module_name name) : sc_module(name), mVcdFile(0) {
    descramble_buf_0_M_U = new hls_xfft2real_deshbi("descramble_buf_0_M_U");
    descramble_buf_0_M_U->clk(ap_clk);
    descramble_buf_0_M_U->reset(ap_rst_n_inv);
    descramble_buf_0_M_U->i_address0(Loop_realfft_be_buff_U0_descramble_buf_0_M_real_V_address0);
    descramble_buf_0_M_U->i_ce0(Loop_realfft_be_buff_U0_descramble_buf_0_M_real_V_ce0);
    descramble_buf_0_M_U->i_we0(Loop_realfft_be_buff_U0_descramble_buf_0_M_real_V_we0);
    descramble_buf_0_M_U->i_d0(Loop_realfft_be_buff_U0_descramble_buf_0_M_real_V_d0);
    descramble_buf_0_M_U->i_q0(descramble_buf_0_M_i_q0);
    descramble_buf_0_M_U->t_address0(Loop_realfft_be_desc_U0_descramble_buf_0_M_real_V_address0);
    descramble_buf_0_M_U->t_ce0(Loop_realfft_be_desc_U0_descramble_buf_0_M_real_V_ce0);
    descramble_buf_0_M_U->t_we0(ap_var_for_const0);
    descramble_buf_0_M_U->t_d0(ap_var_for_const1);
    descramble_buf_0_M_U->t_q0(descramble_buf_0_M_t_q0);
    descramble_buf_0_M_U->i_ce(ap_var_for_const2);
    descramble_buf_0_M_U->t_ce(ap_var_for_const2);
    descramble_buf_0_M_U->i_full_n(descramble_buf_0_M_i_full_n);
    descramble_buf_0_M_U->i_write(ap_channel_done_descramble_buf_0_M);
    descramble_buf_0_M_U->t_empty_n(descramble_buf_0_M_t_empty_n);
    descramble_buf_0_M_U->t_read(Loop_realfft_be_desc_U0_ap_ready);
    descramble_buf_1_M_U = new hls_xfft2real_desibs("descramble_buf_1_M_U");
    descramble_buf_1_M_U->clk(ap_clk);
    descramble_buf_1_M_U->reset(ap_rst_n_inv);
    descramble_buf_1_M_U->i_address0(Loop_realfft_be_buff_U0_descramble_buf_1_M_real_V_address0);
    descramble_buf_1_M_U->i_ce0(Loop_realfft_be_buff_U0_descramble_buf_1_M_real_V_ce0);
    descramble_buf_1_M_U->i_we0(Loop_realfft_be_buff_U0_descramble_buf_1_M_real_V_we0);
    descramble_buf_1_M_U->i_d0(Loop_realfft_be_buff_U0_descramble_buf_1_M_real_V_d0);
    descramble_buf_1_M_U->i_q0(descramble_buf_1_M_i_q0);
    descramble_buf_1_M_U->i_address1(ap_var_for_const3);
    descramble_buf_1_M_U->i_ce1(ap_var_for_const0);
    descramble_buf_1_M_U->i_q1(descramble_buf_1_M_i_q1);
    descramble_buf_1_M_U->t_address0(Loop_realfft_be_desc_U0_descramble_buf_1_M_real_V_address0);
    descramble_buf_1_M_U->t_ce0(Loop_realfft_be_desc_U0_descramble_buf_1_M_real_V_ce0);
    descramble_buf_1_M_U->t_we0(ap_var_for_const0);
    descramble_buf_1_M_U->t_d0(ap_var_for_const1);
    descramble_buf_1_M_U->t_q0(descramble_buf_1_M_t_q0);
    descramble_buf_1_M_U->t_address1(Loop_realfft_be_desc_U0_descramble_buf_1_M_real_V_address1);
    descramble_buf_1_M_U->t_ce1(Loop_realfft_be_desc_U0_descramble_buf_1_M_real_V_ce1);
    descramble_buf_1_M_U->t_q1(descramble_buf_1_M_t_q1);
    descramble_buf_1_M_U->i_ce(ap_var_for_const2);
    descramble_buf_1_M_U->t_ce(ap_var_for_const2);
    descramble_buf_1_M_U->i_full_n(descramble_buf_1_M_i_full_n);
    descramble_buf_1_M_U->i_write(ap_channel_done_descramble_buf_1_M);
    descramble_buf_1_M_U->t_empty_n(descramble_buf_1_M_t_empty_n);
    descramble_buf_1_M_U->t_read(Loop_realfft_be_desc_U0_ap_ready);
    descramble_buf_0_M_1_U = new hls_xfft2real_deshbi("descramble_buf_0_M_1_U");
    descramble_buf_0_M_1_U->clk(ap_clk);
    descramble_buf_0_M_1_U->reset(ap_rst_n_inv);
    descramble_buf_0_M_1_U->i_address0(Loop_realfft_be_buff_U0_descramble_buf_0_M_imag_V_address0);
    descramble_buf_0_M_1_U->i_ce0(Loop_realfft_be_buff_U0_descramble_buf_0_M_imag_V_ce0);
    descramble_buf_0_M_1_U->i_we0(Loop_realfft_be_buff_U0_descramble_buf_0_M_imag_V_we0);
    descramble_buf_0_M_1_U->i_d0(Loop_realfft_be_buff_U0_descramble_buf_0_M_imag_V_d0);
    descramble_buf_0_M_1_U->i_q0(descramble_buf_0_M_1_i_q0);
    descramble_buf_0_M_1_U->t_address0(Loop_realfft_be_desc_U0_descramble_buf_0_M_imag_V_address0);
    descramble_buf_0_M_1_U->t_ce0(Loop_realfft_be_desc_U0_descramble_buf_0_M_imag_V_ce0);
    descramble_buf_0_M_1_U->t_we0(ap_var_for_const0);
    descramble_buf_0_M_1_U->t_d0(ap_var_for_const1);
    descramble_buf_0_M_1_U->t_q0(descramble_buf_0_M_1_t_q0);
    descramble_buf_0_M_1_U->i_ce(ap_var_for_const2);
    descramble_buf_0_M_1_U->t_ce(ap_var_for_const2);
    descramble_buf_0_M_1_U->i_full_n(descramble_buf_0_M_1_i_full_n);
    descramble_buf_0_M_1_U->i_write(ap_channel_done_descramble_buf_0_M_1);
    descramble_buf_0_M_1_U->t_empty_n(descramble_buf_0_M_1_t_empty_n);
    descramble_buf_0_M_1_U->t_read(Loop_realfft_be_desc_U0_ap_ready);
    descramble_buf_1_M_1_U = new hls_xfft2real_desibs("descramble_buf_1_M_1_U");
    descramble_buf_1_M_1_U->clk(ap_clk);
    descramble_buf_1_M_1_U->reset(ap_rst_n_inv);
    descramble_buf_1_M_1_U->i_address0(Loop_realfft_be_buff_U0_descramble_buf_1_M_imag_V_address0);
    descramble_buf_1_M_1_U->i_ce0(Loop_realfft_be_buff_U0_descramble_buf_1_M_imag_V_ce0);
    descramble_buf_1_M_1_U->i_we0(Loop_realfft_be_buff_U0_descramble_buf_1_M_imag_V_we0);
    descramble_buf_1_M_1_U->i_d0(Loop_realfft_be_buff_U0_descramble_buf_1_M_imag_V_d0);
    descramble_buf_1_M_1_U->i_q0(descramble_buf_1_M_1_i_q0);
    descramble_buf_1_M_1_U->i_address1(ap_var_for_const3);
    descramble_buf_1_M_1_U->i_ce1(ap_var_for_const0);
    descramble_buf_1_M_1_U->i_q1(descramble_buf_1_M_1_i_q1);
    descramble_buf_1_M_1_U->t_address0(Loop_realfft_be_desc_U0_descramble_buf_1_M_imag_V_address0);
    descramble_buf_1_M_1_U->t_ce0(Loop_realfft_be_desc_U0_descramble_buf_1_M_imag_V_ce0);
    descramble_buf_1_M_1_U->t_we0(ap_var_for_const0);
    descramble_buf_1_M_1_U->t_d0(ap_var_for_const1);
    descramble_buf_1_M_1_U->t_q0(descramble_buf_1_M_1_t_q0);
    descramble_buf_1_M_1_U->t_address1(Loop_realfft_be_desc_U0_descramble_buf_1_M_imag_V_address1);
    descramble_buf_1_M_1_U->t_ce1(Loop_realfft_be_desc_U0_descramble_buf_1_M_imag_V_ce1);
    descramble_buf_1_M_1_U->t_q1(descramble_buf_1_M_1_t_q1);
    descramble_buf_1_M_1_U->i_ce(ap_var_for_const2);
    descramble_buf_1_M_1_U->t_ce(ap_var_for_const2);
    descramble_buf_1_M_1_U->i_full_n(descramble_buf_1_M_1_i_full_n);
    descramble_buf_1_M_1_U->i_write(ap_channel_done_descramble_buf_1_M_1);
    descramble_buf_1_M_1_U->t_empty_n(descramble_buf_1_M_1_t_empty_n);
    descramble_buf_1_M_1_U->t_read(Loop_realfft_be_desc_U0_ap_ready);
    real_spectrum_hi_buf_U = new hls_xfft2real_deshbi("real_spectrum_hi_buf_U");
    real_spectrum_hi_buf_U->clk(ap_clk);
    real_spectrum_hi_buf_U->reset(ap_rst_n_inv);
    real_spectrum_hi_buf_U->i_address0(Loop_realfft_be_desc_U0_real_spectrum_hi_buf_i_0_address0);
    real_spectrum_hi_buf_U->i_ce0(Loop_realfft_be_desc_U0_real_spectrum_hi_buf_i_0_ce0);
    real_spectrum_hi_buf_U->i_we0(Loop_realfft_be_desc_U0_real_spectrum_hi_buf_i_0_we0);
    real_spectrum_hi_buf_U->i_d0(Loop_realfft_be_desc_U0_real_spectrum_hi_buf_i_0_d0);
    real_spectrum_hi_buf_U->i_q0(real_spectrum_hi_buf_i_q0);
    real_spectrum_hi_buf_U->t_address0(Loop_realfft_be_rev_U0_real_spectrum_hi_buf_i_0_address0);
    real_spectrum_hi_buf_U->t_ce0(Loop_realfft_be_rev_U0_real_spectrum_hi_buf_i_0_ce0);
    real_spectrum_hi_buf_U->t_we0(ap_var_for_const0);
    real_spectrum_hi_buf_U->t_d0(ap_var_for_const1);
    real_spectrum_hi_buf_U->t_q0(real_spectrum_hi_buf_t_q0);
    real_spectrum_hi_buf_U->i_ce(ap_var_for_const2);
    real_spectrum_hi_buf_U->t_ce(ap_var_for_const2);
    real_spectrum_hi_buf_U->i_full_n(real_spectrum_hi_buf_i_full_n);
    real_spectrum_hi_buf_U->i_write(ap_channel_done_real_spectrum_hi_buf);
    real_spectrum_hi_buf_U->t_empty_n(real_spectrum_hi_buf_t_empty_n);
    real_spectrum_hi_buf_U->t_read(Loop_realfft_be_rev_U0_ap_ready);
    real_spectrum_hi_buf_1_U = new hls_xfft2real_deshbi("real_spectrum_hi_buf_1_U");
    real_spectrum_hi_buf_1_U->clk(ap_clk);
    real_spectrum_hi_buf_1_U->reset(ap_rst_n_inv);
    real_spectrum_hi_buf_1_U->i_address0(Loop_realfft_be_desc_U0_real_spectrum_hi_buf_i_1_address0);
    real_spectrum_hi_buf_1_U->i_ce0(Loop_realfft_be_desc_U0_real_spectrum_hi_buf_i_1_ce0);
    real_spectrum_hi_buf_1_U->i_we0(Loop_realfft_be_desc_U0_real_spectrum_hi_buf_i_1_we0);
    real_spectrum_hi_buf_1_U->i_d0(Loop_realfft_be_desc_U0_real_spectrum_hi_buf_i_1_d0);
    real_spectrum_hi_buf_1_U->i_q0(real_spectrum_hi_buf_1_i_q0);
    real_spectrum_hi_buf_1_U->t_address0(Loop_realfft_be_rev_U0_real_spectrum_hi_buf_i_1_address0);
    real_spectrum_hi_buf_1_U->t_ce0(Loop_realfft_be_rev_U0_real_spectrum_hi_buf_i_1_ce0);
    real_spectrum_hi_buf_1_U->t_we0(ap_var_for_const0);
    real_spectrum_hi_buf_1_U->t_d0(ap_var_for_const1);
    real_spectrum_hi_buf_1_U->t_q0(real_spectrum_hi_buf_1_t_q0);
    real_spectrum_hi_buf_1_U->i_ce(ap_var_for_const2);
    real_spectrum_hi_buf_1_U->t_ce(ap_var_for_const2);
    real_spectrum_hi_buf_1_U->i_full_n(real_spectrum_hi_buf_1_i_full_n);
    real_spectrum_hi_buf_1_U->i_write(ap_channel_done_real_spectrum_hi_buf_1);
    real_spectrum_hi_buf_1_U->t_empty_n(real_spectrum_hi_buf_1_t_empty_n);
    real_spectrum_hi_buf_1_U->t_read(Loop_realfft_be_rev_U0_ap_ready);
    Loop_realfft_be_buff_U0 = new Loop_realfft_be_buff("Loop_realfft_be_buff_U0");
    Loop_realfft_be_buff_U0->ap_clk(ap_clk);
    Loop_realfft_be_buff_U0->ap_rst(ap_rst_n_inv);
    Loop_realfft_be_buff_U0->ap_start(Loop_realfft_be_buff_U0_ap_start);
    Loop_realfft_be_buff_U0->ap_done(Loop_realfft_be_buff_U0_ap_done);
    Loop_realfft_be_buff_U0->ap_continue(Loop_realfft_be_buff_U0_ap_continue);
    Loop_realfft_be_buff_U0->ap_idle(Loop_realfft_be_buff_U0_ap_idle);
    Loop_realfft_be_buff_U0->ap_ready(Loop_realfft_be_buff_U0_ap_ready);
    Loop_realfft_be_buff_U0->descramble_buf_0_M_imag_V_address0(Loop_realfft_be_buff_U0_descramble_buf_0_M_imag_V_address0);
    Loop_realfft_be_buff_U0->descramble_buf_0_M_imag_V_ce0(Loop_realfft_be_buff_U0_descramble_buf_0_M_imag_V_ce0);
    Loop_realfft_be_buff_U0->descramble_buf_0_M_imag_V_we0(Loop_realfft_be_buff_U0_descramble_buf_0_M_imag_V_we0);
    Loop_realfft_be_buff_U0->descramble_buf_0_M_imag_V_d0(Loop_realfft_be_buff_U0_descramble_buf_0_M_imag_V_d0);
    Loop_realfft_be_buff_U0->descramble_buf_1_M_imag_V_address0(Loop_realfft_be_buff_U0_descramble_buf_1_M_imag_V_address0);
    Loop_realfft_be_buff_U0->descramble_buf_1_M_imag_V_ce0(Loop_realfft_be_buff_U0_descramble_buf_1_M_imag_V_ce0);
    Loop_realfft_be_buff_U0->descramble_buf_1_M_imag_V_we0(Loop_realfft_be_buff_U0_descramble_buf_1_M_imag_V_we0);
    Loop_realfft_be_buff_U0->descramble_buf_1_M_imag_V_d0(Loop_realfft_be_buff_U0_descramble_buf_1_M_imag_V_d0);
    Loop_realfft_be_buff_U0->din_TDATA(din_TDATA);
    Loop_realfft_be_buff_U0->din_TVALID(din_TVALID);
    Loop_realfft_be_buff_U0->din_TREADY(Loop_realfft_be_buff_U0_din_TREADY);
    Loop_realfft_be_buff_U0->din_TLAST(din_TLAST);
    Loop_realfft_be_buff_U0->descramble_buf_0_M_real_V_address0(Loop_realfft_be_buff_U0_descramble_buf_0_M_real_V_address0);
    Loop_realfft_be_buff_U0->descramble_buf_0_M_real_V_ce0(Loop_realfft_be_buff_U0_descramble_buf_0_M_real_V_ce0);
    Loop_realfft_be_buff_U0->descramble_buf_0_M_real_V_we0(Loop_realfft_be_buff_U0_descramble_buf_0_M_real_V_we0);
    Loop_realfft_be_buff_U0->descramble_buf_0_M_real_V_d0(Loop_realfft_be_buff_U0_descramble_buf_0_M_real_V_d0);
    Loop_realfft_be_buff_U0->descramble_buf_1_M_real_V_address0(Loop_realfft_be_buff_U0_descramble_buf_1_M_real_V_address0);
    Loop_realfft_be_buff_U0->descramble_buf_1_M_real_V_ce0(Loop_realfft_be_buff_U0_descramble_buf_1_M_real_V_ce0);
    Loop_realfft_be_buff_U0->descramble_buf_1_M_real_V_we0(Loop_realfft_be_buff_U0_descramble_buf_1_M_real_V_we0);
    Loop_realfft_be_buff_U0->descramble_buf_1_M_real_V_d0(Loop_realfft_be_buff_U0_descramble_buf_1_M_real_V_d0);
    Loop_realfft_be_desc_U0 = new Loop_realfft_be_desc("Loop_realfft_be_desc_U0");
    Loop_realfft_be_desc_U0->ap_clk(ap_clk);
    Loop_realfft_be_desc_U0->ap_rst(ap_rst_n_inv);
    Loop_realfft_be_desc_U0->ap_start(Loop_realfft_be_desc_U0_ap_start);
    Loop_realfft_be_desc_U0->start_full_n(start_for_Loop_realfft_be_stre_U0_full_n);
    Loop_realfft_be_desc_U0->ap_done(Loop_realfft_be_desc_U0_ap_done);
    Loop_realfft_be_desc_U0->ap_continue(Loop_realfft_be_desc_U0_ap_continue);
    Loop_realfft_be_desc_U0->ap_idle(Loop_realfft_be_desc_U0_ap_idle);
    Loop_realfft_be_desc_U0->ap_ready(Loop_realfft_be_desc_U0_ap_ready);
    Loop_realfft_be_desc_U0->start_out(Loop_realfft_be_desc_U0_start_out);
    Loop_realfft_be_desc_U0->start_write(Loop_realfft_be_desc_U0_start_write);
    Loop_realfft_be_desc_U0->real_spectrum_lo_V_M_real_V_din(Loop_realfft_be_desc_U0_real_spectrum_lo_V_M_real_V_din);
    Loop_realfft_be_desc_U0->real_spectrum_lo_V_M_real_V_full_n(real_spectrum_lo_V_s_full_n);
    Loop_realfft_be_desc_U0->real_spectrum_lo_V_M_real_V_write(Loop_realfft_be_desc_U0_real_spectrum_lo_V_M_real_V_write);
    Loop_realfft_be_desc_U0->real_spectrum_lo_V_M_imag_V_din(Loop_realfft_be_desc_U0_real_spectrum_lo_V_M_imag_V_din);
    Loop_realfft_be_desc_U0->real_spectrum_lo_V_M_imag_V_full_n(real_spectrum_lo_V_1_full_n);
    Loop_realfft_be_desc_U0->real_spectrum_lo_V_M_imag_V_write(Loop_realfft_be_desc_U0_real_spectrum_lo_V_M_imag_V_write);
    Loop_realfft_be_desc_U0->real_spectrum_hi_buf_i_0_address0(Loop_realfft_be_desc_U0_real_spectrum_hi_buf_i_0_address0);
    Loop_realfft_be_desc_U0->real_spectrum_hi_buf_i_0_ce0(Loop_realfft_be_desc_U0_real_spectrum_hi_buf_i_0_ce0);
    Loop_realfft_be_desc_U0->real_spectrum_hi_buf_i_0_we0(Loop_realfft_be_desc_U0_real_spectrum_hi_buf_i_0_we0);
    Loop_realfft_be_desc_U0->real_spectrum_hi_buf_i_0_d0(Loop_realfft_be_desc_U0_real_spectrum_hi_buf_i_0_d0);
    Loop_realfft_be_desc_U0->real_spectrum_hi_buf_i_1_address0(Loop_realfft_be_desc_U0_real_spectrum_hi_buf_i_1_address0);
    Loop_realfft_be_desc_U0->real_spectrum_hi_buf_i_1_ce0(Loop_realfft_be_desc_U0_real_spectrum_hi_buf_i_1_ce0);
    Loop_realfft_be_desc_U0->real_spectrum_hi_buf_i_1_we0(Loop_realfft_be_desc_U0_real_spectrum_hi_buf_i_1_we0);
    Loop_realfft_be_desc_U0->real_spectrum_hi_buf_i_1_d0(Loop_realfft_be_desc_U0_real_spectrum_hi_buf_i_1_d0);
    Loop_realfft_be_desc_U0->descramble_buf_1_M_real_V_address0(Loop_realfft_be_desc_U0_descramble_buf_1_M_real_V_address0);
    Loop_realfft_be_desc_U0->descramble_buf_1_M_real_V_ce0(Loop_realfft_be_desc_U0_descramble_buf_1_M_real_V_ce0);
    Loop_realfft_be_desc_U0->descramble_buf_1_M_real_V_q0(descramble_buf_1_M_t_q0);
    Loop_realfft_be_desc_U0->descramble_buf_1_M_real_V_address1(Loop_realfft_be_desc_U0_descramble_buf_1_M_real_V_address1);
    Loop_realfft_be_desc_U0->descramble_buf_1_M_real_V_ce1(Loop_realfft_be_desc_U0_descramble_buf_1_M_real_V_ce1);
    Loop_realfft_be_desc_U0->descramble_buf_1_M_real_V_q1(descramble_buf_1_M_t_q1);
    Loop_realfft_be_desc_U0->descramble_buf_1_M_imag_V_address0(Loop_realfft_be_desc_U0_descramble_buf_1_M_imag_V_address0);
    Loop_realfft_be_desc_U0->descramble_buf_1_M_imag_V_ce0(Loop_realfft_be_desc_U0_descramble_buf_1_M_imag_V_ce0);
    Loop_realfft_be_desc_U0->descramble_buf_1_M_imag_V_q0(descramble_buf_1_M_1_t_q0);
    Loop_realfft_be_desc_U0->descramble_buf_1_M_imag_V_address1(Loop_realfft_be_desc_U0_descramble_buf_1_M_imag_V_address1);
    Loop_realfft_be_desc_U0->descramble_buf_1_M_imag_V_ce1(Loop_realfft_be_desc_U0_descramble_buf_1_M_imag_V_ce1);
    Loop_realfft_be_desc_U0->descramble_buf_1_M_imag_V_q1(descramble_buf_1_M_1_t_q1);
    Loop_realfft_be_desc_U0->descramble_buf_0_M_real_V_address0(Loop_realfft_be_desc_U0_descramble_buf_0_M_real_V_address0);
    Loop_realfft_be_desc_U0->descramble_buf_0_M_real_V_ce0(Loop_realfft_be_desc_U0_descramble_buf_0_M_real_V_ce0);
    Loop_realfft_be_desc_U0->descramble_buf_0_M_real_V_q0(descramble_buf_0_M_t_q0);
    Loop_realfft_be_desc_U0->descramble_buf_0_M_imag_V_address0(Loop_realfft_be_desc_U0_descramble_buf_0_M_imag_V_address0);
    Loop_realfft_be_desc_U0->descramble_buf_0_M_imag_V_ce0(Loop_realfft_be_desc_U0_descramble_buf_0_M_imag_V_ce0);
    Loop_realfft_be_desc_U0->descramble_buf_0_M_imag_V_q0(descramble_buf_0_M_1_t_q0);
    Loop_realfft_be_rev_U0 = new Loop_realfft_be_rev_s("Loop_realfft_be_rev_U0");
    Loop_realfft_be_rev_U0->ap_clk(ap_clk);
    Loop_realfft_be_rev_U0->ap_rst(ap_rst_n_inv);
    Loop_realfft_be_rev_U0->ap_start(Loop_realfft_be_rev_U0_ap_start);
    Loop_realfft_be_rev_U0->ap_done(Loop_realfft_be_rev_U0_ap_done);
    Loop_realfft_be_rev_U0->ap_continue(Loop_realfft_be_rev_U0_ap_continue);
    Loop_realfft_be_rev_U0->ap_idle(Loop_realfft_be_rev_U0_ap_idle);
    Loop_realfft_be_rev_U0->ap_ready(Loop_realfft_be_rev_U0_ap_ready);
    Loop_realfft_be_rev_U0->real_spectrum_hi_buf_i_0_address0(Loop_realfft_be_rev_U0_real_spectrum_hi_buf_i_0_address0);
    Loop_realfft_be_rev_U0->real_spectrum_hi_buf_i_0_ce0(Loop_realfft_be_rev_U0_real_spectrum_hi_buf_i_0_ce0);
    Loop_realfft_be_rev_U0->real_spectrum_hi_buf_i_0_q0(real_spectrum_hi_buf_t_q0);
    Loop_realfft_be_rev_U0->real_spectrum_hi_buf_i_1_address0(Loop_realfft_be_rev_U0_real_spectrum_hi_buf_i_1_address0);
    Loop_realfft_be_rev_U0->real_spectrum_hi_buf_i_1_ce0(Loop_realfft_be_rev_U0_real_spectrum_hi_buf_i_1_ce0);
    Loop_realfft_be_rev_U0->real_spectrum_hi_buf_i_1_q0(real_spectrum_hi_buf_1_t_q0);
    Loop_realfft_be_rev_U0->real_spectrum_hi_V_M_real_V_din(Loop_realfft_be_rev_U0_real_spectrum_hi_V_M_real_V_din);
    Loop_realfft_be_rev_U0->real_spectrum_hi_V_M_real_V_full_n(real_spectrum_hi_V_s_full_n);
    Loop_realfft_be_rev_U0->real_spectrum_hi_V_M_real_V_write(Loop_realfft_be_rev_U0_real_spectrum_hi_V_M_real_V_write);
    Loop_realfft_be_rev_U0->real_spectrum_hi_V_M_imag_V_din(Loop_realfft_be_rev_U0_real_spectrum_hi_V_M_imag_V_din);
    Loop_realfft_be_rev_U0->real_spectrum_hi_V_M_imag_V_full_n(real_spectrum_hi_V_1_full_n);
    Loop_realfft_be_rev_U0->real_spectrum_hi_V_M_imag_V_write(Loop_realfft_be_rev_U0_real_spectrum_hi_V_M_imag_V_write);
    Loop_realfft_be_stre_U0 = new Loop_realfft_be_stre("Loop_realfft_be_stre_U0");
    Loop_realfft_be_stre_U0->ap_clk(ap_clk);
    Loop_realfft_be_stre_U0->ap_rst(ap_rst_n_inv);
    Loop_realfft_be_stre_U0->ap_start(Loop_realfft_be_stre_U0_ap_start);
    Loop_realfft_be_stre_U0->ap_done(Loop_realfft_be_stre_U0_ap_done);
    Loop_realfft_be_stre_U0->ap_continue(Loop_realfft_be_stre_U0_ap_continue);
    Loop_realfft_be_stre_U0->ap_idle(Loop_realfft_be_stre_U0_ap_idle);
    Loop_realfft_be_stre_U0->ap_ready(Loop_realfft_be_stre_U0_ap_ready);
    Loop_realfft_be_stre_U0->real_spectrum_lo_V_M_real_V_dout(real_spectrum_lo_V_s_dout);
    Loop_realfft_be_stre_U0->real_spectrum_lo_V_M_real_V_empty_n(real_spectrum_lo_V_s_empty_n);
    Loop_realfft_be_stre_U0->real_spectrum_lo_V_M_real_V_read(Loop_realfft_be_stre_U0_real_spectrum_lo_V_M_real_V_read);
    Loop_realfft_be_stre_U0->real_spectrum_lo_V_M_imag_V_dout(real_spectrum_lo_V_1_dout);
    Loop_realfft_be_stre_U0->real_spectrum_lo_V_M_imag_V_empty_n(real_spectrum_lo_V_1_empty_n);
    Loop_realfft_be_stre_U0->real_spectrum_lo_V_M_imag_V_read(Loop_realfft_be_stre_U0_real_spectrum_lo_V_M_imag_V_read);
    Loop_realfft_be_stre_U0->real_spectrum_hi_V_M_real_V_dout(real_spectrum_hi_V_s_dout);
    Loop_realfft_be_stre_U0->real_spectrum_hi_V_M_real_V_empty_n(real_spectrum_hi_V_s_empty_n);
    Loop_realfft_be_stre_U0->real_spectrum_hi_V_M_real_V_read(Loop_realfft_be_stre_U0_real_spectrum_hi_V_M_real_V_read);
    Loop_realfft_be_stre_U0->real_spectrum_hi_V_M_imag_V_dout(real_spectrum_hi_V_1_dout);
    Loop_realfft_be_stre_U0->real_spectrum_hi_V_M_imag_V_empty_n(real_spectrum_hi_V_1_empty_n);
    Loop_realfft_be_stre_U0->real_spectrum_hi_V_M_imag_V_read(Loop_realfft_be_stre_U0_real_spectrum_hi_V_M_imag_V_read);
    Loop_realfft_be_stre_U0->dout_TREADY(dout_TREADY);
    Loop_realfft_be_stre_U0->dout_TDATA(Loop_realfft_be_stre_U0_dout_TDATA);
    Loop_realfft_be_stre_U0->dout_TVALID(Loop_realfft_be_stre_U0_dout_TVALID);
    Loop_realfft_be_stre_U0->dout_TLAST(Loop_realfft_be_stre_U0_dout_TLAST);
    real_spectrum_lo_V_s_U = new fifo_w16_d8_A("real_spectrum_lo_V_s_U");
    real_spectrum_lo_V_s_U->clk(ap_clk);
    real_spectrum_lo_V_s_U->reset(ap_rst_n_inv);
    real_spectrum_lo_V_s_U->if_read_ce(ap_var_for_const2);
    real_spectrum_lo_V_s_U->if_write_ce(ap_var_for_const2);
    real_spectrum_lo_V_s_U->if_din(Loop_realfft_be_desc_U0_real_spectrum_lo_V_M_real_V_din);
    real_spectrum_lo_V_s_U->if_full_n(real_spectrum_lo_V_s_full_n);
    real_spectrum_lo_V_s_U->if_write(Loop_realfft_be_desc_U0_real_spectrum_lo_V_M_real_V_write);
    real_spectrum_lo_V_s_U->if_dout(real_spectrum_lo_V_s_dout);
    real_spectrum_lo_V_s_U->if_empty_n(real_spectrum_lo_V_s_empty_n);
    real_spectrum_lo_V_s_U->if_read(Loop_realfft_be_stre_U0_real_spectrum_lo_V_M_real_V_read);
    real_spectrum_lo_V_1_U = new fifo_w16_d8_A("real_spectrum_lo_V_1_U");
    real_spectrum_lo_V_1_U->clk(ap_clk);
    real_spectrum_lo_V_1_U->reset(ap_rst_n_inv);
    real_spectrum_lo_V_1_U->if_read_ce(ap_var_for_const2);
    real_spectrum_lo_V_1_U->if_write_ce(ap_var_for_const2);
    real_spectrum_lo_V_1_U->if_din(Loop_realfft_be_desc_U0_real_spectrum_lo_V_M_imag_V_din);
    real_spectrum_lo_V_1_U->if_full_n(real_spectrum_lo_V_1_full_n);
    real_spectrum_lo_V_1_U->if_write(Loop_realfft_be_desc_U0_real_spectrum_lo_V_M_imag_V_write);
    real_spectrum_lo_V_1_U->if_dout(real_spectrum_lo_V_1_dout);
    real_spectrum_lo_V_1_U->if_empty_n(real_spectrum_lo_V_1_empty_n);
    real_spectrum_lo_V_1_U->if_read(Loop_realfft_be_stre_U0_real_spectrum_lo_V_M_imag_V_read);
    real_spectrum_hi_V_s_U = new fifo_w16_d8_A("real_spectrum_hi_V_s_U");
    real_spectrum_hi_V_s_U->clk(ap_clk);
    real_spectrum_hi_V_s_U->reset(ap_rst_n_inv);
    real_spectrum_hi_V_s_U->if_read_ce(ap_var_for_const2);
    real_spectrum_hi_V_s_U->if_write_ce(ap_var_for_const2);
    real_spectrum_hi_V_s_U->if_din(Loop_realfft_be_rev_U0_real_spectrum_hi_V_M_real_V_din);
    real_spectrum_hi_V_s_U->if_full_n(real_spectrum_hi_V_s_full_n);
    real_spectrum_hi_V_s_U->if_write(Loop_realfft_be_rev_U0_real_spectrum_hi_V_M_real_V_write);
    real_spectrum_hi_V_s_U->if_dout(real_spectrum_hi_V_s_dout);
    real_spectrum_hi_V_s_U->if_empty_n(real_spectrum_hi_V_s_empty_n);
    real_spectrum_hi_V_s_U->if_read(Loop_realfft_be_stre_U0_real_spectrum_hi_V_M_real_V_read);
    real_spectrum_hi_V_1_U = new fifo_w16_d8_A("real_spectrum_hi_V_1_U");
    real_spectrum_hi_V_1_U->clk(ap_clk);
    real_spectrum_hi_V_1_U->reset(ap_rst_n_inv);
    real_spectrum_hi_V_1_U->if_read_ce(ap_var_for_const2);
    real_spectrum_hi_V_1_U->if_write_ce(ap_var_for_const2);
    real_spectrum_hi_V_1_U->if_din(Loop_realfft_be_rev_U0_real_spectrum_hi_V_M_imag_V_din);
    real_spectrum_hi_V_1_U->if_full_n(real_spectrum_hi_V_1_full_n);
    real_spectrum_hi_V_1_U->if_write(Loop_realfft_be_rev_U0_real_spectrum_hi_V_M_imag_V_write);
    real_spectrum_hi_V_1_U->if_dout(real_spectrum_hi_V_1_dout);
    real_spectrum_hi_V_1_U->if_empty_n(real_spectrum_hi_V_1_empty_n);
    real_spectrum_hi_V_1_U->if_read(Loop_realfft_be_stre_U0_real_spectrum_hi_V_M_imag_V_read);
    start_for_Loop_rencg_U = new start_for_Loop_rencg("start_for_Loop_rencg_U");
    start_for_Loop_rencg_U->clk(ap_clk);
    start_for_Loop_rencg_U->reset(ap_rst_n_inv);
    start_for_Loop_rencg_U->if_read_ce(ap_var_for_const2);
    start_for_Loop_rencg_U->if_write_ce(ap_var_for_const2);
    start_for_Loop_rencg_U->if_din(start_for_Loop_realfft_be_stre_U0_din);
    start_for_Loop_rencg_U->if_full_n(start_for_Loop_realfft_be_stre_U0_full_n);
    start_for_Loop_rencg_U->if_write(Loop_realfft_be_desc_U0_start_write);
    start_for_Loop_rencg_U->if_dout(start_for_Loop_realfft_be_stre_U0_dout);
    start_for_Loop_rencg_U->if_empty_n(start_for_Loop_realfft_be_stre_U0_empty_n);
    start_for_Loop_rencg_U->if_read(Loop_realfft_be_stre_U0_ap_ready);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_Loop_realfft_be_buff_U0_ap_continue);
    sensitive << ( ap_sync_channel_write_descramble_buf_1_M );
    sensitive << ( ap_sync_channel_write_descramble_buf_0_M );
    sensitive << ( ap_sync_channel_write_descramble_buf_1_M_1 );
    sensitive << ( ap_sync_channel_write_descramble_buf_0_M_1 );

    SC_METHOD(thread_Loop_realfft_be_buff_U0_ap_start);
    sensitive << ( ap_start );

    SC_METHOD(thread_Loop_realfft_be_buff_U0_descramble_buf_0_M_imag_V_full_n);
    sensitive << ( descramble_buf_0_M_1_i_full_n );

    SC_METHOD(thread_Loop_realfft_be_buff_U0_descramble_buf_0_M_real_V_full_n);
    sensitive << ( descramble_buf_0_M_i_full_n );

    SC_METHOD(thread_Loop_realfft_be_buff_U0_descramble_buf_1_M_imag_V_full_n);
    sensitive << ( descramble_buf_1_M_1_i_full_n );

    SC_METHOD(thread_Loop_realfft_be_buff_U0_descramble_buf_1_M_real_V_full_n);
    sensitive << ( descramble_buf_1_M_i_full_n );

    SC_METHOD(thread_Loop_realfft_be_buff_U0_start_full_n);

    SC_METHOD(thread_Loop_realfft_be_buff_U0_start_write);

    SC_METHOD(thread_Loop_realfft_be_desc_U0_ap_continue);
    sensitive << ( ap_sync_channel_write_real_spectrum_hi_buf_1 );
    sensitive << ( ap_sync_channel_write_real_spectrum_hi_buf );

    SC_METHOD(thread_Loop_realfft_be_desc_U0_ap_start);
    sensitive << ( descramble_buf_0_M_1_t_empty_n );
    sensitive << ( descramble_buf_1_M_1_t_empty_n );
    sensitive << ( descramble_buf_0_M_t_empty_n );
    sensitive << ( descramble_buf_1_M_t_empty_n );

    SC_METHOD(thread_Loop_realfft_be_desc_U0_real_spectrum_hi_buf_i_0_full_n);
    sensitive << ( real_spectrum_hi_buf_i_full_n );

    SC_METHOD(thread_Loop_realfft_be_desc_U0_real_spectrum_hi_buf_i_1_full_n);
    sensitive << ( real_spectrum_hi_buf_1_i_full_n );

    SC_METHOD(thread_Loop_realfft_be_rev_U0_ap_continue);

    SC_METHOD(thread_Loop_realfft_be_rev_U0_ap_start);
    sensitive << ( real_spectrum_hi_buf_t_empty_n );
    sensitive << ( real_spectrum_hi_buf_1_t_empty_n );

    SC_METHOD(thread_Loop_realfft_be_rev_U0_start_full_n);

    SC_METHOD(thread_Loop_realfft_be_rev_U0_start_write);

    SC_METHOD(thread_Loop_realfft_be_stre_U0_ap_continue);

    SC_METHOD(thread_Loop_realfft_be_stre_U0_ap_start);
    sensitive << ( start_for_Loop_realfft_be_stre_U0_empty_n );

    SC_METHOD(thread_Loop_realfft_be_stre_U0_start_full_n);

    SC_METHOD(thread_Loop_realfft_be_stre_U0_start_write);

    SC_METHOD(thread_ap_channel_done_descramble_buf_0_M);
    sensitive << ( Loop_realfft_be_buff_U0_ap_done );
    sensitive << ( ap_sync_reg_channel_write_descramble_buf_0_M );

    SC_METHOD(thread_ap_channel_done_descramble_buf_0_M_1);
    sensitive << ( Loop_realfft_be_buff_U0_ap_done );
    sensitive << ( ap_sync_reg_channel_write_descramble_buf_0_M_1 );

    SC_METHOD(thread_ap_channel_done_descramble_buf_1_M);
    sensitive << ( Loop_realfft_be_buff_U0_ap_done );
    sensitive << ( ap_sync_reg_channel_write_descramble_buf_1_M );

    SC_METHOD(thread_ap_channel_done_descramble_buf_1_M_1);
    sensitive << ( Loop_realfft_be_buff_U0_ap_done );
    sensitive << ( ap_sync_reg_channel_write_descramble_buf_1_M_1 );

    SC_METHOD(thread_ap_channel_done_real_spectrum_hi_buf);
    sensitive << ( Loop_realfft_be_desc_U0_ap_done );
    sensitive << ( ap_sync_reg_channel_write_real_spectrum_hi_buf );

    SC_METHOD(thread_ap_channel_done_real_spectrum_hi_buf_1);
    sensitive << ( Loop_realfft_be_desc_U0_ap_done );
    sensitive << ( ap_sync_reg_channel_write_real_spectrum_hi_buf_1 );

    SC_METHOD(thread_ap_done);
    sensitive << ( Loop_realfft_be_stre_U0_ap_done );

    SC_METHOD(thread_ap_idle);
    sensitive << ( Loop_realfft_be_buff_U0_ap_idle );
    sensitive << ( Loop_realfft_be_desc_U0_ap_idle );
    sensitive << ( Loop_realfft_be_rev_U0_ap_idle );
    sensitive << ( Loop_realfft_be_stre_U0_ap_idle );
    sensitive << ( descramble_buf_0_M_1_t_empty_n );
    sensitive << ( descramble_buf_1_M_1_t_empty_n );
    sensitive << ( descramble_buf_0_M_t_empty_n );
    sensitive << ( descramble_buf_1_M_t_empty_n );
    sensitive << ( real_spectrum_hi_buf_t_empty_n );
    sensitive << ( real_spectrum_hi_buf_1_t_empty_n );

    SC_METHOD(thread_ap_ready);
    sensitive << ( Loop_realfft_be_buff_U0_ap_ready );

    SC_METHOD(thread_ap_rst_n_inv);
    sensitive << ( ap_rst_n );

    SC_METHOD(thread_ap_sync_channel_write_descramble_buf_0_M);
    sensitive << ( ap_channel_done_descramble_buf_0_M );
    sensitive << ( Loop_realfft_be_buff_U0_descramble_buf_0_M_real_V_full_n );
    sensitive << ( ap_sync_reg_channel_write_descramble_buf_0_M );

    SC_METHOD(thread_ap_sync_channel_write_descramble_buf_0_M_1);
    sensitive << ( ap_channel_done_descramble_buf_0_M_1 );
    sensitive << ( Loop_realfft_be_buff_U0_descramble_buf_0_M_imag_V_full_n );
    sensitive << ( ap_sync_reg_channel_write_descramble_buf_0_M_1 );

    SC_METHOD(thread_ap_sync_channel_write_descramble_buf_1_M);
    sensitive << ( ap_channel_done_descramble_buf_1_M );
    sensitive << ( Loop_realfft_be_buff_U0_descramble_buf_1_M_real_V_full_n );
    sensitive << ( ap_sync_reg_channel_write_descramble_buf_1_M );

    SC_METHOD(thread_ap_sync_channel_write_descramble_buf_1_M_1);
    sensitive << ( ap_channel_done_descramble_buf_1_M_1 );
    sensitive << ( Loop_realfft_be_buff_U0_descramble_buf_1_M_imag_V_full_n );
    sensitive << ( ap_sync_reg_channel_write_descramble_buf_1_M_1 );

    SC_METHOD(thread_ap_sync_channel_write_real_spectrum_hi_buf);
    sensitive << ( ap_channel_done_real_spectrum_hi_buf );
    sensitive << ( Loop_realfft_be_desc_U0_real_spectrum_hi_buf_i_0_full_n );
    sensitive << ( ap_sync_reg_channel_write_real_spectrum_hi_buf );

    SC_METHOD(thread_ap_sync_channel_write_real_spectrum_hi_buf_1);
    sensitive << ( ap_channel_done_real_spectrum_hi_buf_1 );
    sensitive << ( Loop_realfft_be_desc_U0_real_spectrum_hi_buf_i_1_full_n );
    sensitive << ( ap_sync_reg_channel_write_real_spectrum_hi_buf_1 );

    SC_METHOD(thread_ap_sync_continue);

    SC_METHOD(thread_ap_sync_done);
    sensitive << ( Loop_realfft_be_stre_U0_ap_done );

    SC_METHOD(thread_ap_sync_ready);
    sensitive << ( Loop_realfft_be_buff_U0_ap_ready );

    SC_METHOD(thread_descramble_buf_1_M_1_t_d1);

    SC_METHOD(thread_descramble_buf_1_M_1_t_we1);

    SC_METHOD(thread_descramble_buf_1_M_t_d1);

    SC_METHOD(thread_descramble_buf_1_M_t_we1);

    SC_METHOD(thread_din_TREADY);
    sensitive << ( Loop_realfft_be_buff_U0_din_TREADY );

    SC_METHOD(thread_dout_TDATA);
    sensitive << ( Loop_realfft_be_stre_U0_dout_TDATA );

    SC_METHOD(thread_dout_TLAST);
    sensitive << ( Loop_realfft_be_stre_U0_dout_TLAST );

    SC_METHOD(thread_dout_TVALID);
    sensitive << ( Loop_realfft_be_stre_U0_dout_TVALID );

    SC_METHOD(thread_start_for_Loop_realfft_be_stre_U0_din);

    SC_THREAD(thread_hdltv_gen);
    sensitive << ( ap_clk.pos() );

    SC_THREAD(thread_ap_var_for_const2);

    SC_THREAD(thread_ap_var_for_const0);

    SC_THREAD(thread_ap_var_for_const1);

    SC_THREAD(thread_ap_var_for_const3);

    ap_sync_reg_channel_write_descramble_buf_1_M = SC_LOGIC_0;
    ap_sync_reg_channel_write_descramble_buf_0_M = SC_LOGIC_0;
    ap_sync_reg_channel_write_descramble_buf_1_M_1 = SC_LOGIC_0;
    ap_sync_reg_channel_write_descramble_buf_0_M_1 = SC_LOGIC_0;
    ap_sync_reg_channel_write_real_spectrum_hi_buf_1 = SC_LOGIC_0;
    ap_sync_reg_channel_write_real_spectrum_hi_buf = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "hls_xfft2real_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst_n, "(port)ap_rst_n");
    sc_trace(mVcdFile, din_TDATA, "(port)din_TDATA");
    sc_trace(mVcdFile, din_TLAST, "(port)din_TLAST");
    sc_trace(mVcdFile, dout_TDATA, "(port)dout_TDATA");
    sc_trace(mVcdFile, dout_TLAST, "(port)dout_TLAST");
    sc_trace(mVcdFile, din_TVALID, "(port)din_TVALID");
    sc_trace(mVcdFile, din_TREADY, "(port)din_TREADY");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, dout_TVALID, "(port)dout_TVALID");
    sc_trace(mVcdFile, dout_TREADY, "(port)dout_TREADY");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_rst_n_inv, "ap_rst_n_inv");
    sc_trace(mVcdFile, descramble_buf_0_M_i_q0, "descramble_buf_0_M_i_q0");
    sc_trace(mVcdFile, descramble_buf_0_M_t_q0, "descramble_buf_0_M_t_q0");
    sc_trace(mVcdFile, descramble_buf_1_M_i_q0, "descramble_buf_1_M_i_q0");
    sc_trace(mVcdFile, descramble_buf_1_M_i_q1, "descramble_buf_1_M_i_q1");
    sc_trace(mVcdFile, descramble_buf_1_M_t_q0, "descramble_buf_1_M_t_q0");
    sc_trace(mVcdFile, descramble_buf_1_M_t_q1, "descramble_buf_1_M_t_q1");
    sc_trace(mVcdFile, descramble_buf_0_M_1_i_q0, "descramble_buf_0_M_1_i_q0");
    sc_trace(mVcdFile, descramble_buf_0_M_1_t_q0, "descramble_buf_0_M_1_t_q0");
    sc_trace(mVcdFile, descramble_buf_1_M_1_i_q0, "descramble_buf_1_M_1_i_q0");
    sc_trace(mVcdFile, descramble_buf_1_M_1_i_q1, "descramble_buf_1_M_1_i_q1");
    sc_trace(mVcdFile, descramble_buf_1_M_1_t_q0, "descramble_buf_1_M_1_t_q0");
    sc_trace(mVcdFile, descramble_buf_1_M_1_t_q1, "descramble_buf_1_M_1_t_q1");
    sc_trace(mVcdFile, real_spectrum_hi_buf_i_q0, "real_spectrum_hi_buf_i_q0");
    sc_trace(mVcdFile, real_spectrum_hi_buf_t_q0, "real_spectrum_hi_buf_t_q0");
    sc_trace(mVcdFile, real_spectrum_hi_buf_1_i_q0, "real_spectrum_hi_buf_1_i_q0");
    sc_trace(mVcdFile, real_spectrum_hi_buf_1_t_q0, "real_spectrum_hi_buf_1_t_q0");
    sc_trace(mVcdFile, Loop_realfft_be_buff_U0_ap_start, "Loop_realfft_be_buff_U0_ap_start");
    sc_trace(mVcdFile, Loop_realfft_be_buff_U0_ap_done, "Loop_realfft_be_buff_U0_ap_done");
    sc_trace(mVcdFile, Loop_realfft_be_buff_U0_ap_continue, "Loop_realfft_be_buff_U0_ap_continue");
    sc_trace(mVcdFile, Loop_realfft_be_buff_U0_ap_idle, "Loop_realfft_be_buff_U0_ap_idle");
    sc_trace(mVcdFile, Loop_realfft_be_buff_U0_ap_ready, "Loop_realfft_be_buff_U0_ap_ready");
    sc_trace(mVcdFile, Loop_realfft_be_buff_U0_descramble_buf_0_M_imag_V_address0, "Loop_realfft_be_buff_U0_descramble_buf_0_M_imag_V_address0");
    sc_trace(mVcdFile, Loop_realfft_be_buff_U0_descramble_buf_0_M_imag_V_ce0, "Loop_realfft_be_buff_U0_descramble_buf_0_M_imag_V_ce0");
    sc_trace(mVcdFile, Loop_realfft_be_buff_U0_descramble_buf_0_M_imag_V_we0, "Loop_realfft_be_buff_U0_descramble_buf_0_M_imag_V_we0");
    sc_trace(mVcdFile, Loop_realfft_be_buff_U0_descramble_buf_0_M_imag_V_d0, "Loop_realfft_be_buff_U0_descramble_buf_0_M_imag_V_d0");
    sc_trace(mVcdFile, Loop_realfft_be_buff_U0_descramble_buf_1_M_imag_V_address0, "Loop_realfft_be_buff_U0_descramble_buf_1_M_imag_V_address0");
    sc_trace(mVcdFile, Loop_realfft_be_buff_U0_descramble_buf_1_M_imag_V_ce0, "Loop_realfft_be_buff_U0_descramble_buf_1_M_imag_V_ce0");
    sc_trace(mVcdFile, Loop_realfft_be_buff_U0_descramble_buf_1_M_imag_V_we0, "Loop_realfft_be_buff_U0_descramble_buf_1_M_imag_V_we0");
    sc_trace(mVcdFile, Loop_realfft_be_buff_U0_descramble_buf_1_M_imag_V_d0, "Loop_realfft_be_buff_U0_descramble_buf_1_M_imag_V_d0");
    sc_trace(mVcdFile, Loop_realfft_be_buff_U0_din_TREADY, "Loop_realfft_be_buff_U0_din_TREADY");
    sc_trace(mVcdFile, Loop_realfft_be_buff_U0_descramble_buf_0_M_real_V_address0, "Loop_realfft_be_buff_U0_descramble_buf_0_M_real_V_address0");
    sc_trace(mVcdFile, Loop_realfft_be_buff_U0_descramble_buf_0_M_real_V_ce0, "Loop_realfft_be_buff_U0_descramble_buf_0_M_real_V_ce0");
    sc_trace(mVcdFile, Loop_realfft_be_buff_U0_descramble_buf_0_M_real_V_we0, "Loop_realfft_be_buff_U0_descramble_buf_0_M_real_V_we0");
    sc_trace(mVcdFile, Loop_realfft_be_buff_U0_descramble_buf_0_M_real_V_d0, "Loop_realfft_be_buff_U0_descramble_buf_0_M_real_V_d0");
    sc_trace(mVcdFile, Loop_realfft_be_buff_U0_descramble_buf_1_M_real_V_address0, "Loop_realfft_be_buff_U0_descramble_buf_1_M_real_V_address0");
    sc_trace(mVcdFile, Loop_realfft_be_buff_U0_descramble_buf_1_M_real_V_ce0, "Loop_realfft_be_buff_U0_descramble_buf_1_M_real_V_ce0");
    sc_trace(mVcdFile, Loop_realfft_be_buff_U0_descramble_buf_1_M_real_V_we0, "Loop_realfft_be_buff_U0_descramble_buf_1_M_real_V_we0");
    sc_trace(mVcdFile, Loop_realfft_be_buff_U0_descramble_buf_1_M_real_V_d0, "Loop_realfft_be_buff_U0_descramble_buf_1_M_real_V_d0");
    sc_trace(mVcdFile, ap_channel_done_descramble_buf_1_M, "ap_channel_done_descramble_buf_1_M");
    sc_trace(mVcdFile, Loop_realfft_be_buff_U0_descramble_buf_1_M_real_V_full_n, "Loop_realfft_be_buff_U0_descramble_buf_1_M_real_V_full_n");
    sc_trace(mVcdFile, ap_sync_reg_channel_write_descramble_buf_1_M, "ap_sync_reg_channel_write_descramble_buf_1_M");
    sc_trace(mVcdFile, ap_sync_channel_write_descramble_buf_1_M, "ap_sync_channel_write_descramble_buf_1_M");
    sc_trace(mVcdFile, ap_channel_done_descramble_buf_0_M, "ap_channel_done_descramble_buf_0_M");
    sc_trace(mVcdFile, Loop_realfft_be_buff_U0_descramble_buf_0_M_real_V_full_n, "Loop_realfft_be_buff_U0_descramble_buf_0_M_real_V_full_n");
    sc_trace(mVcdFile, ap_sync_reg_channel_write_descramble_buf_0_M, "ap_sync_reg_channel_write_descramble_buf_0_M");
    sc_trace(mVcdFile, ap_sync_channel_write_descramble_buf_0_M, "ap_sync_channel_write_descramble_buf_0_M");
    sc_trace(mVcdFile, ap_channel_done_descramble_buf_1_M_1, "ap_channel_done_descramble_buf_1_M_1");
    sc_trace(mVcdFile, Loop_realfft_be_buff_U0_descramble_buf_1_M_imag_V_full_n, "Loop_realfft_be_buff_U0_descramble_buf_1_M_imag_V_full_n");
    sc_trace(mVcdFile, ap_sync_reg_channel_write_descramble_buf_1_M_1, "ap_sync_reg_channel_write_descramble_buf_1_M_1");
    sc_trace(mVcdFile, ap_sync_channel_write_descramble_buf_1_M_1, "ap_sync_channel_write_descramble_buf_1_M_1");
    sc_trace(mVcdFile, ap_channel_done_descramble_buf_0_M_1, "ap_channel_done_descramble_buf_0_M_1");
    sc_trace(mVcdFile, Loop_realfft_be_buff_U0_descramble_buf_0_M_imag_V_full_n, "Loop_realfft_be_buff_U0_descramble_buf_0_M_imag_V_full_n");
    sc_trace(mVcdFile, ap_sync_reg_channel_write_descramble_buf_0_M_1, "ap_sync_reg_channel_write_descramble_buf_0_M_1");
    sc_trace(mVcdFile, ap_sync_channel_write_descramble_buf_0_M_1, "ap_sync_channel_write_descramble_buf_0_M_1");
    sc_trace(mVcdFile, Loop_realfft_be_desc_U0_ap_start, "Loop_realfft_be_desc_U0_ap_start");
    sc_trace(mVcdFile, Loop_realfft_be_desc_U0_ap_done, "Loop_realfft_be_desc_U0_ap_done");
    sc_trace(mVcdFile, Loop_realfft_be_desc_U0_ap_continue, "Loop_realfft_be_desc_U0_ap_continue");
    sc_trace(mVcdFile, Loop_realfft_be_desc_U0_ap_idle, "Loop_realfft_be_desc_U0_ap_idle");
    sc_trace(mVcdFile, Loop_realfft_be_desc_U0_ap_ready, "Loop_realfft_be_desc_U0_ap_ready");
    sc_trace(mVcdFile, Loop_realfft_be_desc_U0_start_out, "Loop_realfft_be_desc_U0_start_out");
    sc_trace(mVcdFile, Loop_realfft_be_desc_U0_start_write, "Loop_realfft_be_desc_U0_start_write");
    sc_trace(mVcdFile, Loop_realfft_be_desc_U0_real_spectrum_lo_V_M_real_V_din, "Loop_realfft_be_desc_U0_real_spectrum_lo_V_M_real_V_din");
    sc_trace(mVcdFile, Loop_realfft_be_desc_U0_real_spectrum_lo_V_M_real_V_write, "Loop_realfft_be_desc_U0_real_spectrum_lo_V_M_real_V_write");
    sc_trace(mVcdFile, Loop_realfft_be_desc_U0_real_spectrum_lo_V_M_imag_V_din, "Loop_realfft_be_desc_U0_real_spectrum_lo_V_M_imag_V_din");
    sc_trace(mVcdFile, Loop_realfft_be_desc_U0_real_spectrum_lo_V_M_imag_V_write, "Loop_realfft_be_desc_U0_real_spectrum_lo_V_M_imag_V_write");
    sc_trace(mVcdFile, Loop_realfft_be_desc_U0_real_spectrum_hi_buf_i_0_address0, "Loop_realfft_be_desc_U0_real_spectrum_hi_buf_i_0_address0");
    sc_trace(mVcdFile, Loop_realfft_be_desc_U0_real_spectrum_hi_buf_i_0_ce0, "Loop_realfft_be_desc_U0_real_spectrum_hi_buf_i_0_ce0");
    sc_trace(mVcdFile, Loop_realfft_be_desc_U0_real_spectrum_hi_buf_i_0_we0, "Loop_realfft_be_desc_U0_real_spectrum_hi_buf_i_0_we0");
    sc_trace(mVcdFile, Loop_realfft_be_desc_U0_real_spectrum_hi_buf_i_0_d0, "Loop_realfft_be_desc_U0_real_spectrum_hi_buf_i_0_d0");
    sc_trace(mVcdFile, Loop_realfft_be_desc_U0_real_spectrum_hi_buf_i_1_address0, "Loop_realfft_be_desc_U0_real_spectrum_hi_buf_i_1_address0");
    sc_trace(mVcdFile, Loop_realfft_be_desc_U0_real_spectrum_hi_buf_i_1_ce0, "Loop_realfft_be_desc_U0_real_spectrum_hi_buf_i_1_ce0");
    sc_trace(mVcdFile, Loop_realfft_be_desc_U0_real_spectrum_hi_buf_i_1_we0, "Loop_realfft_be_desc_U0_real_spectrum_hi_buf_i_1_we0");
    sc_trace(mVcdFile, Loop_realfft_be_desc_U0_real_spectrum_hi_buf_i_1_d0, "Loop_realfft_be_desc_U0_real_spectrum_hi_buf_i_1_d0");
    sc_trace(mVcdFile, Loop_realfft_be_desc_U0_descramble_buf_1_M_real_V_address0, "Loop_realfft_be_desc_U0_descramble_buf_1_M_real_V_address0");
    sc_trace(mVcdFile, Loop_realfft_be_desc_U0_descramble_buf_1_M_real_V_ce0, "Loop_realfft_be_desc_U0_descramble_buf_1_M_real_V_ce0");
    sc_trace(mVcdFile, Loop_realfft_be_desc_U0_descramble_buf_1_M_real_V_address1, "Loop_realfft_be_desc_U0_descramble_buf_1_M_real_V_address1");
    sc_trace(mVcdFile, Loop_realfft_be_desc_U0_descramble_buf_1_M_real_V_ce1, "Loop_realfft_be_desc_U0_descramble_buf_1_M_real_V_ce1");
    sc_trace(mVcdFile, Loop_realfft_be_desc_U0_descramble_buf_1_M_imag_V_address0, "Loop_realfft_be_desc_U0_descramble_buf_1_M_imag_V_address0");
    sc_trace(mVcdFile, Loop_realfft_be_desc_U0_descramble_buf_1_M_imag_V_ce0, "Loop_realfft_be_desc_U0_descramble_buf_1_M_imag_V_ce0");
    sc_trace(mVcdFile, Loop_realfft_be_desc_U0_descramble_buf_1_M_imag_V_address1, "Loop_realfft_be_desc_U0_descramble_buf_1_M_imag_V_address1");
    sc_trace(mVcdFile, Loop_realfft_be_desc_U0_descramble_buf_1_M_imag_V_ce1, "Loop_realfft_be_desc_U0_descramble_buf_1_M_imag_V_ce1");
    sc_trace(mVcdFile, Loop_realfft_be_desc_U0_descramble_buf_0_M_real_V_address0, "Loop_realfft_be_desc_U0_descramble_buf_0_M_real_V_address0");
    sc_trace(mVcdFile, Loop_realfft_be_desc_U0_descramble_buf_0_M_real_V_ce0, "Loop_realfft_be_desc_U0_descramble_buf_0_M_real_V_ce0");
    sc_trace(mVcdFile, Loop_realfft_be_desc_U0_descramble_buf_0_M_imag_V_address0, "Loop_realfft_be_desc_U0_descramble_buf_0_M_imag_V_address0");
    sc_trace(mVcdFile, Loop_realfft_be_desc_U0_descramble_buf_0_M_imag_V_ce0, "Loop_realfft_be_desc_U0_descramble_buf_0_M_imag_V_ce0");
    sc_trace(mVcdFile, ap_channel_done_real_spectrum_hi_buf_1, "ap_channel_done_real_spectrum_hi_buf_1");
    sc_trace(mVcdFile, Loop_realfft_be_desc_U0_real_spectrum_hi_buf_i_1_full_n, "Loop_realfft_be_desc_U0_real_spectrum_hi_buf_i_1_full_n");
    sc_trace(mVcdFile, ap_sync_reg_channel_write_real_spectrum_hi_buf_1, "ap_sync_reg_channel_write_real_spectrum_hi_buf_1");
    sc_trace(mVcdFile, ap_sync_channel_write_real_spectrum_hi_buf_1, "ap_sync_channel_write_real_spectrum_hi_buf_1");
    sc_trace(mVcdFile, ap_channel_done_real_spectrum_hi_buf, "ap_channel_done_real_spectrum_hi_buf");
    sc_trace(mVcdFile, Loop_realfft_be_desc_U0_real_spectrum_hi_buf_i_0_full_n, "Loop_realfft_be_desc_U0_real_spectrum_hi_buf_i_0_full_n");
    sc_trace(mVcdFile, ap_sync_reg_channel_write_real_spectrum_hi_buf, "ap_sync_reg_channel_write_real_spectrum_hi_buf");
    sc_trace(mVcdFile, ap_sync_channel_write_real_spectrum_hi_buf, "ap_sync_channel_write_real_spectrum_hi_buf");
    sc_trace(mVcdFile, Loop_realfft_be_rev_U0_ap_start, "Loop_realfft_be_rev_U0_ap_start");
    sc_trace(mVcdFile, Loop_realfft_be_rev_U0_ap_done, "Loop_realfft_be_rev_U0_ap_done");
    sc_trace(mVcdFile, Loop_realfft_be_rev_U0_ap_continue, "Loop_realfft_be_rev_U0_ap_continue");
    sc_trace(mVcdFile, Loop_realfft_be_rev_U0_ap_idle, "Loop_realfft_be_rev_U0_ap_idle");
    sc_trace(mVcdFile, Loop_realfft_be_rev_U0_ap_ready, "Loop_realfft_be_rev_U0_ap_ready");
    sc_trace(mVcdFile, Loop_realfft_be_rev_U0_real_spectrum_hi_buf_i_0_address0, "Loop_realfft_be_rev_U0_real_spectrum_hi_buf_i_0_address0");
    sc_trace(mVcdFile, Loop_realfft_be_rev_U0_real_spectrum_hi_buf_i_0_ce0, "Loop_realfft_be_rev_U0_real_spectrum_hi_buf_i_0_ce0");
    sc_trace(mVcdFile, Loop_realfft_be_rev_U0_real_spectrum_hi_buf_i_1_address0, "Loop_realfft_be_rev_U0_real_spectrum_hi_buf_i_1_address0");
    sc_trace(mVcdFile, Loop_realfft_be_rev_U0_real_spectrum_hi_buf_i_1_ce0, "Loop_realfft_be_rev_U0_real_spectrum_hi_buf_i_1_ce0");
    sc_trace(mVcdFile, Loop_realfft_be_rev_U0_real_spectrum_hi_V_M_real_V_din, "Loop_realfft_be_rev_U0_real_spectrum_hi_V_M_real_V_din");
    sc_trace(mVcdFile, Loop_realfft_be_rev_U0_real_spectrum_hi_V_M_real_V_write, "Loop_realfft_be_rev_U0_real_spectrum_hi_V_M_real_V_write");
    sc_trace(mVcdFile, Loop_realfft_be_rev_U0_real_spectrum_hi_V_M_imag_V_din, "Loop_realfft_be_rev_U0_real_spectrum_hi_V_M_imag_V_din");
    sc_trace(mVcdFile, Loop_realfft_be_rev_U0_real_spectrum_hi_V_M_imag_V_write, "Loop_realfft_be_rev_U0_real_spectrum_hi_V_M_imag_V_write");
    sc_trace(mVcdFile, Loop_realfft_be_stre_U0_ap_start, "Loop_realfft_be_stre_U0_ap_start");
    sc_trace(mVcdFile, Loop_realfft_be_stre_U0_ap_done, "Loop_realfft_be_stre_U0_ap_done");
    sc_trace(mVcdFile, Loop_realfft_be_stre_U0_ap_continue, "Loop_realfft_be_stre_U0_ap_continue");
    sc_trace(mVcdFile, Loop_realfft_be_stre_U0_ap_idle, "Loop_realfft_be_stre_U0_ap_idle");
    sc_trace(mVcdFile, Loop_realfft_be_stre_U0_ap_ready, "Loop_realfft_be_stre_U0_ap_ready");
    sc_trace(mVcdFile, Loop_realfft_be_stre_U0_real_spectrum_lo_V_M_real_V_read, "Loop_realfft_be_stre_U0_real_spectrum_lo_V_M_real_V_read");
    sc_trace(mVcdFile, Loop_realfft_be_stre_U0_real_spectrum_lo_V_M_imag_V_read, "Loop_realfft_be_stre_U0_real_spectrum_lo_V_M_imag_V_read");
    sc_trace(mVcdFile, Loop_realfft_be_stre_U0_real_spectrum_hi_V_M_real_V_read, "Loop_realfft_be_stre_U0_real_spectrum_hi_V_M_real_V_read");
    sc_trace(mVcdFile, Loop_realfft_be_stre_U0_real_spectrum_hi_V_M_imag_V_read, "Loop_realfft_be_stre_U0_real_spectrum_hi_V_M_imag_V_read");
    sc_trace(mVcdFile, Loop_realfft_be_stre_U0_dout_TDATA, "Loop_realfft_be_stre_U0_dout_TDATA");
    sc_trace(mVcdFile, Loop_realfft_be_stre_U0_dout_TVALID, "Loop_realfft_be_stre_U0_dout_TVALID");
    sc_trace(mVcdFile, Loop_realfft_be_stre_U0_dout_TLAST, "Loop_realfft_be_stre_U0_dout_TLAST");
    sc_trace(mVcdFile, ap_sync_continue, "ap_sync_continue");
    sc_trace(mVcdFile, descramble_buf_0_M_1_i_full_n, "descramble_buf_0_M_1_i_full_n");
    sc_trace(mVcdFile, descramble_buf_0_M_1_t_empty_n, "descramble_buf_0_M_1_t_empty_n");
    sc_trace(mVcdFile, descramble_buf_1_M_1_i_full_n, "descramble_buf_1_M_1_i_full_n");
    sc_trace(mVcdFile, descramble_buf_1_M_1_t_empty_n, "descramble_buf_1_M_1_t_empty_n");
    sc_trace(mVcdFile, descramble_buf_1_M_1_t_d1, "descramble_buf_1_M_1_t_d1");
    sc_trace(mVcdFile, descramble_buf_1_M_1_t_we1, "descramble_buf_1_M_1_t_we1");
    sc_trace(mVcdFile, descramble_buf_0_M_i_full_n, "descramble_buf_0_M_i_full_n");
    sc_trace(mVcdFile, descramble_buf_0_M_t_empty_n, "descramble_buf_0_M_t_empty_n");
    sc_trace(mVcdFile, descramble_buf_1_M_i_full_n, "descramble_buf_1_M_i_full_n");
    sc_trace(mVcdFile, descramble_buf_1_M_t_empty_n, "descramble_buf_1_M_t_empty_n");
    sc_trace(mVcdFile, descramble_buf_1_M_t_d1, "descramble_buf_1_M_t_d1");
    sc_trace(mVcdFile, descramble_buf_1_M_t_we1, "descramble_buf_1_M_t_we1");
    sc_trace(mVcdFile, real_spectrum_hi_buf_i_full_n, "real_spectrum_hi_buf_i_full_n");
    sc_trace(mVcdFile, real_spectrum_hi_buf_t_empty_n, "real_spectrum_hi_buf_t_empty_n");
    sc_trace(mVcdFile, real_spectrum_hi_buf_1_i_full_n, "real_spectrum_hi_buf_1_i_full_n");
    sc_trace(mVcdFile, real_spectrum_hi_buf_1_t_empty_n, "real_spectrum_hi_buf_1_t_empty_n");
    sc_trace(mVcdFile, real_spectrum_lo_V_s_full_n, "real_spectrum_lo_V_s_full_n");
    sc_trace(mVcdFile, real_spectrum_lo_V_s_dout, "real_spectrum_lo_V_s_dout");
    sc_trace(mVcdFile, real_spectrum_lo_V_s_empty_n, "real_spectrum_lo_V_s_empty_n");
    sc_trace(mVcdFile, real_spectrum_lo_V_1_full_n, "real_spectrum_lo_V_1_full_n");
    sc_trace(mVcdFile, real_spectrum_lo_V_1_dout, "real_spectrum_lo_V_1_dout");
    sc_trace(mVcdFile, real_spectrum_lo_V_1_empty_n, "real_spectrum_lo_V_1_empty_n");
    sc_trace(mVcdFile, real_spectrum_hi_V_s_full_n, "real_spectrum_hi_V_s_full_n");
    sc_trace(mVcdFile, real_spectrum_hi_V_s_dout, "real_spectrum_hi_V_s_dout");
    sc_trace(mVcdFile, real_spectrum_hi_V_s_empty_n, "real_spectrum_hi_V_s_empty_n");
    sc_trace(mVcdFile, real_spectrum_hi_V_1_full_n, "real_spectrum_hi_V_1_full_n");
    sc_trace(mVcdFile, real_spectrum_hi_V_1_dout, "real_spectrum_hi_V_1_dout");
    sc_trace(mVcdFile, real_spectrum_hi_V_1_empty_n, "real_spectrum_hi_V_1_empty_n");
    sc_trace(mVcdFile, ap_sync_done, "ap_sync_done");
    sc_trace(mVcdFile, ap_sync_ready, "ap_sync_ready");
    sc_trace(mVcdFile, Loop_realfft_be_buff_U0_start_full_n, "Loop_realfft_be_buff_U0_start_full_n");
    sc_trace(mVcdFile, Loop_realfft_be_buff_U0_start_write, "Loop_realfft_be_buff_U0_start_write");
    sc_trace(mVcdFile, start_for_Loop_realfft_be_stre_U0_din, "start_for_Loop_realfft_be_stre_U0_din");
    sc_trace(mVcdFile, start_for_Loop_realfft_be_stre_U0_full_n, "start_for_Loop_realfft_be_stre_U0_full_n");
    sc_trace(mVcdFile, start_for_Loop_realfft_be_stre_U0_dout, "start_for_Loop_realfft_be_stre_U0_dout");
    sc_trace(mVcdFile, start_for_Loop_realfft_be_stre_U0_empty_n, "start_for_Loop_realfft_be_stre_U0_empty_n");
    sc_trace(mVcdFile, Loop_realfft_be_rev_U0_start_full_n, "Loop_realfft_be_rev_U0_start_full_n");
    sc_trace(mVcdFile, Loop_realfft_be_rev_U0_start_write, "Loop_realfft_be_rev_U0_start_write");
    sc_trace(mVcdFile, Loop_realfft_be_stre_U0_start_full_n, "Loop_realfft_be_stre_U0_start_full_n");
    sc_trace(mVcdFile, Loop_realfft_be_stre_U0_start_write, "Loop_realfft_be_stre_U0_start_write");
#endif

    }
    mHdltvinHandle.open("hls_xfft2real.hdltvin.dat");
    mHdltvoutHandle.open("hls_xfft2real.hdltvout.dat");
}

hls_xfft2real::~hls_xfft2real() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    mHdltvinHandle << "] " << endl;
    mHdltvoutHandle << "] " << endl;
    mHdltvinHandle.close();
    mHdltvoutHandle.close();
    delete descramble_buf_0_M_U;
    delete descramble_buf_1_M_U;
    delete descramble_buf_0_M_1_U;
    delete descramble_buf_1_M_1_U;
    delete real_spectrum_hi_buf_U;
    delete real_spectrum_hi_buf_1_U;
    delete Loop_realfft_be_buff_U0;
    delete Loop_realfft_be_desc_U0;
    delete Loop_realfft_be_rev_U0;
    delete Loop_realfft_be_stre_U0;
    delete real_spectrum_lo_V_s_U;
    delete real_spectrum_lo_V_1_U;
    delete real_spectrum_hi_V_s_U;
    delete real_spectrum_hi_V_1_U;
    delete start_for_Loop_rencg_U;
}

void hls_xfft2real::thread_ap_var_for_const2() {
    ap_var_for_const2 = ap_const_logic_1;
}

void hls_xfft2real::thread_ap_var_for_const0() {
    ap_var_for_const0 = ap_const_logic_0;
}

void hls_xfft2real::thread_ap_var_for_const1() {
    ap_var_for_const1 = ap_const_lv16_0;
}

void hls_xfft2real::thread_ap_var_for_const3() {
    ap_var_for_const3 = ap_const_lv8_0;
}

void hls_xfft2real::thread_ap_clk_no_reset_() {
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        ap_sync_reg_channel_write_descramble_buf_0_M = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, (Loop_realfft_be_buff_U0_ap_done.read() & 
             Loop_realfft_be_buff_U0_ap_continue.read()))) {
            ap_sync_reg_channel_write_descramble_buf_0_M = ap_const_logic_0;
        } else {
            ap_sync_reg_channel_write_descramble_buf_0_M = ap_sync_channel_write_descramble_buf_0_M.read();
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        ap_sync_reg_channel_write_descramble_buf_0_M_1 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, (Loop_realfft_be_buff_U0_ap_done.read() & 
             Loop_realfft_be_buff_U0_ap_continue.read()))) {
            ap_sync_reg_channel_write_descramble_buf_0_M_1 = ap_const_logic_0;
        } else {
            ap_sync_reg_channel_write_descramble_buf_0_M_1 = ap_sync_channel_write_descramble_buf_0_M_1.read();
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        ap_sync_reg_channel_write_descramble_buf_1_M = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, (Loop_realfft_be_buff_U0_ap_done.read() & 
             Loop_realfft_be_buff_U0_ap_continue.read()))) {
            ap_sync_reg_channel_write_descramble_buf_1_M = ap_const_logic_0;
        } else {
            ap_sync_reg_channel_write_descramble_buf_1_M = ap_sync_channel_write_descramble_buf_1_M.read();
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        ap_sync_reg_channel_write_descramble_buf_1_M_1 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, (Loop_realfft_be_buff_U0_ap_done.read() & 
             Loop_realfft_be_buff_U0_ap_continue.read()))) {
            ap_sync_reg_channel_write_descramble_buf_1_M_1 = ap_const_logic_0;
        } else {
            ap_sync_reg_channel_write_descramble_buf_1_M_1 = ap_sync_channel_write_descramble_buf_1_M_1.read();
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        ap_sync_reg_channel_write_real_spectrum_hi_buf = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, (Loop_realfft_be_desc_U0_ap_done.read() & 
             Loop_realfft_be_desc_U0_ap_continue.read()))) {
            ap_sync_reg_channel_write_real_spectrum_hi_buf = ap_const_logic_0;
        } else {
            ap_sync_reg_channel_write_real_spectrum_hi_buf = ap_sync_channel_write_real_spectrum_hi_buf.read();
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        ap_sync_reg_channel_write_real_spectrum_hi_buf_1 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, (Loop_realfft_be_desc_U0_ap_done.read() & 
             Loop_realfft_be_desc_U0_ap_continue.read()))) {
            ap_sync_reg_channel_write_real_spectrum_hi_buf_1 = ap_const_logic_0;
        } else {
            ap_sync_reg_channel_write_real_spectrum_hi_buf_1 = ap_sync_channel_write_real_spectrum_hi_buf_1.read();
        }
    }
}

void hls_xfft2real::thread_Loop_realfft_be_buff_U0_ap_continue() {
    Loop_realfft_be_buff_U0_ap_continue = (ap_sync_channel_write_descramble_buf_1_M.read() & ap_sync_channel_write_descramble_buf_0_M.read() & ap_sync_channel_write_descramble_buf_1_M_1.read() & ap_sync_channel_write_descramble_buf_0_M_1.read());
}

void hls_xfft2real::thread_Loop_realfft_be_buff_U0_ap_start() {
    Loop_realfft_be_buff_U0_ap_start = ap_start.read();
}

void hls_xfft2real::thread_Loop_realfft_be_buff_U0_descramble_buf_0_M_imag_V_full_n() {
    Loop_realfft_be_buff_U0_descramble_buf_0_M_imag_V_full_n = descramble_buf_0_M_1_i_full_n.read();
}

void hls_xfft2real::thread_Loop_realfft_be_buff_U0_descramble_buf_0_M_real_V_full_n() {
    Loop_realfft_be_buff_U0_descramble_buf_0_M_real_V_full_n = descramble_buf_0_M_i_full_n.read();
}

void hls_xfft2real::thread_Loop_realfft_be_buff_U0_descramble_buf_1_M_imag_V_full_n() {
    Loop_realfft_be_buff_U0_descramble_buf_1_M_imag_V_full_n = descramble_buf_1_M_1_i_full_n.read();
}

void hls_xfft2real::thread_Loop_realfft_be_buff_U0_descramble_buf_1_M_real_V_full_n() {
    Loop_realfft_be_buff_U0_descramble_buf_1_M_real_V_full_n = descramble_buf_1_M_i_full_n.read();
}

void hls_xfft2real::thread_Loop_realfft_be_buff_U0_start_full_n() {
    Loop_realfft_be_buff_U0_start_full_n = ap_const_logic_1;
}

void hls_xfft2real::thread_Loop_realfft_be_buff_U0_start_write() {
    Loop_realfft_be_buff_U0_start_write = ap_const_logic_0;
}

void hls_xfft2real::thread_Loop_realfft_be_desc_U0_ap_continue() {
    Loop_realfft_be_desc_U0_ap_continue = (ap_sync_channel_write_real_spectrum_hi_buf_1.read() & ap_sync_channel_write_real_spectrum_hi_buf.read());
}

void hls_xfft2real::thread_Loop_realfft_be_desc_U0_ap_start() {
    Loop_realfft_be_desc_U0_ap_start = (descramble_buf_0_M_1_t_empty_n.read() & descramble_buf_1_M_1_t_empty_n.read() & descramble_buf_0_M_t_empty_n.read() & descramble_buf_1_M_t_empty_n.read());
}

void hls_xfft2real::thread_Loop_realfft_be_desc_U0_real_spectrum_hi_buf_i_0_full_n() {
    Loop_realfft_be_desc_U0_real_spectrum_hi_buf_i_0_full_n = real_spectrum_hi_buf_i_full_n.read();
}

void hls_xfft2real::thread_Loop_realfft_be_desc_U0_real_spectrum_hi_buf_i_1_full_n() {
    Loop_realfft_be_desc_U0_real_spectrum_hi_buf_i_1_full_n = real_spectrum_hi_buf_1_i_full_n.read();
}

void hls_xfft2real::thread_Loop_realfft_be_rev_U0_ap_continue() {
    Loop_realfft_be_rev_U0_ap_continue = ap_const_logic_1;
}

void hls_xfft2real::thread_Loop_realfft_be_rev_U0_ap_start() {
    Loop_realfft_be_rev_U0_ap_start = (real_spectrum_hi_buf_t_empty_n.read() & real_spectrum_hi_buf_1_t_empty_n.read());
}

void hls_xfft2real::thread_Loop_realfft_be_rev_U0_start_full_n() {
    Loop_realfft_be_rev_U0_start_full_n = ap_const_logic_1;
}

void hls_xfft2real::thread_Loop_realfft_be_rev_U0_start_write() {
    Loop_realfft_be_rev_U0_start_write = ap_const_logic_0;
}

void hls_xfft2real::thread_Loop_realfft_be_stre_U0_ap_continue() {
    Loop_realfft_be_stre_U0_ap_continue = ap_const_logic_1;
}

void hls_xfft2real::thread_Loop_realfft_be_stre_U0_ap_start() {
    Loop_realfft_be_stre_U0_ap_start = start_for_Loop_realfft_be_stre_U0_empty_n.read();
}

void hls_xfft2real::thread_Loop_realfft_be_stre_U0_start_full_n() {
    Loop_realfft_be_stre_U0_start_full_n = ap_const_logic_1;
}

void hls_xfft2real::thread_Loop_realfft_be_stre_U0_start_write() {
    Loop_realfft_be_stre_U0_start_write = ap_const_logic_0;
}

void hls_xfft2real::thread_ap_channel_done_descramble_buf_0_M() {
    ap_channel_done_descramble_buf_0_M = (Loop_realfft_be_buff_U0_ap_done.read() & (ap_sync_reg_channel_write_descramble_buf_0_M.read() ^ 
  ap_const_logic_1));
}

void hls_xfft2real::thread_ap_channel_done_descramble_buf_0_M_1() {
    ap_channel_done_descramble_buf_0_M_1 = (Loop_realfft_be_buff_U0_ap_done.read() & (ap_sync_reg_channel_write_descramble_buf_0_M_1.read() ^ 
  ap_const_logic_1));
}

void hls_xfft2real::thread_ap_channel_done_descramble_buf_1_M() {
    ap_channel_done_descramble_buf_1_M = (Loop_realfft_be_buff_U0_ap_done.read() & (ap_sync_reg_channel_write_descramble_buf_1_M.read() ^ 
  ap_const_logic_1));
}

void hls_xfft2real::thread_ap_channel_done_descramble_buf_1_M_1() {
    ap_channel_done_descramble_buf_1_M_1 = (Loop_realfft_be_buff_U0_ap_done.read() & (ap_sync_reg_channel_write_descramble_buf_1_M_1.read() ^ 
  ap_const_logic_1));
}

void hls_xfft2real::thread_ap_channel_done_real_spectrum_hi_buf() {
    ap_channel_done_real_spectrum_hi_buf = (Loop_realfft_be_desc_U0_ap_done.read() & (ap_sync_reg_channel_write_real_spectrum_hi_buf.read() ^ 
  ap_const_logic_1));
}

void hls_xfft2real::thread_ap_channel_done_real_spectrum_hi_buf_1() {
    ap_channel_done_real_spectrum_hi_buf_1 = (Loop_realfft_be_desc_U0_ap_done.read() & (ap_sync_reg_channel_write_real_spectrum_hi_buf_1.read() ^ 
  ap_const_logic_1));
}

void hls_xfft2real::thread_ap_done() {
    ap_done = Loop_realfft_be_stre_U0_ap_done.read();
}

void hls_xfft2real::thread_ap_idle() {
    ap_idle = (Loop_realfft_be_buff_U0_ap_idle.read() & Loop_realfft_be_desc_U0_ap_idle.read() & Loop_realfft_be_rev_U0_ap_idle.read() & Loop_realfft_be_stre_U0_ap_idle.read() & (descramble_buf_0_M_1_t_empty_n.read() ^ 
  ap_const_logic_1) & (descramble_buf_1_M_1_t_empty_n.read() ^ 
  ap_const_logic_1) & (descramble_buf_0_M_t_empty_n.read() ^ 
  ap_const_logic_1) & (descramble_buf_1_M_t_empty_n.read() ^ 
  ap_const_logic_1) & (real_spectrum_hi_buf_t_empty_n.read() ^ 
  ap_const_logic_1) & (real_spectrum_hi_buf_1_t_empty_n.read() ^ 
  ap_const_logic_1));
}

void hls_xfft2real::thread_ap_ready() {
    ap_ready = Loop_realfft_be_buff_U0_ap_ready.read();
}

void hls_xfft2real::thread_ap_rst_n_inv() {
    ap_rst_n_inv =  (sc_logic) (~ap_rst_n.read());
}

void hls_xfft2real::thread_ap_sync_channel_write_descramble_buf_0_M() {
    ap_sync_channel_write_descramble_buf_0_M = ((ap_channel_done_descramble_buf_0_M.read() & 
  Loop_realfft_be_buff_U0_descramble_buf_0_M_real_V_full_n.read()) | ap_sync_reg_channel_write_descramble_buf_0_M.read());
}

void hls_xfft2real::thread_ap_sync_channel_write_descramble_buf_0_M_1() {
    ap_sync_channel_write_descramble_buf_0_M_1 = ((ap_channel_done_descramble_buf_0_M_1.read() & 
  Loop_realfft_be_buff_U0_descramble_buf_0_M_imag_V_full_n.read()) | ap_sync_reg_channel_write_descramble_buf_0_M_1.read());
}

void hls_xfft2real::thread_ap_sync_channel_write_descramble_buf_1_M() {
    ap_sync_channel_write_descramble_buf_1_M = ((ap_channel_done_descramble_buf_1_M.read() & 
  Loop_realfft_be_buff_U0_descramble_buf_1_M_real_V_full_n.read()) | ap_sync_reg_channel_write_descramble_buf_1_M.read());
}

void hls_xfft2real::thread_ap_sync_channel_write_descramble_buf_1_M_1() {
    ap_sync_channel_write_descramble_buf_1_M_1 = ((ap_channel_done_descramble_buf_1_M_1.read() & 
  Loop_realfft_be_buff_U0_descramble_buf_1_M_imag_V_full_n.read()) | ap_sync_reg_channel_write_descramble_buf_1_M_1.read());
}

void hls_xfft2real::thread_ap_sync_channel_write_real_spectrum_hi_buf() {
    ap_sync_channel_write_real_spectrum_hi_buf = ((ap_channel_done_real_spectrum_hi_buf.read() & 
  Loop_realfft_be_desc_U0_real_spectrum_hi_buf_i_0_full_n.read()) | ap_sync_reg_channel_write_real_spectrum_hi_buf.read());
}

void hls_xfft2real::thread_ap_sync_channel_write_real_spectrum_hi_buf_1() {
    ap_sync_channel_write_real_spectrum_hi_buf_1 = ((ap_channel_done_real_spectrum_hi_buf_1.read() & 
  Loop_realfft_be_desc_U0_real_spectrum_hi_buf_i_1_full_n.read()) | ap_sync_reg_channel_write_real_spectrum_hi_buf_1.read());
}

void hls_xfft2real::thread_ap_sync_continue() {
    ap_sync_continue = ap_const_logic_1;
}

void hls_xfft2real::thread_ap_sync_done() {
    ap_sync_done = Loop_realfft_be_stre_U0_ap_done.read();
}

void hls_xfft2real::thread_ap_sync_ready() {
    ap_sync_ready = Loop_realfft_be_buff_U0_ap_ready.read();
}

void hls_xfft2real::thread_descramble_buf_1_M_1_t_d1() {
    descramble_buf_1_M_1_t_d1 = ap_const_lv16_0;
}

void hls_xfft2real::thread_descramble_buf_1_M_1_t_we1() {
    descramble_buf_1_M_1_t_we1 = ap_const_logic_0;
}

void hls_xfft2real::thread_descramble_buf_1_M_t_d1() {
    descramble_buf_1_M_t_d1 = ap_const_lv16_0;
}

void hls_xfft2real::thread_descramble_buf_1_M_t_we1() {
    descramble_buf_1_M_t_we1 = ap_const_logic_0;
}

void hls_xfft2real::thread_din_TREADY() {
    din_TREADY = Loop_realfft_be_buff_U0_din_TREADY.read();
}

void hls_xfft2real::thread_dout_TDATA() {
    dout_TDATA = Loop_realfft_be_stre_U0_dout_TDATA.read();
}

void hls_xfft2real::thread_dout_TLAST() {
    dout_TLAST = Loop_realfft_be_stre_U0_dout_TLAST.read();
}

void hls_xfft2real::thread_dout_TVALID() {
    dout_TVALID = Loop_realfft_be_stre_U0_dout_TVALID.read();
}

void hls_xfft2real::thread_start_for_Loop_realfft_be_stre_U0_din() {
    start_for_Loop_realfft_be_stre_U0_din =  (sc_lv<1>) (ap_const_logic_1);
}

void hls_xfft2real::thread_hdltv_gen() {
    const char* dump_tv = std::getenv("AP_WRITE_TV");
    if (!(dump_tv && string(dump_tv) == "on")) return;

    wait();

    mHdltvinHandle << "[ " << endl;
    mHdltvoutHandle << "[ " << endl;
    int ap_cycleNo = 0;
    while (1) {
        wait();
        const char* mComma = ap_cycleNo == 0 ? " " : ", " ;
        mHdltvinHandle << mComma << "{"  <<  " \"ap_rst_n\" :  \"" << ap_rst_n.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"din_TDATA\" :  \"" << din_TDATA.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"din_TLAST\" :  \"" << din_TLAST.read() << "\" ";
        mHdltvoutHandle << mComma << "{"  <<  " \"dout_TDATA\" :  \"" << dout_TDATA.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"dout_TLAST\" :  \"" << dout_TLAST.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"din_TVALID\" :  \"" << din_TVALID.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"din_TREADY\" :  \"" << din_TREADY.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"ap_start\" :  \"" << ap_start.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"dout_TVALID\" :  \"" << dout_TVALID.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"dout_TREADY\" :  \"" << dout_TREADY.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_done\" :  \"" << ap_done.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_ready\" :  \"" << ap_ready.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_idle\" :  \"" << ap_idle.read() << "\" ";
        mHdltvinHandle << "}" << std::endl;
        mHdltvoutHandle << "}" << std::endl;
        ap_cycleNo++;
    }
}

}

