// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2020.1
// Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "Loop_realfft_be_rev_s.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic Loop_realfft_be_rev_s::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic Loop_realfft_be_rev_s::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<3> Loop_realfft_be_rev_s::ap_ST_fsm_state1 = "1";
const sc_lv<3> Loop_realfft_be_rev_s::ap_ST_fsm_pp0_stage0 = "10";
const sc_lv<3> Loop_realfft_be_rev_s::ap_ST_fsm_state5 = "100";
const sc_lv<32> Loop_realfft_be_rev_s::ap_const_lv32_0 = "00000000000000000000000000000000";
const bool Loop_realfft_be_rev_s::ap_const_boolean_1 = true;
const bool Loop_realfft_be_rev_s::ap_const_boolean_0 = false;
const sc_lv<1> Loop_realfft_be_rev_s::ap_const_lv1_0 = "0";
const sc_lv<32> Loop_realfft_be_rev_s::ap_const_lv32_1 = "1";
const sc_lv<1> Loop_realfft_be_rev_s::ap_const_lv1_1 = "1";
const sc_lv<9> Loop_realfft_be_rev_s::ap_const_lv9_0 = "000000000";
const sc_lv<9> Loop_realfft_be_rev_s::ap_const_lv9_100 = "100000000";
const sc_lv<9> Loop_realfft_be_rev_s::ap_const_lv9_1 = "1";
const sc_lv<32> Loop_realfft_be_rev_s::ap_const_lv32_2 = "10";

Loop_realfft_be_rev_s::Loop_realfft_be_rev_s(sc_module_name name) : sc_module(name), mVcdFile(0) {

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_CS_fsm_pp0_stage0);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state5);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_block_pp0_stage0);

    SC_METHOD(thread_ap_block_pp0_stage0_01001);
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( icmp_ln115_reg_137_pp0_iter1_reg );
    sensitive << ( io_acc_block_signal_op24 );

    SC_METHOD(thread_ap_block_pp0_stage0_11001);
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( icmp_ln115_reg_137_pp0_iter1_reg );
    sensitive << ( io_acc_block_signal_op24 );

    SC_METHOD(thread_ap_block_pp0_stage0_subdone);
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( icmp_ln115_reg_137_pp0_iter1_reg );
    sensitive << ( io_acc_block_signal_op24 );

    SC_METHOD(thread_ap_block_state1);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );

    SC_METHOD(thread_ap_block_state2_pp0_stage0_iter0);

    SC_METHOD(thread_ap_block_state3_pp0_stage0_iter1);

    SC_METHOD(thread_ap_block_state4_pp0_stage0_iter2);
    sensitive << ( icmp_ln115_reg_137_pp0_iter1_reg );
    sensitive << ( io_acc_block_signal_op24 );

    SC_METHOD(thread_ap_condition_pp0_exit_iter0_state2);
    sensitive << ( icmp_ln115_fu_119_p2 );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_ap_enable_pp0);
    sensitive << ( ap_idle_pp0 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_idle_pp0);
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_i_fu_125_p2);
    sensitive << ( i3_0_i_reg_108 );

    SC_METHOD(thread_icmp_ln115_fu_119_p2);
    sensitive << ( i3_0_i_reg_108 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );

    SC_METHOD(thread_io_acc_block_signal_op24);
    sensitive << ( real_spectrum_hi_V_M_real_V_full_n );
    sensitive << ( real_spectrum_hi_V_M_imag_V_full_n );

    SC_METHOD(thread_real_spectrum_hi_V_M_imag_V_blk_n);
    sensitive << ( real_spectrum_hi_V_M_imag_V_full_n );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( icmp_ln115_reg_137_pp0_iter1_reg );

    SC_METHOD(thread_real_spectrum_hi_V_M_imag_V_din);
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( icmp_ln115_reg_137_pp0_iter1_reg );
    sensitive << ( tmp_M_imag_V_reg_161 );
    sensitive << ( ap_block_pp0_stage0_01001 );

    SC_METHOD(thread_real_spectrum_hi_V_M_imag_V_write);
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( icmp_ln115_reg_137_pp0_iter1_reg );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_real_spectrum_hi_V_M_real_V_blk_n);
    sensitive << ( real_spectrum_hi_V_M_real_V_full_n );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( icmp_ln115_reg_137_pp0_iter1_reg );

    SC_METHOD(thread_real_spectrum_hi_V_M_real_V_din);
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( icmp_ln115_reg_137_pp0_iter1_reg );
    sensitive << ( tmp_M_real_V_reg_156 );
    sensitive << ( ap_block_pp0_stage0_01001 );

    SC_METHOD(thread_real_spectrum_hi_V_M_real_V_write);
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( icmp_ln115_reg_137_pp0_iter1_reg );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_real_spectrum_hi_buf_i_0_address0);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( zext_ln117_fu_131_p1 );

    SC_METHOD(thread_real_spectrum_hi_buf_i_0_ce0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );

    SC_METHOD(thread_real_spectrum_hi_buf_i_1_address0);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( zext_ln117_fu_131_p1 );

    SC_METHOD(thread_real_spectrum_hi_buf_i_1_ce0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );

    SC_METHOD(thread_zext_ln117_fu_131_p1);
    sensitive << ( i3_0_i_reg_108 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( icmp_ln115_fu_119_p2 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_block_pp0_stage0_subdone );
    sensitive << ( ap_enable_reg_pp0_iter1 );

    ap_done_reg = SC_LOGIC_0;
    ap_CS_fsm = "001";
    ap_enable_reg_pp0_iter2 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter0 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter1 = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "Loop_realfft_be_rev_s_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_continue, "(port)ap_continue");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, real_spectrum_hi_buf_i_0_address0, "(port)real_spectrum_hi_buf_i_0_address0");
    sc_trace(mVcdFile, real_spectrum_hi_buf_i_0_ce0, "(port)real_spectrum_hi_buf_i_0_ce0");
    sc_trace(mVcdFile, real_spectrum_hi_buf_i_0_q0, "(port)real_spectrum_hi_buf_i_0_q0");
    sc_trace(mVcdFile, real_spectrum_hi_buf_i_1_address0, "(port)real_spectrum_hi_buf_i_1_address0");
    sc_trace(mVcdFile, real_spectrum_hi_buf_i_1_ce0, "(port)real_spectrum_hi_buf_i_1_ce0");
    sc_trace(mVcdFile, real_spectrum_hi_buf_i_1_q0, "(port)real_spectrum_hi_buf_i_1_q0");
    sc_trace(mVcdFile, real_spectrum_hi_V_M_real_V_din, "(port)real_spectrum_hi_V_M_real_V_din");
    sc_trace(mVcdFile, real_spectrum_hi_V_M_real_V_full_n, "(port)real_spectrum_hi_V_M_real_V_full_n");
    sc_trace(mVcdFile, real_spectrum_hi_V_M_real_V_write, "(port)real_spectrum_hi_V_M_real_V_write");
    sc_trace(mVcdFile, real_spectrum_hi_V_M_imag_V_din, "(port)real_spectrum_hi_V_M_imag_V_din");
    sc_trace(mVcdFile, real_spectrum_hi_V_M_imag_V_full_n, "(port)real_spectrum_hi_V_M_imag_V_full_n");
    sc_trace(mVcdFile, real_spectrum_hi_V_M_imag_V_write, "(port)real_spectrum_hi_V_M_imag_V_write");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_done_reg, "ap_done_reg");
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, real_spectrum_hi_V_M_real_V_blk_n, "real_spectrum_hi_V_M_real_V_blk_n");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter2, "ap_enable_reg_pp0_iter2");
    sc_trace(mVcdFile, ap_block_pp0_stage0, "ap_block_pp0_stage0");
    sc_trace(mVcdFile, icmp_ln115_reg_137, "icmp_ln115_reg_137");
    sc_trace(mVcdFile, icmp_ln115_reg_137_pp0_iter1_reg, "icmp_ln115_reg_137_pp0_iter1_reg");
    sc_trace(mVcdFile, real_spectrum_hi_V_M_imag_V_blk_n, "real_spectrum_hi_V_M_imag_V_blk_n");
    sc_trace(mVcdFile, i3_0_i_reg_108, "i3_0_i_reg_108");
    sc_trace(mVcdFile, icmp_ln115_fu_119_p2, "icmp_ln115_fu_119_p2");
    sc_trace(mVcdFile, ap_CS_fsm_pp0_stage0, "ap_CS_fsm_pp0_stage0");
    sc_trace(mVcdFile, ap_block_state2_pp0_stage0_iter0, "ap_block_state2_pp0_stage0_iter0");
    sc_trace(mVcdFile, ap_block_state3_pp0_stage0_iter1, "ap_block_state3_pp0_stage0_iter1");
    sc_trace(mVcdFile, io_acc_block_signal_op24, "io_acc_block_signal_op24");
    sc_trace(mVcdFile, ap_block_state4_pp0_stage0_iter2, "ap_block_state4_pp0_stage0_iter2");
    sc_trace(mVcdFile, ap_block_pp0_stage0_11001, "ap_block_pp0_stage0_11001");
    sc_trace(mVcdFile, i_fu_125_p2, "i_fu_125_p2");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter0, "ap_enable_reg_pp0_iter0");
    sc_trace(mVcdFile, tmp_M_real_V_reg_156, "tmp_M_real_V_reg_156");
    sc_trace(mVcdFile, tmp_M_imag_V_reg_161, "tmp_M_imag_V_reg_161");
    sc_trace(mVcdFile, ap_block_state1, "ap_block_state1");
    sc_trace(mVcdFile, ap_block_pp0_stage0_subdone, "ap_block_pp0_stage0_subdone");
    sc_trace(mVcdFile, ap_condition_pp0_exit_iter0_state2, "ap_condition_pp0_exit_iter0_state2");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter1, "ap_enable_reg_pp0_iter1");
    sc_trace(mVcdFile, zext_ln117_fu_131_p1, "zext_ln117_fu_131_p1");
    sc_trace(mVcdFile, ap_block_pp0_stage0_01001, "ap_block_pp0_stage0_01001");
    sc_trace(mVcdFile, ap_CS_fsm_state5, "ap_CS_fsm_state5");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
    sc_trace(mVcdFile, ap_idle_pp0, "ap_idle_pp0");
    sc_trace(mVcdFile, ap_enable_pp0, "ap_enable_pp0");
#endif

    }
}

Loop_realfft_be_rev_s::~Loop_realfft_be_rev_s() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

}

void Loop_realfft_be_rev_s::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_done_reg = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_continue.read())) {
            ap_done_reg = ap_const_logic_0;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
            ap_done_reg = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter0 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
             esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_condition_pp0_exit_iter0_state2.read()))) {
            ap_enable_reg_pp0_iter0 = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                    !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
            ap_enable_reg_pp0_iter0 = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter1 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            if (esl_seteq<1,1,1>(ap_const_logic_1, ap_condition_pp0_exit_iter0_state2.read())) {
                ap_enable_reg_pp0_iter1 = (ap_condition_pp0_exit_iter0_state2.read() ^ ap_const_logic_1);
            } else if (esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1)) {
                ap_enable_reg_pp0_iter1 = ap_enable_reg_pp0_iter0.read();
            }
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter2 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter2 = ap_enable_reg_pp0_iter1.read();
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                    !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
            ap_enable_reg_pp0_iter2 = ap_const_logic_0;
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        i3_0_i_reg_108 = ap_const_lv9_0;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
                esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln115_fu_119_p2.read()))) {
        i3_0_i_reg_108 = i_fu_125_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        icmp_ln115_reg_137 = icmp_ln115_fu_119_p2.read();
        icmp_ln115_reg_137_pp0_iter1_reg = icmp_ln115_reg_137.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(icmp_ln115_reg_137.read(), ap_const_lv1_0))) {
        tmp_M_imag_V_reg_161 = real_spectrum_hi_buf_i_1_q0.read();
        tmp_M_real_V_reg_156 = real_spectrum_hi_buf_i_0_q0.read();
    }
}

void Loop_realfft_be_rev_s::thread_ap_CS_fsm_pp0_stage0() {
    ap_CS_fsm_pp0_stage0 = ap_CS_fsm.read()[1];
}

void Loop_realfft_be_rev_s::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void Loop_realfft_be_rev_s::thread_ap_CS_fsm_state5() {
    ap_CS_fsm_state5 = ap_CS_fsm.read()[2];
}

void Loop_realfft_be_rev_s::thread_ap_block_pp0_stage0() {
    ap_block_pp0_stage0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void Loop_realfft_be_rev_s::thread_ap_block_pp0_stage0_01001() {
    ap_block_pp0_stage0_01001 = (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && esl_seteq<1,1,1>(icmp_ln115_reg_137_pp0_iter1_reg.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_0, io_acc_block_signal_op24.read()));
}

void Loop_realfft_be_rev_s::thread_ap_block_pp0_stage0_11001() {
    ap_block_pp0_stage0_11001 = (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && esl_seteq<1,1,1>(icmp_ln115_reg_137_pp0_iter1_reg.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_0, io_acc_block_signal_op24.read()));
}

void Loop_realfft_be_rev_s::thread_ap_block_pp0_stage0_subdone() {
    ap_block_pp0_stage0_subdone = (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && esl_seteq<1,1,1>(icmp_ln115_reg_137_pp0_iter1_reg.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_0, io_acc_block_signal_op24.read()));
}

void Loop_realfft_be_rev_s::thread_ap_block_state1() {
    ap_block_state1 = (esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1));
}

void Loop_realfft_be_rev_s::thread_ap_block_state2_pp0_stage0_iter0() {
    ap_block_state2_pp0_stage0_iter0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void Loop_realfft_be_rev_s::thread_ap_block_state3_pp0_stage0_iter1() {
    ap_block_state3_pp0_stage0_iter1 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void Loop_realfft_be_rev_s::thread_ap_block_state4_pp0_stage0_iter2() {
    ap_block_state4_pp0_stage0_iter2 = (esl_seteq<1,1,1>(icmp_ln115_reg_137_pp0_iter1_reg.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_0, io_acc_block_signal_op24.read()));
}

void Loop_realfft_be_rev_s::thread_ap_condition_pp0_exit_iter0_state2() {
    if (esl_seteq<1,1,1>(icmp_ln115_fu_119_p2.read(), ap_const_lv1_1)) {
        ap_condition_pp0_exit_iter0_state2 = ap_const_logic_1;
    } else {
        ap_condition_pp0_exit_iter0_state2 = ap_const_logic_0;
    }
}

void Loop_realfft_be_rev_s::thread_ap_done() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_done_reg.read();
    }
}

void Loop_realfft_be_rev_s::thread_ap_enable_pp0() {
    ap_enable_pp0 = (ap_idle_pp0.read() ^ ap_const_logic_1);
}

void Loop_realfft_be_rev_s::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void Loop_realfft_be_rev_s::thread_ap_idle_pp0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter2.read()))) {
        ap_idle_pp0 = ap_const_logic_1;
    } else {
        ap_idle_pp0 = ap_const_logic_0;
    }
}

void Loop_realfft_be_rev_s::thread_ap_ready() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void Loop_realfft_be_rev_s::thread_i_fu_125_p2() {
    i_fu_125_p2 = (!i3_0_i_reg_108.read().is_01() || !ap_const_lv9_1.is_01())? sc_lv<9>(): (sc_biguint<9>(i3_0_i_reg_108.read()) + sc_biguint<9>(ap_const_lv9_1));
}

void Loop_realfft_be_rev_s::thread_icmp_ln115_fu_119_p2() {
    icmp_ln115_fu_119_p2 = (!i3_0_i_reg_108.read().is_01() || !ap_const_lv9_100.is_01())? sc_lv<1>(): sc_lv<1>(i3_0_i_reg_108.read() == ap_const_lv9_100);
}

void Loop_realfft_be_rev_s::thread_io_acc_block_signal_op24() {
    io_acc_block_signal_op24 = (real_spectrum_hi_V_M_real_V_full_n.read() & real_spectrum_hi_V_M_imag_V_full_n.read());
}

void Loop_realfft_be_rev_s::thread_real_spectrum_hi_V_M_imag_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(icmp_ln115_reg_137_pp0_iter1_reg.read(), ap_const_lv1_0))) {
        real_spectrum_hi_V_M_imag_V_blk_n = real_spectrum_hi_V_M_imag_V_full_n.read();
    } else {
        real_spectrum_hi_V_M_imag_V_blk_n = ap_const_logic_1;
    }
}

void Loop_realfft_be_rev_s::thread_real_spectrum_hi_V_M_imag_V_din() {
    real_spectrum_hi_V_M_imag_V_din = tmp_M_imag_V_reg_161.read();
}

void Loop_realfft_be_rev_s::thread_real_spectrum_hi_V_M_imag_V_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && 
         esl_seteq<1,1,1>(icmp_ln115_reg_137_pp0_iter1_reg.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        real_spectrum_hi_V_M_imag_V_write = ap_const_logic_1;
    } else {
        real_spectrum_hi_V_M_imag_V_write = ap_const_logic_0;
    }
}

void Loop_realfft_be_rev_s::thread_real_spectrum_hi_V_M_real_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(icmp_ln115_reg_137_pp0_iter1_reg.read(), ap_const_lv1_0))) {
        real_spectrum_hi_V_M_real_V_blk_n = real_spectrum_hi_V_M_real_V_full_n.read();
    } else {
        real_spectrum_hi_V_M_real_V_blk_n = ap_const_logic_1;
    }
}

void Loop_realfft_be_rev_s::thread_real_spectrum_hi_V_M_real_V_din() {
    real_spectrum_hi_V_M_real_V_din = tmp_M_real_V_reg_156.read();
}

void Loop_realfft_be_rev_s::thread_real_spectrum_hi_V_M_real_V_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && 
         esl_seteq<1,1,1>(icmp_ln115_reg_137_pp0_iter1_reg.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        real_spectrum_hi_V_M_real_V_write = ap_const_logic_1;
    } else {
        real_spectrum_hi_V_M_real_V_write = ap_const_logic_0;
    }
}

void Loop_realfft_be_rev_s::thread_real_spectrum_hi_buf_i_0_address0() {
    real_spectrum_hi_buf_i_0_address0 =  (sc_lv<8>) (zext_ln117_fu_131_p1.read());
}

void Loop_realfft_be_rev_s::thread_real_spectrum_hi_buf_i_0_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()))) {
        real_spectrum_hi_buf_i_0_ce0 = ap_const_logic_1;
    } else {
        real_spectrum_hi_buf_i_0_ce0 = ap_const_logic_0;
    }
}

void Loop_realfft_be_rev_s::thread_real_spectrum_hi_buf_i_1_address0() {
    real_spectrum_hi_buf_i_1_address0 =  (sc_lv<8>) (zext_ln117_fu_131_p1.read());
}

void Loop_realfft_be_rev_s::thread_real_spectrum_hi_buf_i_1_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()))) {
        real_spectrum_hi_buf_i_1_ce0 = ap_const_logic_1;
    } else {
        real_spectrum_hi_buf_i_1_ce0 = ap_const_logic_0;
    }
}

void Loop_realfft_be_rev_s::thread_zext_ln117_fu_131_p1() {
    zext_ln117_fu_131_p1 = esl_zext<64,9>(i3_0_i_reg_108.read());
}

void Loop_realfft_be_rev_s::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((!(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_enable_reg_pp0_iter1.read(), ap_const_logic_0)) && !(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(icmp_ln115_fu_119_p2.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_enable_reg_pp0_iter1.read(), ap_const_logic_0)))) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            } else if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && 
  esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && 
  esl_seteq<1,1,1>(ap_enable_reg_pp0_iter1.read(), ap_const_logic_0)) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
  esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && 
  esl_seteq<1,1,1>(icmp_ln115_fu_119_p2.read(), ap_const_lv1_1) && 
  esl_seteq<1,1,1>(ap_enable_reg_pp0_iter1.read(), ap_const_logic_0)))) {
                ap_NS_fsm = ap_ST_fsm_state5;
            } else {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            }
            break;
        case 4 : 
            ap_NS_fsm = ap_ST_fsm_state1;
            break;
        default : 
            ap_NS_fsm = "XXX";
            break;
    }
}

}

