# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/ethan_kvm/hls_ip_zynq_lab2/hls_ip_zynq_lab2.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_2/design_1_axi_dma_2.xci
# IP: The module: 'design_1_axi_dma_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/ethan_kvm/hls_ip_zynq_lab2/hls_ip_zynq_lab2.gen/sources_1/bd/design_1/ip/design_1_axi_dma_2/design_1_axi_dma_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_dma_2'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/ethan_kvm/hls_ip_zynq_lab2/hls_ip_zynq_lab2.gen/sources_1/bd/design_1/ip/design_1_axi_dma_2/design_1_axi_dma_2_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_dma_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/ethan_kvm/hls_ip_zynq_lab2/hls_ip_zynq_lab2.gen/sources_1/bd/design_1/ip/design_1_axi_dma_2/design_1_axi_dma_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_dma_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/ethan_kvm/hls_ip_zynq_lab2/hls_ip_zynq_lab2.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_2/design_1_axi_dma_2.xci
# IP: The module: 'design_1_axi_dma_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/ethan_kvm/hls_ip_zynq_lab2/hls_ip_zynq_lab2.gen/sources_1/bd/design_1/ip/design_1_axi_dma_2/design_1_axi_dma_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_dma_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/ethan_kvm/hls_ip_zynq_lab2/hls_ip_zynq_lab2.gen/sources_1/bd/design_1/ip/design_1_axi_dma_2/design_1_axi_dma_2_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_dma_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/ethan_kvm/hls_ip_zynq_lab2/hls_ip_zynq_lab2.gen/sources_1/bd/design_1/ip/design_1_axi_dma_2/design_1_axi_dma_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_dma_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
