// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2 (64-bit)
// Version: 2020.2
// Copyright (C) Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="hls_real2xfft_hls_real2xfft,hls_ip_2020_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=5.404000,HLS_SYN_LAT=2055,HLS_SYN_TPT=1024,HLS_SYN_MEM=8,HLS_SYN_DSP=0,HLS_SYN_FF=681,HLS_SYN_LUT=757,HLS_VERSION=2020_2}" *)

module hls_real2xfft (
        ap_clk,
        ap_rst_n,
        din_V_TDATA,
        dout_V_TDATA,
        din_V_TVALID,
        din_V_TREADY,
        ap_start,
        dout_V_TVALID,
        dout_V_TREADY,
        ap_done,
        ap_ready,
        ap_idle
);


input   ap_clk;
input   ap_rst_n;
input  [15:0] din_V_TDATA;
output  [47:0] dout_V_TDATA;
input   din_V_TVALID;
output   din_V_TREADY;
input   ap_start;
output   dout_V_TVALID;
input   dout_V_TREADY;
output   ap_done;
output   ap_ready;
output   ap_idle;

 reg    ap_rst_n_inv;
wire   [15:0] data2window_V_0_i_q0;
wire   [15:0] data2window_V_0_t_q0;
wire   [15:0] data2window_V_1_i_q0;
wire   [15:0] data2window_V_1_t_q0;
wire   [15:0] windowed_V_0_i_q0;
wire   [15:0] windowed_V_0_t_q0;
wire   [15:0] windowed_V_1_i_q0;
wire   [15:0] windowed_V_1_t_q0;
wire   [8:0] sliding_win_1in2out_ap_fixed_16_1_5_3_0_1024_U0_dout_address0;
wire    sliding_win_1in2out_ap_fixed_16_1_5_3_0_1024_U0_dout_ce0;
wire   [15:0] sliding_win_1in2out_ap_fixed_16_1_5_3_0_1024_U0_dout_d0;
wire    sliding_win_1in2out_ap_fixed_16_1_5_3_0_1024_U0_dout_we0;
wire   [8:0] sliding_win_1in2out_ap_fixed_16_1_5_3_0_1024_U0_dout_address1;
wire    sliding_win_1in2out_ap_fixed_16_1_5_3_0_1024_U0_dout_ce1;
wire   [15:0] sliding_win_1in2out_ap_fixed_16_1_5_3_0_1024_U0_dout_d1;
wire    sliding_win_1in2out_ap_fixed_16_1_5_3_0_1024_U0_dout_we1;
wire   [8:0] sliding_win_1in2out_ap_fixed_16_1_5_3_0_1024_U0_dout1_address0;
wire    sliding_win_1in2out_ap_fixed_16_1_5_3_0_1024_U0_dout1_ce0;
wire   [15:0] sliding_win_1in2out_ap_fixed_16_1_5_3_0_1024_U0_dout1_d0;
wire    sliding_win_1in2out_ap_fixed_16_1_5_3_0_1024_U0_dout1_we0;
wire   [8:0] sliding_win_1in2out_ap_fixed_16_1_5_3_0_1024_U0_dout1_address1;
wire    sliding_win_1in2out_ap_fixed_16_1_5_3_0_1024_U0_dout1_ce1;
wire   [15:0] sliding_win_1in2out_ap_fixed_16_1_5_3_0_1024_U0_dout1_d1;
wire    sliding_win_1in2out_ap_fixed_16_1_5_3_0_1024_U0_dout1_we1;
wire    sliding_win_1in2out_ap_fixed_16_1_5_3_0_1024_U0_din_V_TREADY;
wire    sliding_win_1in2out_ap_fixed_16_1_5_3_0_1024_U0_ap_start;
wire    sliding_win_1in2out_ap_fixed_16_1_5_3_0_1024_U0_dout1_full_n;
wire    sliding_win_1in2out_ap_fixed_16_1_5_3_0_1024_U0_dout1_write;
wire    sliding_win_1in2out_ap_fixed_16_1_5_3_0_1024_U0_dout_full_n;
wire    sliding_win_1in2out_ap_fixed_16_1_5_3_0_1024_U0_dout_write;
wire    sliding_win_1in2out_ap_fixed_16_1_5_3_0_1024_U0_ap_done;
wire    sliding_win_1in2out_ap_fixed_16_1_5_3_0_1024_U0_ap_ready;
wire    sliding_win_1in2out_ap_fixed_16_1_5_3_0_1024_U0_ap_idle;
wire    sliding_win_1in2out_ap_fixed_16_1_5_3_0_1024_U0_ap_continue;
wire    ap_channel_done_data2window_V_1;
reg    ap_sync_reg_channel_write_data2window_V_1;
wire    ap_sync_channel_write_data2window_V_1;
wire    ap_channel_done_data2window_V_0;
reg    ap_sync_reg_channel_write_data2window_V_0;
wire    ap_sync_channel_write_data2window_V_0;
wire    window_fn_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_0_0_1024_2_2_U0_ap_start;
wire    window_fn_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_0_0_1024_2_2_U0_ap_done;
wire    window_fn_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_0_0_1024_2_2_U0_ap_continue;
wire    window_fn_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_0_0_1024_2_2_U0_ap_idle;
wire    window_fn_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_0_0_1024_2_2_U0_ap_ready;
wire   [8:0] window_fn_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_0_0_1024_2_2_U0_indata_address0;
wire    window_fn_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_0_0_1024_2_2_U0_indata_ce0;
wire   [8:0] window_fn_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_0_0_1024_2_2_U0_indata1_address0;
wire    window_fn_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_0_0_1024_2_2_U0_indata1_ce0;
wire   [8:0] window_fn_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_0_0_1024_2_2_U0_outdata_address0;
wire    window_fn_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_0_0_1024_2_2_U0_outdata_ce0;
wire    window_fn_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_0_0_1024_2_2_U0_outdata_we0;
wire   [15:0] window_fn_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_0_0_1024_2_2_U0_outdata_d0;
wire   [8:0] window_fn_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_0_0_1024_2_2_U0_outdata2_address0;
wire    window_fn_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_0_0_1024_2_2_U0_outdata2_ce0;
wire    window_fn_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_0_0_1024_2_2_U0_outdata2_we0;
wire   [15:0] window_fn_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_0_0_1024_2_2_U0_outdata2_d0;
wire    ap_channel_done_windowed_V_1;
wire    window_fn_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_0_0_1024_2_2_U0_outdata2_full_n;
reg    ap_sync_reg_channel_write_windowed_V_1;
wire    ap_sync_channel_write_windowed_V_1;
wire    ap_channel_done_windowed_V_0;
wire    window_fn_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_0_0_1024_2_2_U0_outdata_full_n;
reg    ap_sync_reg_channel_write_windowed_V_0;
wire    ap_sync_channel_write_windowed_V_0;
wire    Loop_real2xfft_output_proc9_U0_ap_start;
wire    Loop_real2xfft_output_proc9_U0_ap_done;
wire    Loop_real2xfft_output_proc9_U0_ap_continue;
wire    Loop_real2xfft_output_proc9_U0_ap_idle;
wire    Loop_real2xfft_output_proc9_U0_ap_ready;
wire   [8:0] Loop_real2xfft_output_proc9_U0_windowed_V_0_address0;
wire    Loop_real2xfft_output_proc9_U0_windowed_V_0_ce0;
wire   [8:0] Loop_real2xfft_output_proc9_U0_windowed_V_1_address0;
wire    Loop_real2xfft_output_proc9_U0_windowed_V_1_ce0;
wire   [47:0] Loop_real2xfft_output_proc9_U0_dout_V_TDATA;
wire    Loop_real2xfft_output_proc9_U0_dout_V_TVALID;
wire    ap_sync_continue;
wire    data2window_V_0_i_full_n;
wire    data2window_V_0_t_empty_n;
wire    data2window_V_1_i_full_n;
wire    data2window_V_1_t_empty_n;
wire    windowed_V_0_i_full_n;
wire    windowed_V_0_t_empty_n;
wire    windowed_V_1_i_full_n;
wire    windowed_V_1_t_empty_n;
wire    ap_sync_done;
wire    ap_sync_ready;
wire    sliding_win_1in2out_ap_fixed_16_1_5_3_0_1024_U0_start_full_n;
wire    sliding_win_1in2out_ap_fixed_16_1_5_3_0_1024_U0_start_write;
wire    window_fn_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_0_0_1024_2_2_U0_start_full_n;
wire    window_fn_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_0_0_1024_2_2_U0_start_write;
wire    Loop_real2xfft_output_proc9_U0_start_full_n;
wire    Loop_real2xfft_output_proc9_U0_start_write;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_sync_reg_channel_write_data2window_V_1 = 1'b0;
#0 ap_sync_reg_channel_write_data2window_V_0 = 1'b0;
#0 ap_sync_reg_channel_write_windowed_V_1 = 1'b0;
#0 ap_sync_reg_channel_write_windowed_V_0 = 1'b0;
end

hls_real2xfft_data2window_V_0 #(
    .DataWidth( 16 ),
    .AddressRange( 512 ),
    .AddressWidth( 9 ))
data2window_V_0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .i_address0(sliding_win_1in2out_ap_fixed_16_1_5_3_0_1024_U0_dout_address0),
    .i_ce0(sliding_win_1in2out_ap_fixed_16_1_5_3_0_1024_U0_dout_ce0),
    .i_we0(sliding_win_1in2out_ap_fixed_16_1_5_3_0_1024_U0_dout_we0),
    .i_d0(sliding_win_1in2out_ap_fixed_16_1_5_3_0_1024_U0_dout_d0),
    .i_q0(data2window_V_0_i_q0),
    .t_address0(window_fn_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_0_0_1024_2_2_U0_indata_address0),
    .t_ce0(window_fn_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_0_0_1024_2_2_U0_indata_ce0),
    .t_we0(1'b0),
    .t_d0(16'd0),
    .t_q0(data2window_V_0_t_q0),
    .i_ce(1'b1),
    .t_ce(1'b1),
    .i_full_n(data2window_V_0_i_full_n),
    .i_write(ap_channel_done_data2window_V_0),
    .t_empty_n(data2window_V_0_t_empty_n),
    .t_read(window_fn_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_0_0_1024_2_2_U0_ap_ready)
);

hls_real2xfft_data2window_V_0 #(
    .DataWidth( 16 ),
    .AddressRange( 512 ),
    .AddressWidth( 9 ))
data2window_V_1_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .i_address0(sliding_win_1in2out_ap_fixed_16_1_5_3_0_1024_U0_dout1_address0),
    .i_ce0(sliding_win_1in2out_ap_fixed_16_1_5_3_0_1024_U0_dout1_ce0),
    .i_we0(sliding_win_1in2out_ap_fixed_16_1_5_3_0_1024_U0_dout1_we0),
    .i_d0(sliding_win_1in2out_ap_fixed_16_1_5_3_0_1024_U0_dout1_d0),
    .i_q0(data2window_V_1_i_q0),
    .t_address0(window_fn_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_0_0_1024_2_2_U0_indata1_address0),
    .t_ce0(window_fn_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_0_0_1024_2_2_U0_indata1_ce0),
    .t_we0(1'b0),
    .t_d0(16'd0),
    .t_q0(data2window_V_1_t_q0),
    .i_ce(1'b1),
    .t_ce(1'b1),
    .i_full_n(data2window_V_1_i_full_n),
    .i_write(ap_channel_done_data2window_V_1),
    .t_empty_n(data2window_V_1_t_empty_n),
    .t_read(window_fn_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_0_0_1024_2_2_U0_ap_ready)
);

hls_real2xfft_data2window_V_0 #(
    .DataWidth( 16 ),
    .AddressRange( 512 ),
    .AddressWidth( 9 ))
windowed_V_0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .i_address0(window_fn_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_0_0_1024_2_2_U0_outdata_address0),
    .i_ce0(window_fn_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_0_0_1024_2_2_U0_outdata_ce0),
    .i_we0(window_fn_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_0_0_1024_2_2_U0_outdata_we0),
    .i_d0(window_fn_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_0_0_1024_2_2_U0_outdata_d0),
    .i_q0(windowed_V_0_i_q0),
    .t_address0(Loop_real2xfft_output_proc9_U0_windowed_V_0_address0),
    .t_ce0(Loop_real2xfft_output_proc9_U0_windowed_V_0_ce0),
    .t_we0(1'b0),
    .t_d0(16'd0),
    .t_q0(windowed_V_0_t_q0),
    .i_ce(1'b1),
    .t_ce(1'b1),
    .i_full_n(windowed_V_0_i_full_n),
    .i_write(ap_channel_done_windowed_V_0),
    .t_empty_n(windowed_V_0_t_empty_n),
    .t_read(Loop_real2xfft_output_proc9_U0_ap_ready)
);

hls_real2xfft_data2window_V_0 #(
    .DataWidth( 16 ),
    .AddressRange( 512 ),
    .AddressWidth( 9 ))
windowed_V_1_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .i_address0(window_fn_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_0_0_1024_2_2_U0_outdata2_address0),
    .i_ce0(window_fn_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_0_0_1024_2_2_U0_outdata2_ce0),
    .i_we0(window_fn_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_0_0_1024_2_2_U0_outdata2_we0),
    .i_d0(window_fn_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_0_0_1024_2_2_U0_outdata2_d0),
    .i_q0(windowed_V_1_i_q0),
    .t_address0(Loop_real2xfft_output_proc9_U0_windowed_V_1_address0),
    .t_ce0(Loop_real2xfft_output_proc9_U0_windowed_V_1_ce0),
    .t_we0(1'b0),
    .t_d0(16'd0),
    .t_q0(windowed_V_1_t_q0),
    .i_ce(1'b1),
    .t_ce(1'b1),
    .i_full_n(windowed_V_1_i_full_n),
    .i_write(ap_channel_done_windowed_V_1),
    .t_empty_n(windowed_V_1_t_empty_n),
    .t_read(Loop_real2xfft_output_proc9_U0_ap_ready)
);

hls_real2xfft_sliding_win_1in2out_ap_fixed_16_1_5_3_0_1024_s sliding_win_1in2out_ap_fixed_16_1_5_3_0_1024_U0(
    .din_V_TDATA(din_V_TDATA),
    .dout_address0(sliding_win_1in2out_ap_fixed_16_1_5_3_0_1024_U0_dout_address0),
    .dout_ce0(sliding_win_1in2out_ap_fixed_16_1_5_3_0_1024_U0_dout_ce0),
    .dout_d0(sliding_win_1in2out_ap_fixed_16_1_5_3_0_1024_U0_dout_d0),
    .dout_q0(16'd0),
    .dout_we0(sliding_win_1in2out_ap_fixed_16_1_5_3_0_1024_U0_dout_we0),
    .dout_address1(sliding_win_1in2out_ap_fixed_16_1_5_3_0_1024_U0_dout_address1),
    .dout_ce1(sliding_win_1in2out_ap_fixed_16_1_5_3_0_1024_U0_dout_ce1),
    .dout_d1(sliding_win_1in2out_ap_fixed_16_1_5_3_0_1024_U0_dout_d1),
    .dout_q1(16'd0),
    .dout_we1(sliding_win_1in2out_ap_fixed_16_1_5_3_0_1024_U0_dout_we1),
    .dout1_address0(sliding_win_1in2out_ap_fixed_16_1_5_3_0_1024_U0_dout1_address0),
    .dout1_ce0(sliding_win_1in2out_ap_fixed_16_1_5_3_0_1024_U0_dout1_ce0),
    .dout1_d0(sliding_win_1in2out_ap_fixed_16_1_5_3_0_1024_U0_dout1_d0),
    .dout1_q0(16'd0),
    .dout1_we0(sliding_win_1in2out_ap_fixed_16_1_5_3_0_1024_U0_dout1_we0),
    .dout1_address1(sliding_win_1in2out_ap_fixed_16_1_5_3_0_1024_U0_dout1_address1),
    .dout1_ce1(sliding_win_1in2out_ap_fixed_16_1_5_3_0_1024_U0_dout1_ce1),
    .dout1_d1(sliding_win_1in2out_ap_fixed_16_1_5_3_0_1024_U0_dout1_d1),
    .dout1_q1(16'd0),
    .dout1_we1(sliding_win_1in2out_ap_fixed_16_1_5_3_0_1024_U0_dout1_we1),
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .din_V_TVALID(din_V_TVALID),
    .din_V_TREADY(sliding_win_1in2out_ap_fixed_16_1_5_3_0_1024_U0_din_V_TREADY),
    .ap_start(sliding_win_1in2out_ap_fixed_16_1_5_3_0_1024_U0_ap_start),
    .dout1_full_n(data2window_V_1_i_full_n),
    .dout1_write(sliding_win_1in2out_ap_fixed_16_1_5_3_0_1024_U0_dout1_write),
    .dout_full_n(data2window_V_0_i_full_n),
    .dout_write(sliding_win_1in2out_ap_fixed_16_1_5_3_0_1024_U0_dout_write),
    .ap_done(sliding_win_1in2out_ap_fixed_16_1_5_3_0_1024_U0_ap_done),
    .ap_ready(sliding_win_1in2out_ap_fixed_16_1_5_3_0_1024_U0_ap_ready),
    .ap_idle(sliding_win_1in2out_ap_fixed_16_1_5_3_0_1024_U0_ap_idle),
    .ap_continue(sliding_win_1in2out_ap_fixed_16_1_5_3_0_1024_U0_ap_continue)
);

hls_real2xfft_window_fn_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_0_0_1024_2_2_s window_fn_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_0_0_1024_2_2_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(window_fn_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_0_0_1024_2_2_U0_ap_start),
    .ap_done(window_fn_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_0_0_1024_2_2_U0_ap_done),
    .ap_continue(window_fn_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_0_0_1024_2_2_U0_ap_continue),
    .ap_idle(window_fn_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_0_0_1024_2_2_U0_ap_idle),
    .ap_ready(window_fn_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_0_0_1024_2_2_U0_ap_ready),
    .indata_address0(window_fn_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_0_0_1024_2_2_U0_indata_address0),
    .indata_ce0(window_fn_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_0_0_1024_2_2_U0_indata_ce0),
    .indata_q0(data2window_V_0_t_q0),
    .indata1_address0(window_fn_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_0_0_1024_2_2_U0_indata1_address0),
    .indata1_ce0(window_fn_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_0_0_1024_2_2_U0_indata1_ce0),
    .indata1_q0(data2window_V_1_t_q0),
    .outdata_address0(window_fn_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_0_0_1024_2_2_U0_outdata_address0),
    .outdata_ce0(window_fn_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_0_0_1024_2_2_U0_outdata_ce0),
    .outdata_we0(window_fn_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_0_0_1024_2_2_U0_outdata_we0),
    .outdata_d0(window_fn_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_0_0_1024_2_2_U0_outdata_d0),
    .outdata2_address0(window_fn_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_0_0_1024_2_2_U0_outdata2_address0),
    .outdata2_ce0(window_fn_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_0_0_1024_2_2_U0_outdata2_ce0),
    .outdata2_we0(window_fn_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_0_0_1024_2_2_U0_outdata2_we0),
    .outdata2_d0(window_fn_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_0_0_1024_2_2_U0_outdata2_d0)
);

hls_real2xfft_Loop_real2xfft_output_proc9 Loop_real2xfft_output_proc9_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(Loop_real2xfft_output_proc9_U0_ap_start),
    .ap_done(Loop_real2xfft_output_proc9_U0_ap_done),
    .ap_continue(Loop_real2xfft_output_proc9_U0_ap_continue),
    .ap_idle(Loop_real2xfft_output_proc9_U0_ap_idle),
    .ap_ready(Loop_real2xfft_output_proc9_U0_ap_ready),
    .dout_V_TREADY(dout_V_TREADY),
    .windowed_V_0_address0(Loop_real2xfft_output_proc9_U0_windowed_V_0_address0),
    .windowed_V_0_ce0(Loop_real2xfft_output_proc9_U0_windowed_V_0_ce0),
    .windowed_V_0_q0(windowed_V_0_t_q0),
    .windowed_V_1_address0(Loop_real2xfft_output_proc9_U0_windowed_V_1_address0),
    .windowed_V_1_ce0(Loop_real2xfft_output_proc9_U0_windowed_V_1_ce0),
    .windowed_V_1_q0(windowed_V_1_t_q0),
    .dout_V_TDATA(Loop_real2xfft_output_proc9_U0_dout_V_TDATA),
    .dout_V_TVALID(Loop_real2xfft_output_proc9_U0_dout_V_TVALID)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_channel_write_data2window_V_0 <= 1'b0;
    end else begin
        if (((sliding_win_1in2out_ap_fixed_16_1_5_3_0_1024_U0_ap_done & sliding_win_1in2out_ap_fixed_16_1_5_3_0_1024_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_data2window_V_0 <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_data2window_V_0 <= ap_sync_channel_write_data2window_V_0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_channel_write_data2window_V_1 <= 1'b0;
    end else begin
        if (((sliding_win_1in2out_ap_fixed_16_1_5_3_0_1024_U0_ap_done & sliding_win_1in2out_ap_fixed_16_1_5_3_0_1024_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_data2window_V_1 <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_data2window_V_1 <= ap_sync_channel_write_data2window_V_1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_channel_write_windowed_V_0 <= 1'b0;
    end else begin
        if (((window_fn_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_0_0_1024_2_2_U0_ap_done & window_fn_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_0_0_1024_2_2_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_windowed_V_0 <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_windowed_V_0 <= ap_sync_channel_write_windowed_V_0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_channel_write_windowed_V_1 <= 1'b0;
    end else begin
        if (((window_fn_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_0_0_1024_2_2_U0_ap_done & window_fn_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_0_0_1024_2_2_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_windowed_V_1 <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_windowed_V_1 <= ap_sync_channel_write_windowed_V_1;
        end
    end
end

assign Loop_real2xfft_output_proc9_U0_ap_continue = 1'b1;

assign Loop_real2xfft_output_proc9_U0_ap_start = (windowed_V_1_t_empty_n & windowed_V_0_t_empty_n);

assign Loop_real2xfft_output_proc9_U0_start_full_n = 1'b1;

assign Loop_real2xfft_output_proc9_U0_start_write = 1'b0;

assign ap_channel_done_data2window_V_0 = (sliding_win_1in2out_ap_fixed_16_1_5_3_0_1024_U0_ap_done & (ap_sync_reg_channel_write_data2window_V_0 ^ 1'b1));

assign ap_channel_done_data2window_V_1 = (sliding_win_1in2out_ap_fixed_16_1_5_3_0_1024_U0_ap_done & (ap_sync_reg_channel_write_data2window_V_1 ^ 1'b1));

assign ap_channel_done_windowed_V_0 = (window_fn_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_0_0_1024_2_2_U0_ap_done & (ap_sync_reg_channel_write_windowed_V_0 ^ 1'b1));

assign ap_channel_done_windowed_V_1 = (window_fn_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_0_0_1024_2_2_U0_ap_done & (ap_sync_reg_channel_write_windowed_V_1 ^ 1'b1));

assign ap_done = Loop_real2xfft_output_proc9_U0_ap_done;

assign ap_idle = (window_fn_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_0_0_1024_2_2_U0_ap_idle & sliding_win_1in2out_ap_fixed_16_1_5_3_0_1024_U0_ap_idle & (windowed_V_1_t_empty_n ^ 1'b1) & (windowed_V_0_t_empty_n ^ 1'b1) & (data2window_V_1_t_empty_n ^ 1'b1) & (data2window_V_0_t_empty_n ^ 1'b1) & Loop_real2xfft_output_proc9_U0_ap_idle);

assign ap_ready = sliding_win_1in2out_ap_fixed_16_1_5_3_0_1024_U0_ap_ready;

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign ap_sync_channel_write_data2window_V_0 = ((sliding_win_1in2out_ap_fixed_16_1_5_3_0_1024_U0_dout_full_n & ap_channel_done_data2window_V_0) | ap_sync_reg_channel_write_data2window_V_0);

assign ap_sync_channel_write_data2window_V_1 = ((sliding_win_1in2out_ap_fixed_16_1_5_3_0_1024_U0_dout1_full_n & ap_channel_done_data2window_V_1) | ap_sync_reg_channel_write_data2window_V_1);

assign ap_sync_channel_write_windowed_V_0 = ((window_fn_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_0_0_1024_2_2_U0_outdata_full_n & ap_channel_done_windowed_V_0) | ap_sync_reg_channel_write_windowed_V_0);

assign ap_sync_channel_write_windowed_V_1 = ((window_fn_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_0_0_1024_2_2_U0_outdata2_full_n & ap_channel_done_windowed_V_1) | ap_sync_reg_channel_write_windowed_V_1);

assign ap_sync_continue = 1'b1;

assign ap_sync_done = Loop_real2xfft_output_proc9_U0_ap_done;

assign ap_sync_ready = sliding_win_1in2out_ap_fixed_16_1_5_3_0_1024_U0_ap_ready;

assign din_V_TREADY = sliding_win_1in2out_ap_fixed_16_1_5_3_0_1024_U0_din_V_TREADY;

assign dout_V_TDATA = Loop_real2xfft_output_proc9_U0_dout_V_TDATA;

assign dout_V_TVALID = Loop_real2xfft_output_proc9_U0_dout_V_TVALID;

assign sliding_win_1in2out_ap_fixed_16_1_5_3_0_1024_U0_ap_continue = (ap_sync_channel_write_data2window_V_1 & ap_sync_channel_write_data2window_V_0);

assign sliding_win_1in2out_ap_fixed_16_1_5_3_0_1024_U0_ap_start = ap_start;

assign sliding_win_1in2out_ap_fixed_16_1_5_3_0_1024_U0_dout1_full_n = data2window_V_1_i_full_n;

assign sliding_win_1in2out_ap_fixed_16_1_5_3_0_1024_U0_dout_full_n = data2window_V_0_i_full_n;

assign sliding_win_1in2out_ap_fixed_16_1_5_3_0_1024_U0_start_full_n = 1'b1;

assign sliding_win_1in2out_ap_fixed_16_1_5_3_0_1024_U0_start_write = 1'b0;

assign window_fn_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_0_0_1024_2_2_U0_ap_continue = (ap_sync_channel_write_windowed_V_1 & ap_sync_channel_write_windowed_V_0);

assign window_fn_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_0_0_1024_2_2_U0_ap_start = (data2window_V_1_t_empty_n & data2window_V_0_t_empty_n);

assign window_fn_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_0_0_1024_2_2_U0_outdata2_full_n = windowed_V_1_i_full_n;

assign window_fn_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_0_0_1024_2_2_U0_outdata_full_n = windowed_V_0_i_full_n;

assign window_fn_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_0_0_1024_2_2_U0_start_full_n = 1'b1;

assign window_fn_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_0_0_1024_2_2_U0_start_write = 1'b0;


// synthesis translate_off
`include "hls_real2xfft_hls_deadlock_detector.vh"
// synthesis translate_on

endmodule //hls_real2xfft

