# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/Zynq_Design/Zynq_Design.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Zynq_Design || ORIG_REF_NAME==Zynq_Design} -quiet] -quiet

# IP: bd/Zynq_Design/ip/Zynq_Design_processing_system7_0_0/Zynq_Design_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Zynq_Design_processing_system7_0_0 || ORIG_REF_NAME==Zynq_Design_processing_system7_0_0} -quiet] -quiet

# IP: bd/Zynq_Design/ip/Zynq_Design_hls_macc_0_0/Zynq_Design_hls_macc_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Zynq_Design_hls_macc_0_0 || ORIG_REF_NAME==Zynq_Design_hls_macc_0_0} -quiet] -quiet

# IP: bd/Zynq_Design/ip/Zynq_Design_ps7_0_axi_periph_0/Zynq_Design_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Zynq_Design_ps7_0_axi_periph_0 || ORIG_REF_NAME==Zynq_Design_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/Zynq_Design/ip/Zynq_Design_rst_ps7_0_50M_0/Zynq_Design_rst_ps7_0_50M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Zynq_Design_rst_ps7_0_50M_0 || ORIG_REF_NAME==Zynq_Design_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/Zynq_Design/ip/Zynq_Design_xbar_0/Zynq_Design_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Zynq_Design_xbar_0 || ORIG_REF_NAME==Zynq_Design_xbar_0} -quiet] -quiet

# IP: bd/Zynq_Design/ip/Zynq_Design_auto_pc_0/Zynq_Design_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Zynq_Design_auto_pc_0 || ORIG_REF_NAME==Zynq_Design_auto_pc_0} -quiet] -quiet

# IP: bd/Zynq_Design/ip/Zynq_Design_axi_intc_0_0/Zynq_Design_axi_intc_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Zynq_Design_axi_intc_0_0 || ORIG_REF_NAME==Zynq_Design_axi_intc_0_0} -quiet] -quiet

# XDC: e:/Courses/EEE5060/LabA/Using_IP_with_Zynq/lab1/project_1/project_1.gen/sources_1/bd/Zynq_Design/Zynq_Design_ooc.xdc
