-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2 (64-bit)
-- Version: 2020.2
-- Copyright (C) Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity hls_real2xfft_sliding_win_1in2out_ap_fixed_16_1_5_3_0_1024_s is
port (
    din_V_TDATA : IN STD_LOGIC_VECTOR (15 downto 0);
    dout_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
    dout_ce0 : OUT STD_LOGIC;
    dout_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    dout_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    dout_we0 : OUT STD_LOGIC;
    dout_address1 : OUT STD_LOGIC_VECTOR (8 downto 0);
    dout_ce1 : OUT STD_LOGIC;
    dout_d1 : OUT STD_LOGIC_VECTOR (15 downto 0);
    dout_q1 : IN STD_LOGIC_VECTOR (15 downto 0);
    dout_we1 : OUT STD_LOGIC;
    dout1_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
    dout1_ce0 : OUT STD_LOGIC;
    dout1_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    dout1_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    dout1_we0 : OUT STD_LOGIC;
    dout1_address1 : OUT STD_LOGIC_VECTOR (8 downto 0);
    dout1_ce1 : OUT STD_LOGIC;
    dout1_d1 : OUT STD_LOGIC_VECTOR (15 downto 0);
    dout1_q1 : IN STD_LOGIC_VECTOR (15 downto 0);
    dout1_we1 : OUT STD_LOGIC;
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    din_V_TVALID : IN STD_LOGIC;
    din_V_TREADY : OUT STD_LOGIC;
    ap_start : IN STD_LOGIC;
    dout1_full_n : IN STD_LOGIC;
    dout1_write : OUT STD_LOGIC;
    dout_full_n : IN STD_LOGIC;
    dout_write : OUT STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC );
end;


architecture behav of hls_real2xfft_sliding_win_1in2out_ap_fixed_16_1_5_3_0_1024_s is 
    constant ap_const_lv9_0 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_logic_1 : STD_LOGIC := '1';

attribute shreg_extract : string;
    signal sliding_win_1in2out_ap_fixed_16_1_5_3_0_1024_Loop_sliding_win_delay_proc7_U0_ap_start : STD_LOGIC;
    signal sliding_win_1in2out_ap_fixed_16_1_5_3_0_1024_Loop_sliding_win_delay_proc7_U0_ap_done : STD_LOGIC;
    signal sliding_win_1in2out_ap_fixed_16_1_5_3_0_1024_Loop_sliding_win_delay_proc7_U0_ap_continue : STD_LOGIC;
    signal sliding_win_1in2out_ap_fixed_16_1_5_3_0_1024_Loop_sliding_win_delay_proc7_U0_ap_idle : STD_LOGIC;
    signal sliding_win_1in2out_ap_fixed_16_1_5_3_0_1024_Loop_sliding_win_delay_proc7_U0_ap_ready : STD_LOGIC;
    signal sliding_win_1in2out_ap_fixed_16_1_5_3_0_1024_Loop_sliding_win_delay_proc7_U0_start_out : STD_LOGIC;
    signal sliding_win_1in2out_ap_fixed_16_1_5_3_0_1024_Loop_sliding_win_delay_proc7_U0_start_write : STD_LOGIC;
    signal sliding_win_1in2out_ap_fixed_16_1_5_3_0_1024_Loop_sliding_win_delay_proc7_U0_din_V_TREADY : STD_LOGIC;
    signal sliding_win_1in2out_ap_fixed_16_1_5_3_0_1024_Loop_sliding_win_delay_proc7_U0_nodelay_V_din : STD_LOGIC_VECTOR (15 downto 0);
    signal sliding_win_1in2out_ap_fixed_16_1_5_3_0_1024_Loop_sliding_win_delay_proc7_U0_nodelay_V_write : STD_LOGIC;
    signal sliding_win_1in2out_ap_fixed_16_1_5_3_0_1024_Loop_sliding_win_delay_proc7_U0_delayed_V_din : STD_LOGIC_VECTOR (15 downto 0);
    signal sliding_win_1in2out_ap_fixed_16_1_5_3_0_1024_Loop_sliding_win_delay_proc7_U0_delayed_V_write : STD_LOGIC;
    signal sliding_win_1in2out_ap_fixed_16_1_5_3_0_1024_Loop_sliding_win_output_proc8_U0_ap_start : STD_LOGIC;
    signal sliding_win_1in2out_ap_fixed_16_1_5_3_0_1024_Loop_sliding_win_output_proc8_U0_ap_done : STD_LOGIC;
    signal sliding_win_1in2out_ap_fixed_16_1_5_3_0_1024_Loop_sliding_win_output_proc8_U0_ap_continue : STD_LOGIC;
    signal sliding_win_1in2out_ap_fixed_16_1_5_3_0_1024_Loop_sliding_win_output_proc8_U0_ap_idle : STD_LOGIC;
    signal sliding_win_1in2out_ap_fixed_16_1_5_3_0_1024_Loop_sliding_win_output_proc8_U0_ap_ready : STD_LOGIC;
    signal sliding_win_1in2out_ap_fixed_16_1_5_3_0_1024_Loop_sliding_win_output_proc8_U0_delayed_V_read : STD_LOGIC;
    signal sliding_win_1in2out_ap_fixed_16_1_5_3_0_1024_Loop_sliding_win_output_proc8_U0_nodelay_V_read : STD_LOGIC;
    signal sliding_win_1in2out_ap_fixed_16_1_5_3_0_1024_Loop_sliding_win_output_proc8_U0_dout1_address0 : STD_LOGIC_VECTOR (8 downto 0);
    signal sliding_win_1in2out_ap_fixed_16_1_5_3_0_1024_Loop_sliding_win_output_proc8_U0_dout1_ce0 : STD_LOGIC;
    signal sliding_win_1in2out_ap_fixed_16_1_5_3_0_1024_Loop_sliding_win_output_proc8_U0_dout1_we0 : STD_LOGIC;
    signal sliding_win_1in2out_ap_fixed_16_1_5_3_0_1024_Loop_sliding_win_output_proc8_U0_dout1_d0 : STD_LOGIC_VECTOR (15 downto 0);
    signal sliding_win_1in2out_ap_fixed_16_1_5_3_0_1024_Loop_sliding_win_output_proc8_U0_dout_address0 : STD_LOGIC_VECTOR (8 downto 0);
    signal sliding_win_1in2out_ap_fixed_16_1_5_3_0_1024_Loop_sliding_win_output_proc8_U0_dout_ce0 : STD_LOGIC;
    signal sliding_win_1in2out_ap_fixed_16_1_5_3_0_1024_Loop_sliding_win_output_proc8_U0_dout_we0 : STD_LOGIC;
    signal sliding_win_1in2out_ap_fixed_16_1_5_3_0_1024_Loop_sliding_win_output_proc8_U0_dout_d0 : STD_LOGIC_VECTOR (15 downto 0);
    signal sliding_win_1in2out_ap_fixed_16_1_5_3_0_1024_Loop_sliding_win_output_proc8_U0_dout1_full_n : STD_LOGIC;
    signal sliding_win_1in2out_ap_fixed_16_1_5_3_0_1024_Loop_sliding_win_output_proc8_U0_dout1_write : STD_LOGIC;
    signal sliding_win_1in2out_ap_fixed_16_1_5_3_0_1024_Loop_sliding_win_output_proc8_U0_dout_full_n : STD_LOGIC;
    signal sliding_win_1in2out_ap_fixed_16_1_5_3_0_1024_Loop_sliding_win_output_proc8_U0_dout_write : STD_LOGIC;
    signal ap_sync_continue : STD_LOGIC;
    signal nodelay_V_full_n : STD_LOGIC;
    signal nodelay_V_dout : STD_LOGIC_VECTOR (15 downto 0);
    signal nodelay_V_empty_n : STD_LOGIC;
    signal delayed_V_full_n : STD_LOGIC;
    signal delayed_V_dout : STD_LOGIC_VECTOR (15 downto 0);
    signal delayed_V_empty_n : STD_LOGIC;
    signal ap_sync_done : STD_LOGIC;
    signal ap_sync_ready : STD_LOGIC;
    signal start_for_sliding_win_1in2out_ap_fixed_16_1_5_3_0_1024_Loop_sliding_win_output_proc8_U0_din : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_sliding_win_1in2out_ap_fixed_16_1_5_3_0_1024_Loop_sliding_win_output_proc8_U0_full_n : STD_LOGIC;
    signal start_for_sliding_win_1in2out_ap_fixed_16_1_5_3_0_1024_Loop_sliding_win_output_proc8_U0_dout : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_sliding_win_1in2out_ap_fixed_16_1_5_3_0_1024_Loop_sliding_win_output_proc8_U0_empty_n : STD_LOGIC;
    signal sliding_win_1in2out_ap_fixed_16_1_5_3_0_1024_Loop_sliding_win_output_proc8_U0_start_full_n : STD_LOGIC;
    signal sliding_win_1in2out_ap_fixed_16_1_5_3_0_1024_Loop_sliding_win_output_proc8_U0_start_write : STD_LOGIC;

    component hls_real2xfft_sliding_win_1in2out_ap_fixed_16_1_5_3_0_1024_Loop_sliding_win_delay_proc7 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        start_full_n : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        start_out : OUT STD_LOGIC;
        start_write : OUT STD_LOGIC;
        din_V_TDATA : IN STD_LOGIC_VECTOR (15 downto 0);
        din_V_TVALID : IN STD_LOGIC;
        din_V_TREADY : OUT STD_LOGIC;
        nodelay_V_din : OUT STD_LOGIC_VECTOR (15 downto 0);
        nodelay_V_full_n : IN STD_LOGIC;
        nodelay_V_write : OUT STD_LOGIC;
        delayed_V_din : OUT STD_LOGIC_VECTOR (15 downto 0);
        delayed_V_full_n : IN STD_LOGIC;
        delayed_V_write : OUT STD_LOGIC );
    end component;


    component hls_real2xfft_sliding_win_1in2out_ap_fixed_16_1_5_3_0_1024_Loop_sliding_win_output_proc8 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        delayed_V_dout : IN STD_LOGIC_VECTOR (15 downto 0);
        delayed_V_empty_n : IN STD_LOGIC;
        delayed_V_read : OUT STD_LOGIC;
        nodelay_V_dout : IN STD_LOGIC_VECTOR (15 downto 0);
        nodelay_V_empty_n : IN STD_LOGIC;
        nodelay_V_read : OUT STD_LOGIC;
        dout1_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
        dout1_ce0 : OUT STD_LOGIC;
        dout1_we0 : OUT STD_LOGIC;
        dout1_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
        dout_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
        dout_ce0 : OUT STD_LOGIC;
        dout_we0 : OUT STD_LOGIC;
        dout_d0 : OUT STD_LOGIC_VECTOR (15 downto 0) );
    end component;


    component hls_real2xfft_fifo_w16_d512_A IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (15 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (15 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component hls_real2xfft_fifo_w16_d256_A IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (15 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (15 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component hls_real2xfft_start_for_sliding_win_1in2out_ap_fixed_16_1_5_3_0_1024_Loop_sliding_win_outpucud IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (0 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (0 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;



begin
    sliding_win_1in2out_ap_fixed_16_1_5_3_0_1024_Loop_sliding_win_delay_proc7_U0 : component hls_real2xfft_sliding_win_1in2out_ap_fixed_16_1_5_3_0_1024_Loop_sliding_win_delay_proc7
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => sliding_win_1in2out_ap_fixed_16_1_5_3_0_1024_Loop_sliding_win_delay_proc7_U0_ap_start,
        start_full_n => start_for_sliding_win_1in2out_ap_fixed_16_1_5_3_0_1024_Loop_sliding_win_output_proc8_U0_full_n,
        ap_done => sliding_win_1in2out_ap_fixed_16_1_5_3_0_1024_Loop_sliding_win_delay_proc7_U0_ap_done,
        ap_continue => sliding_win_1in2out_ap_fixed_16_1_5_3_0_1024_Loop_sliding_win_delay_proc7_U0_ap_continue,
        ap_idle => sliding_win_1in2out_ap_fixed_16_1_5_3_0_1024_Loop_sliding_win_delay_proc7_U0_ap_idle,
        ap_ready => sliding_win_1in2out_ap_fixed_16_1_5_3_0_1024_Loop_sliding_win_delay_proc7_U0_ap_ready,
        start_out => sliding_win_1in2out_ap_fixed_16_1_5_3_0_1024_Loop_sliding_win_delay_proc7_U0_start_out,
        start_write => sliding_win_1in2out_ap_fixed_16_1_5_3_0_1024_Loop_sliding_win_delay_proc7_U0_start_write,
        din_V_TDATA => din_V_TDATA,
        din_V_TVALID => din_V_TVALID,
        din_V_TREADY => sliding_win_1in2out_ap_fixed_16_1_5_3_0_1024_Loop_sliding_win_delay_proc7_U0_din_V_TREADY,
        nodelay_V_din => sliding_win_1in2out_ap_fixed_16_1_5_3_0_1024_Loop_sliding_win_delay_proc7_U0_nodelay_V_din,
        nodelay_V_full_n => nodelay_V_full_n,
        nodelay_V_write => sliding_win_1in2out_ap_fixed_16_1_5_3_0_1024_Loop_sliding_win_delay_proc7_U0_nodelay_V_write,
        delayed_V_din => sliding_win_1in2out_ap_fixed_16_1_5_3_0_1024_Loop_sliding_win_delay_proc7_U0_delayed_V_din,
        delayed_V_full_n => delayed_V_full_n,
        delayed_V_write => sliding_win_1in2out_ap_fixed_16_1_5_3_0_1024_Loop_sliding_win_delay_proc7_U0_delayed_V_write);

    sliding_win_1in2out_ap_fixed_16_1_5_3_0_1024_Loop_sliding_win_output_proc8_U0 : component hls_real2xfft_sliding_win_1in2out_ap_fixed_16_1_5_3_0_1024_Loop_sliding_win_output_proc8
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => sliding_win_1in2out_ap_fixed_16_1_5_3_0_1024_Loop_sliding_win_output_proc8_U0_ap_start,
        ap_done => sliding_win_1in2out_ap_fixed_16_1_5_3_0_1024_Loop_sliding_win_output_proc8_U0_ap_done,
        ap_continue => sliding_win_1in2out_ap_fixed_16_1_5_3_0_1024_Loop_sliding_win_output_proc8_U0_ap_continue,
        ap_idle => sliding_win_1in2out_ap_fixed_16_1_5_3_0_1024_Loop_sliding_win_output_proc8_U0_ap_idle,
        ap_ready => sliding_win_1in2out_ap_fixed_16_1_5_3_0_1024_Loop_sliding_win_output_proc8_U0_ap_ready,
        delayed_V_dout => delayed_V_dout,
        delayed_V_empty_n => delayed_V_empty_n,
        delayed_V_read => sliding_win_1in2out_ap_fixed_16_1_5_3_0_1024_Loop_sliding_win_output_proc8_U0_delayed_V_read,
        nodelay_V_dout => nodelay_V_dout,
        nodelay_V_empty_n => nodelay_V_empty_n,
        nodelay_V_read => sliding_win_1in2out_ap_fixed_16_1_5_3_0_1024_Loop_sliding_win_output_proc8_U0_nodelay_V_read,
        dout1_address0 => sliding_win_1in2out_ap_fixed_16_1_5_3_0_1024_Loop_sliding_win_output_proc8_U0_dout1_address0,
        dout1_ce0 => sliding_win_1in2out_ap_fixed_16_1_5_3_0_1024_Loop_sliding_win_output_proc8_U0_dout1_ce0,
        dout1_we0 => sliding_win_1in2out_ap_fixed_16_1_5_3_0_1024_Loop_sliding_win_output_proc8_U0_dout1_we0,
        dout1_d0 => sliding_win_1in2out_ap_fixed_16_1_5_3_0_1024_Loop_sliding_win_output_proc8_U0_dout1_d0,
        dout_address0 => sliding_win_1in2out_ap_fixed_16_1_5_3_0_1024_Loop_sliding_win_output_proc8_U0_dout_address0,
        dout_ce0 => sliding_win_1in2out_ap_fixed_16_1_5_3_0_1024_Loop_sliding_win_output_proc8_U0_dout_ce0,
        dout_we0 => sliding_win_1in2out_ap_fixed_16_1_5_3_0_1024_Loop_sliding_win_output_proc8_U0_dout_we0,
        dout_d0 => sliding_win_1in2out_ap_fixed_16_1_5_3_0_1024_Loop_sliding_win_output_proc8_U0_dout_d0);

    nodelay_V_U : component hls_real2xfft_fifo_w16_d512_A
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => sliding_win_1in2out_ap_fixed_16_1_5_3_0_1024_Loop_sliding_win_delay_proc7_U0_nodelay_V_din,
        if_full_n => nodelay_V_full_n,
        if_write => sliding_win_1in2out_ap_fixed_16_1_5_3_0_1024_Loop_sliding_win_delay_proc7_U0_nodelay_V_write,
        if_dout => nodelay_V_dout,
        if_empty_n => nodelay_V_empty_n,
        if_read => sliding_win_1in2out_ap_fixed_16_1_5_3_0_1024_Loop_sliding_win_output_proc8_U0_nodelay_V_read);

    delayed_V_U : component hls_real2xfft_fifo_w16_d256_A
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => sliding_win_1in2out_ap_fixed_16_1_5_3_0_1024_Loop_sliding_win_delay_proc7_U0_delayed_V_din,
        if_full_n => delayed_V_full_n,
        if_write => sliding_win_1in2out_ap_fixed_16_1_5_3_0_1024_Loop_sliding_win_delay_proc7_U0_delayed_V_write,
        if_dout => delayed_V_dout,
        if_empty_n => delayed_V_empty_n,
        if_read => sliding_win_1in2out_ap_fixed_16_1_5_3_0_1024_Loop_sliding_win_output_proc8_U0_delayed_V_read);

    start_for_sliding_win_1in2out_ap_fixed_16_1_5_3_0_1024_Loop_sliding_win_outpucud_U : component hls_real2xfft_start_for_sliding_win_1in2out_ap_fixed_16_1_5_3_0_1024_Loop_sliding_win_outpucud
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => start_for_sliding_win_1in2out_ap_fixed_16_1_5_3_0_1024_Loop_sliding_win_output_proc8_U0_din,
        if_full_n => start_for_sliding_win_1in2out_ap_fixed_16_1_5_3_0_1024_Loop_sliding_win_output_proc8_U0_full_n,
        if_write => sliding_win_1in2out_ap_fixed_16_1_5_3_0_1024_Loop_sliding_win_delay_proc7_U0_start_write,
        if_dout => start_for_sliding_win_1in2out_ap_fixed_16_1_5_3_0_1024_Loop_sliding_win_output_proc8_U0_dout,
        if_empty_n => start_for_sliding_win_1in2out_ap_fixed_16_1_5_3_0_1024_Loop_sliding_win_output_proc8_U0_empty_n,
        if_read => sliding_win_1in2out_ap_fixed_16_1_5_3_0_1024_Loop_sliding_win_output_proc8_U0_ap_ready);




    ap_done <= sliding_win_1in2out_ap_fixed_16_1_5_3_0_1024_Loop_sliding_win_output_proc8_U0_ap_done;
    ap_idle <= (sliding_win_1in2out_ap_fixed_16_1_5_3_0_1024_Loop_sliding_win_output_proc8_U0_ap_idle and sliding_win_1in2out_ap_fixed_16_1_5_3_0_1024_Loop_sliding_win_delay_proc7_U0_ap_idle);
    ap_ready <= sliding_win_1in2out_ap_fixed_16_1_5_3_0_1024_Loop_sliding_win_delay_proc7_U0_ap_ready;
    ap_sync_continue <= ap_continue;
    ap_sync_done <= sliding_win_1in2out_ap_fixed_16_1_5_3_0_1024_Loop_sliding_win_output_proc8_U0_ap_done;
    ap_sync_ready <= sliding_win_1in2out_ap_fixed_16_1_5_3_0_1024_Loop_sliding_win_delay_proc7_U0_ap_ready;
    din_V_TREADY <= sliding_win_1in2out_ap_fixed_16_1_5_3_0_1024_Loop_sliding_win_delay_proc7_U0_din_V_TREADY;
    dout1_address0 <= sliding_win_1in2out_ap_fixed_16_1_5_3_0_1024_Loop_sliding_win_output_proc8_U0_dout1_address0;
    dout1_address1 <= ap_const_lv9_0;
    dout1_ce0 <= sliding_win_1in2out_ap_fixed_16_1_5_3_0_1024_Loop_sliding_win_output_proc8_U0_dout1_ce0;
    dout1_ce1 <= ap_const_logic_0;
    dout1_d0 <= sliding_win_1in2out_ap_fixed_16_1_5_3_0_1024_Loop_sliding_win_output_proc8_U0_dout1_d0;
    dout1_d1 <= ap_const_lv16_0;
    dout1_we0 <= sliding_win_1in2out_ap_fixed_16_1_5_3_0_1024_Loop_sliding_win_output_proc8_U0_dout1_we0;
    dout1_we1 <= ap_const_logic_0;
    dout1_write <= sliding_win_1in2out_ap_fixed_16_1_5_3_0_1024_Loop_sliding_win_output_proc8_U0_dout1_write;
    dout_address0 <= sliding_win_1in2out_ap_fixed_16_1_5_3_0_1024_Loop_sliding_win_output_proc8_U0_dout_address0;
    dout_address1 <= ap_const_lv9_0;
    dout_ce0 <= sliding_win_1in2out_ap_fixed_16_1_5_3_0_1024_Loop_sliding_win_output_proc8_U0_dout_ce0;
    dout_ce1 <= ap_const_logic_0;
    dout_d0 <= sliding_win_1in2out_ap_fixed_16_1_5_3_0_1024_Loop_sliding_win_output_proc8_U0_dout_d0;
    dout_d1 <= ap_const_lv16_0;
    dout_we0 <= sliding_win_1in2out_ap_fixed_16_1_5_3_0_1024_Loop_sliding_win_output_proc8_U0_dout_we0;
    dout_we1 <= ap_const_logic_0;
    dout_write <= sliding_win_1in2out_ap_fixed_16_1_5_3_0_1024_Loop_sliding_win_output_proc8_U0_dout_write;
    sliding_win_1in2out_ap_fixed_16_1_5_3_0_1024_Loop_sliding_win_delay_proc7_U0_ap_continue <= ap_const_logic_1;
    sliding_win_1in2out_ap_fixed_16_1_5_3_0_1024_Loop_sliding_win_delay_proc7_U0_ap_start <= ap_start;
    sliding_win_1in2out_ap_fixed_16_1_5_3_0_1024_Loop_sliding_win_output_proc8_U0_ap_continue <= ap_continue;
    sliding_win_1in2out_ap_fixed_16_1_5_3_0_1024_Loop_sliding_win_output_proc8_U0_ap_start <= start_for_sliding_win_1in2out_ap_fixed_16_1_5_3_0_1024_Loop_sliding_win_output_proc8_U0_empty_n;
    sliding_win_1in2out_ap_fixed_16_1_5_3_0_1024_Loop_sliding_win_output_proc8_U0_dout1_full_n <= dout1_full_n;
    sliding_win_1in2out_ap_fixed_16_1_5_3_0_1024_Loop_sliding_win_output_proc8_U0_dout1_write <= ap_const_logic_0;
    sliding_win_1in2out_ap_fixed_16_1_5_3_0_1024_Loop_sliding_win_output_proc8_U0_dout_full_n <= dout_full_n;
    sliding_win_1in2out_ap_fixed_16_1_5_3_0_1024_Loop_sliding_win_output_proc8_U0_dout_write <= ap_const_logic_0;
    sliding_win_1in2out_ap_fixed_16_1_5_3_0_1024_Loop_sliding_win_output_proc8_U0_start_full_n <= ap_const_logic_1;
    sliding_win_1in2out_ap_fixed_16_1_5_3_0_1024_Loop_sliding_win_output_proc8_U0_start_write <= ap_const_logic_0;
    start_for_sliding_win_1in2out_ap_fixed_16_1_5_3_0_1024_Loop_sliding_win_output_proc8_U0_din <= (0=>ap_const_logic_1, others=>'-');
end behav;
